### ISSUE TITLE
Import Email from Outlook

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#679] opened 2017-07-06 17:15 UTC
Hello,

I am having a issue when importing Outlook source in to the import email object. My terminal is giving back the following:

```
2017/07/06 13:03:35 api.go:556: malformed MIME header line: </style><![endif]--
`><style><!--`
127.0.0.1 - - [06/Jul/2017:13:03:35 -0400] "POST /api/import/email HTTP/2.0" 200
 89 "https://127.0.0.1:3333/templates" "Mozilla/5.0 (Windows NT 6.1; Win64; x64)
 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

I then added a registry value SaveAllMIMENotJustHeaders and still nothing is working. The email imports correctly for gmail, not sure why Outlook is being so much a pain. 

Thank you

**Comment by jordan-wright** [comment] 2017-07-11 02:39
This definitely looks like the issue is that the MIME headers aren't being included. I'm not sure how to do this in Outlook specifically, but you'll want to find the way to view the original email (similar to Gmail) to use when importing.

If you're already doing this, it would help us out if you could show us a sample email that isn't importing so we can try to reproduce the issue on our side.

**Comment by loza0269** [comment] 2017-07-11 14:38
It's going to be a bit long but this is a Outlook source code for a dropbox email

`<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body><div dir="ltr"><p style="box-sizing:border-box;margin:0px 0px 10.5px;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><img alt="Dropbox logo" title="" src="https://security.berkeley.edu/sites/default/files/styles/width_100/public/glyph_342x_0.png?itok=gW9ShD4e&amp;c=7d72319ece4d25d48f54bc41e937ab03" style="box-sizing: border-box; border: 0px; vertical-align: middle; height: auto; max-width: 100%;"></p><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><br style="box-sizing:border-box">Hello,</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">You just received a file through Dropbox Share Application.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Please click below and log in to view file.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><a title="http://authberkeleyedu.atwebpages.com/caslogin.php" style="box-sizing:border-box;background-color:transparent;color:rgb(0,50,98);text-decoration-line:underline" href="http://172.31.61.36:80?rid=csHFNsn">View file</a></div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Every time a friend installs Dropbox, we'll give both of you 1 GB of</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">space for free! Need even more space? Upgrade your Dropbox and get 1 TB</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">(1,000 GB) of space.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Happy Dropboxing.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">- The Dropbox Team</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Dropbox, Inc., PO Box 77767, San Francisco, CA 94107 © 2017 Dropbox</div></div>
<img alt="" style="display: none" src="http://172.31.61.36:80/track?rid=csHFNsn"></body></html>`

**Comment by loza0269** [comment] 2017-07-11 14:39
This is the outlook source code

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body><div dir="ltr"><p style="box-sizing:border-box;margin:0px 0px 10.5px;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><img alt="Dropbox logo" title="" src="https://security.berkeley.edu/sites/default/files/styles/width_100/public/glyph_342x_0.png?itok=gW9ShD4e&amp;c=7d72319ece4d25d48f54bc41e937ab03" style="box-sizing: border-box; border: 0px; vertical-align: middle; height: auto; max-width: 100%;"></p><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><br style="box-sizing:border-box">Hello,</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">You just received a file through Dropbox Share Application.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Please click below and log in to view file.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><a title="http://authberkeleyedu.atwebpages.com/caslogin.php" style="box-sizing:border-box;background-color:transparent;color:rgb(0,50,98);text-decoration-line:underline" href="http://172.31.61.36:80?rid=csHFNsn">View file</a></div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Every time a friend installs Dropbox, we'll give both of you 1 GB of</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">space for free! Need even more space? Upgrade your Dropbox and get 1 TB</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">(1,000 GB) of space.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Happy Dropboxing.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">- The Dropbox Team</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Dropbox, Inc., PO Box 77767, San Francisco, CA 94107 © 2017 Dropbox</div></div>
<img alt="" style="display: none" src="http://172.31.61.36:80/track?rid=csHFNsn"></body></html>

**Comment by loza0269** [comment] 2017-07-11 14:41
This is the outlook source code

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body><div dir="ltr"><p style="box-sizing:border-box;margin:0px 0px 10.5px;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><img alt="Dropbox logo" title="" src="https://security.berkeley.edu/sites/default/files/styles/width_100/public/glyph_342x_0.png?itok=gW9ShD4e&amp;c=7d72319ece4d25d48f54bc41e937ab03" style="box-sizing: border-box; border: 0px; vertical-align: middle; height: auto; max-width: 100%;"></p><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><br style="box-sizing:border-box">Hello,</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">You just received a file through Dropbox Share Application.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Please click below and log in to view file.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)"><a title="http://authberkeleyedu.atwebpages.com/caslogin.php" style="box-sizing:border-box;background-color:transparent;color:rgb(0,50,98);text-decoration-line:underline" href="http://172.31.61.36:80?rid=csHFNsn">View file</a></div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Every time a friend installs Dropbox, we'll give both of you 1 GB of</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">space for free! Need even more space? Upgrade your Dropbox and get 1 TB</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">(1,000 GB) of space.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Happy Dropboxing.</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">- The Dropbox Team</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">&nbsp;</div><div style="box-sizing:border-box;color:rgb(51,51,51);font-family:&quot;Open Sans&quot;,sans-serif;font-size:15px;background-color:rgb(249,249,249)">Dropbox, Inc., PO Box 77767, San Francisco, CA 94107 © 2017 Dropbox</div></div>
<img alt="" style="display: none" src="http://172.31.61.36:80/track?rid=csHFNsn"></body></html>

**Comment by jordan-wright** [comment] 2017-07-18 02:37
This is just the HTML and not the complete MIME representation of the email. You will need to import the complete source of the email, including headers. You can find more information [here](https://www.lifewire.com/view-complete-message-source-outlook-1173713).

Since we've found the reason for this error, I'm going to go ahead and close this one out. Let me know if you continue to run into issues when importing the full source (please provide the source if this is the case) and we can re-open to continue troubleshooting.

Thanks for your report!

**Closed by jordan-wright** 2017-07-18 02:37 UTC
Labels: support
