### ISSUE TITLE
campaign completed_date  saving date 0001-01-01T00:00:00Z

### ISSUE THREAD

**Issue by dipeshpatel306** [gophish/gophish#658] opened 2017-06-16 20:52 UTC
Hello, 

When i create new campaign at that time taking campaign start date and campaign end date. but end date save correct but having issue to save completed_date  field save  0001-01-01T00:00:00Z

**Comment by jordan-wright** [comment] 2017-06-16 22:38
So are you actually marking the campaign as complete and then seeing that date? If the campaign has not been marked complete, then you will see `completed_date` listed as the default 0001-01-01T00:00:00Z since the campaign has not been completed yet.

**Comment by jordan-wright** [comment] 2017-06-19 15:10
This is not possible with Gophish currently. You can only set the `launch_date` which is the date the campaign will start.

There is an open issue at #351 that aims to provide randomized sending which will, by extension, allow you to specify an "end date" for the email sending. However, this isn't completed yet. The date you see in `completed_date` is for the date the campaign is closed. Once it's closed, no more results will be processed for the campaign.

Hope this helps! I'm going to close this one out as a duplicate of #351.

**Closed by jordan-wright** 2017-06-19 15:10 UTC
Labels: support

**Comment by mansichauhan27** [comment] 2020-09-18 04:16
HI, I am facing the same issue,is this fixed?
