### ISSUE TITLE
GoPhish User Login issue

### ISSUE THREAD

**Issue by kevinsample** [gophish/gophish#1208] opened 2018-09-21 20:14 UTC
We're running GoPhish version 0.7.1 and have had some problems logging in to the web console using https://server:3333/login. When a registered user will try to login they'll get a message that the username/password was incorrect and we verified the hashes stored in the database were still the same (we started verifying this after the login issues occurred). We couldn't locate any helpful information in the logs. Later we tried restarting the gophish service and that seems to fix the problem for a day or two.

Does anyone have advise on how to troubleshoot this problem?

**Comment by jordan-wright** [comment] 2018-09-22 16:08
Hi @kevinsample,

Thanks for reaching out! I'm afraid it will be difficult to help troubleshoot this without more information. 🙁 Is there any other information at all you can provide? You may try standing up a separate Gophish instance that doesn't listen externally to see if the problem is able to be reproduced there.

I'm afraid that's about all I can suggest at the moment, since there isn't much to go off of right now.

**Comment by jordan-wright** [comment] 2018-10-04 21:43
Going ahead and closing this out for now since there hasn't been any updates in about 2 weeks. @kevinsample, if you're still encountering the issue, take a look at my suggestions above and let me know if they help get the ball rolling.

If there's any other information you can provide to help us continue troubleshooting, I'll be happy to re-open this issue 😄 

Thanks again for getting in touch!

**Closed by jordan-wright** 2018-10-04 21:43 UTC
Labels: support
