### ISSUE TITLE
link javascript file to go file. 

### ISSUE THREAD

**Issue by Soka96** [gophish/gophish#1424] opened 2019-04-07 08:36 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1  

Brief description of the issue: I am trying  to add new features to gophish for learning purpose . Therefore, I  create new go,js and html files, but when i run the code it seems that the functions in a new go file not execute. 
is there a way to link go files with the source code ??

What are you expecting to see happen? :
My features work properly

What are you seeing happen?
when I click a button , no action happen !

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - create new HTML file and put the path of JS file
 * Step 2 - create new JS file 
 * Step 3- create new  GO file
 * Step 4- modify api.go file 
 * Step 5 - modify route.go file
 * Step 6 - modify the database using (DB Browser SQLite)
 * Step 7 - create new executable file using (go build)

**Comment by jordan-wright** [comment] 2019-04-07 18:19
Hi there!

This seems awfully similar to #1422 and #1423. While it may be a coincidence, for the sake of keeping these issues tidy, can you confirm if you and @nanarosana are working on the same feature?

Either way, I'll have to give the same response as I did in #1422 and #1423 - there isn't enough information here to begin troubleshooting. Please provide the code you've written and the exact steps you've taken to get where you are. This will help us reproduce the issue locally and troubleshoot further. Without the code, I'm afraid we simply can't help.

**Comment by S0larflare** [comment] 2019-04-08 09:12
Something to keep in mind is if you have copied the files to a location away from your GOPATH/GOROOT then the dependencies in the files will still point there. So when you are building you're not building the files that you have modified but rather the original GO files themselves are just being rebuilt in the new folder.

**Comment by Soka96** [comment] 2019-04-09 15:04
Hello everyone 
Yes, we are working on same group, but on different features. 
 Ok, we will give our code. 
 
Do you prefer to give you a download link of our files or just screenshots?

**Comment by jordan-wright** [comment] 2019-04-10 02:15
Hi @Soka96,

I'd recommend forking Gophish and uploading your changes to your local instance on Github.

That said, in addition to the code, we'll need to understand what it is you're trying to add, what you're doing to reproduce the issue, and any other information you can provide. Without that information, I won't move forward troubleshooting since I simply don't have enough time to review someone else's code from scratch without context.

**Comment by Soka96** [comment] 2019-04-10 10:44
thank you very much @jordan-wright 

I am trying to add a feature that allows the user to send an email after launching a campaign based on the act of the recipient (if he opens the phishing email, clicks on the link or submits his credential).
So, I create a new HTML page very similar to the Template page the only difference is I removed (Import Email part, Text tap part and Add Tracking Image part).
Then, I write a new go file and define my own type called (EchoEmail) and used the same functions of template.go and replaced all parameters from (template ) to ( EchoEmail)  as well as the javascript file.
Also, I add two functions in API.go (APIEchoEmails &APIEchoEmail)
finally, I used (go build) command to generate a new executable file. I able to see the new HTML page but when I try to write something and click on (Save) button, no action happens. I try to click the button without fulling the fields but also the error message not display. 
I think there is a problem with my file .go, or maybe there are some necessary steps I did not do. 


I upload my files here: 
https://github.com/Soka96/gophish

**Comment by jordan-wright** [comment] 2019-04-13 16:12
Glancing through the changes it looks like you first aren't creating a database migration which is needed to tell the database how to store the object you're making. You can find an example of that [here](https://github.com/gophish/gophish/pull/1069#issuecomment-390521422).

Next, you'll need to update [gophish.js](https://github.com/gophish/gophish/blob/master/static/js/src/app/gophish.js#L49) to add your new API endpoints. I'd recommend watching your browser's developer console to see errors thrown from your Javascript- that would catch this particular case.

**Comment by Soka96** [comment] 2019-04-13 18:31
thank you for your help 

> var api = {
    // campaigns contains the endpoints for /campaigns
    campaigns: {
        // get() - Queries the API for GET /campaigns
        get: function () {
            return query**("/campaigns/"**, "GET", {}, false)
        },

> 

But I have one more question, ("/campaigns/")  refers to what??

**Comment by jordan-wright** [comment] 2019-04-13 18:56
That says to make a request to `/campaigns/`.

**Comment by Soka96** [comment] 2019-04-14 00:16
Sorry for the inconvenience.
I face another issue, after doing what you say and run the program I get "Error fetching ... " in my new page. I don't have any idea about where I do a mistake because I am a beginner in Golang. 
any help, please?

**Comment by Soka96** [comment] 2019-04-18 15:01
one more question 

In order to send feedback emails to the users, we changed on: 
1.  worker.go
2. maillog.go
3. template-context.go
Is that enough or should we do changes somewhere else?

**Comment by jordan-wright** [comment] 2019-04-22 00:59
It entirely depends on what you're doing. If you need to store new data, you need a SQL migration, if you need API endpoints, you need to create them, etc. etc.

Sorry I can't be of more help. Adding custom features to Gophish for your own use is outside of the support we provide here, so at this point I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2019-04-22 00:59 UTC
Labels: support
