### ISSUE TITLE
Office 365: Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [MN2PR13CA0005.namprd13.prod.outlook.com]

### ISSUE THREAD

**Issue by ajaychan** [gophish/gophish#1839] opened 2020-05-17 03:20 UTC
What version of Gophish are you using?:  0.9.0

Brief description of the issue: Unable to send email via Office 365 SMTP

What are you expecting to see happen? :

Test email sent

What are you seeing happen?

time="2020-05-17T03:11:07Z" level=warning msg="Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [MN2PR13CA0005.namprd13.prod.outlook.com]"
time="2020-05-17T03:11:07Z" level=error msg="Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [MN2PR13CA0005.namprd13.prod.outlook.com]"
time="2020-05-17T03:11:07Z" level=info msg="172.69.63.156 - - [17/May/2020:03:09:25 +0000] \"POST /api/util/send_test_email HTTP/1.1\" 500 169 \"https://phishing.stratuscyber.com/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\""

![2020-05-16_23-17-52](https://user-images.githubusercontent.com/17014481/82134974-af189300-97cb-11ea-9bbd-5a3298ccb2f4.jpg)

**Comment by jordan-wright** [comment] 2020-05-17 15:16
Hi there!

Thanks for getting in touch.

This appears to be a duplicate of #1822. Let’s track things there to figure out why O365 authentication isn’t working.

**Closed by jordan-wright** 2020-05-17 15:16 UTC
