### ISSUE TITLE
User status is not correct in Campaign detail 

### ISSUE THREAD

**Issue by dckidd452** [gophish/gophish#161] opened 2016-02-17 08:51 UTC
Hi,

I think the status that should be "success",because link have been clicked.
![image](https://cloud.githubusercontent.com/assets/12841587/13104212/b5179ca2-d596-11e5-8f8e-58586a2ea89a.png)

**Comment by jordan-wright** [comment] 2016-02-17 14:15
Are you using the precompiled binary? I believe this has been fixed in the master branch, so building from source should fix this for you.

**Comment by jordan-wright** [comment] 2016-02-18 02:08
Going to go ahead and close this as a duplicate of #119. If this is in fact not a duplicate, please let me know and we can investigate.

Thanks for the report!

**Closed by jordan-wright** 2016-02-18 02:08 UTC
Labels: duplicate
