### ISSUE TITLE
Issue on edit landing page

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#468] opened 2016-11-30 10:58 UTC
On edit of landing page I saw that all is bank now .. all info gone. is this issue under you knowledge?

**Comment by jordan-wright** [comment] 2016-11-30 14:15
There is no information here to help us determine the issue. What steps exactly did you take to get this result? What landing HTML did you use? Did it say the page was saved successfully? What was the console output? What button did you click to edit the page?

**Comment by dalvirsaini** [comment] 2016-12-01 12:48
today i face the same issue. I was on the site more then for 2 hours logged in and then I clicked on edit to edit the landing page and after some modification in html i clicked on save button. after this page reloaded and the title was missing from the landing page list for this page and again i clicked on edit icon and saw that now data was there fro this page like redirect url , html title

**Comment by jordan-wright** [comment] 2016-12-04 13:57
So are you still experiencing the issue? It's hard for me to follow the exact flow you're doing, but this is the first I've heard about something like this so it seems like everything should be working as intended.

If you're still encountering this issue, please provide the full steps to reproduce the issue in list format like this:

* clicked edit button for landing page "Example page"
* edited HTML
* etc.

**Comment by jordan-wright** [comment] 2016-12-17 15:54
Closing this issue as there haven't been any updates in 2 weeks. @dalvirsaini if you're still encountering issues, please provide the full steps to reproduce the issue in list format like this:

* clicked edit button for landing page "Example page"
* edited HTML
* etc.

**Closed by jordan-wright** 2016-12-17 15:54 UTC
