### ISSUE TITLE
What version of Gophish are you using?: Gophish v0.8.0

### ISSUE THREAD

**Issue by landry5** [gophish/gophish#1639] opened 2019-10-29 11:42 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish v0.8.0

Brief description of the issue: links in email templates are not directing to the landing page why?

What are you expecting to see happen? : i want the receive to open the landing page if he clicks on the links

What are you seeing happen?the links are instead opening to " welcome to Nginx " or " apache2"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment] 2019-10-29 11:57
Sounds like you have another web server running on port 80. Stop that and rerun GoPhish

Sent from my iPhone

On 29 Oct 2019, at 11:42, landry5 <notifications@github.com> wrote:

﻿

Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?:

Brief description of the issue:

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by jordan-wright** [comment] 2019-10-30 02:31
@S0larflare is spot on, this seems like a conflict where you're running a different web server on port 80. Since it seems the solution has been found, I'm going to go ahead and close this one out. Let us know if you continue to run into issues!

**Closed by jordan-wright** 2019-10-30 02:31 UTC
