### ISSUE TITLE
Improper Email Template tags when running campaigns crashes gophish docker container

### ISSUE THREAD

**Issue by pktalatham** [gophish/gophish#691] opened 2017-07-12 19:21 UTC
I was having an issue running two of my campaigns and found that if I had the tags "{{.First Name}} {{.Last Name}}" instead of "{{.FirstName}} {{.LastName}}" (including a space in the tag name) that gophish will crash with the error:

worker.go:90: template: html_template:6: function "Name" not defined
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x61a4a5]

It would be nice if GoPhish can gracefully return the error instead of breaking the container.

Thanks,
Kevin

**Comment by jordan-wright** [comment] 2017-07-14 03:13
I'm afraid we can't provide support for the Docker container since it is not provided by the core Gophish team but rather by a member of the community.

I would recommend ensuring that the Docker container is using the latest version of Gophish, since I think we changed this to provide a warning if the template is invalid in later versions.

**Comment by jordan-wright** [comment] 2017-07-18 02:31
Closing this one out since there hasn't been any updates in a few days and we don't officially support the Docker container. If anyone can reproduce this using the latest release on a non-Docker container install, let me know and I'll reopen.

**Closed by jordan-wright** 2017-07-18 02:31 UTC
