### ISSUE TITLE
SMTP Relay

### ISSUE THREAD

**Issue by bigj75025** [gophish/gophish#1797] opened 2020-03-27 16:37 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by bigj75025** [comment] 2020-03-27 16:40
Hello everyone,

I have been using Gophish for a couple of years now using Siteground as my SMTP relay. That account has recently expired since my last phishing assessment. I am currently on an engagement which allows phishing as an attack vector. Any good pointers for a free or low-cost SMTP relay that works well with the Gophish platform these days?

**Comment by vay3t** [comment] 2020-03-27 20:27
gsuite

**Comment by jordan-wright** [comment] 2020-03-28 01:09
Hi there!

We try to keep these issues focused on bug reports, feature requests and unexpected behavior with the Gophish software itself. Since this doesn't fit those categories I'm going to close this one out.

There are many low-cost email sending services. SES, Sendgrid, Mailgun, Mandrill, Mailjet, Sparkpost, you name it. Almost all of these (if not all) will allow you to send emails via SMTP directly.

**Closed by jordan-wright** 2020-03-28 01:09 UTC
