### ISSUE TITLE
Installation issue on Raspbian GNU/Linux 9

### ISSUE THREAD

**Issue by RptAlex** [gophish/gophish#1122] opened 2018-06-27 10:08 UTC
Hi!

I am trying to setup the Gophish project on a Rapsberry Pi 3 running Raspbian GNU/Linux 9 (stretch).

I followed the Official Documentation for Installation
To perform setup, I followed this step:
 * Step 1 - Installing Go Programming language 
Everything go fine.
 * Step 2 - Setup GOPATH
No trouble
 * Step 3 - Installing Gophish from Source
here comes the trouble, I run:
`$ go get github.com/gophish/gophish`

and I get the following output from the terminal:
```
# github.com/go-sql-driver/mysql
../../go-sql-driver/mysql/connection.go:485: undefined: driver.TxOptions
../../go-sql-driver/mysql/connection.go:491: undefined: sql.IsolationLevel
../../go-sql-driver/mysql/connection.go:491: undefined: sql.LevelDefault
../../go-sql-driver/mysql/connection.go:505: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:524: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:558: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:577: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:642: undefined: driver.NamedValue
../../go-sql-driver/mysql/utils.go:730: undefined: driver.NamedValue
../../go-sql-driver/mysql/utils.go:742: undefined: driver.IsolationLevel
../../go-sql-driver/mysql/connection.go:491: too many errors
# github.com/lib/pq
../../lib/pq/notify.go:787: undefined: time.Until
```
Even with this error I still tried to build it
```
pi@raspberrypi:~/go/src/github.com/gophish/gophish $ go build
# github.com/go-sql-driver/mysql
../../go-sql-driver/mysql/connection.go:485: undefined: driver.TxOptions
../../go-sql-driver/mysql/connection.go:491: undefined: sql.IsolationLevel
../../go-sql-driver/mysql/connection.go:491: undefined: sql.LevelDefault
../../go-sql-driver/mysql/connection.go:505: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:524: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:558: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:577: undefined: driver.NamedValue
../../go-sql-driver/mysql/connection.go:642: undefined: driver.NamedValue
../../go-sql-driver/mysql/utils.go:730: undefined: driver.NamedValue
../../go-sql-driver/mysql/utils.go:742: undefined: driver.IsolationLevel
../../go-sql-driver/mysql/connection.go:491: too many errors
# github.com/lib/pq
../../lib/pq/notify.go:787: undefined: time.Until
```
I can't build the executable (not a surprise with my previous error).

Any idea about how to fix this?

**Comment by jordan-wright** [comment] 2018-06-28 03:13
Hi @RptAlex, thanks for reaching out!

What version of Golang are you using (`go version`)? Note that Gophish is currently only supported with Golang 1.8 and above.

**Comment by RptAlex** [comment] 2018-06-28 06:55
Hi thanks for anwsering!
 Indeed I'm using an unsupported version....
```
$ go version
go version go1.7.4 linux/arm
```
But I installed it yesterday from the official repository... So my only option is to change my system and hardware to one that supports Golang 1.8 or above?

**Comment by jordan-wright** [comment] 2018-06-29 02:46
You don't need to change your system, you can just install Golang manually 😄 

It looks like someone created some instructions [here](https://gist.github.com/simoncos/49463a8b781d63b5fb8a3b666e566bb5) that will likely help. I recommend installing the latest stable version of Go, which I _think_ is 1.10 these days.

Hope this helps! Since we've identified the root cause, I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2018-06-29 02:46 UTC
Labels: support
