### ISSUE TITLE
PLEASE I CANNOT SEND TEST MAILS OR LAUNCH CAMPAIGN. 

### ISSUE THREAD

**Issue by playjett** [gophish/gophish#1286] opened 2018-11-19 15:43 UTC
i have gophish 7.1,my problem with it is that is not sending test mail neither do the campaigns emails go through. Please recommend to me some smtp severs beside gmail and common ones. attached file is a screen shot of what i see when i tried to send test mails.
![gophish file](https://user-images.githubusercontent.com/37704143/48717517-6f6ced00-ebce-11e8-9bc4-c5bff4e72544.PNG)

**Comment by securitygeneration** [comment] 2018-11-20 13:44
It looks like you're trying to use Google's SMTP server... I don't think that's going to work. You need to set up your own SMTP relay server. You might want to Google how to do that.

**Comment by jordan-wright** [comment] 2018-11-21 01:13
Hi @playjett,

This appears to be a duplicate of #1269 and #1260. As @securitygeneration mentioned, Gmail likely isn't the best SMTP server. Instead, we encourage you to use your own organizations mail server to send emails.

If you are insisting to use Gmail, we recommend following the steps at the URL provided in the error message, trying all options to see if they help resolve the issue.

**Closed by jordan-wright** 2018-11-21 01:13 UTC

**Comment by playjett** [comment] 2018-11-21 02:07
please after i have set the mailserver what then do i fill into these spaces 1. HOST 2. {{URL}  3. URL (http://192.168.1.1)

**Comment by jordan-wright** [comment] 2018-11-21 03:15
It's still not clear what you're trying to do and what you've tried. It sounds like you're trying to set up your sending profile and you can find more information about that [in our documentation](https://docs.getgophish.com/user-guide/documentation/sending-profiles).

Without more information, I'm afraid there isn't anything else we can do to help.

**Comment by playjett** [comment] 2018-11-21 03:36
please am using hmailserver to setup my relay to use when preparing sending profile in gophish.
what will i fill into these three spaces 
SENDING PROFILE
 1. HOST 2. {{URL}
 3. (on the campaign) URL (http://192.168.1.1)
PLEASE TELL ME DETAILS TO PUT THERE FROM hmailserver?

**Comment by playjett** [comment] 2018-11-21 03:43
please am using hmailserver to setup my relay to use when preparing sending profile in gophish.
what will i fill into these three spaces
SENDING PROFILE

HOST 2. {{URL}
(on the campaign) URL (http://192.168.1.1)
PLEASE TELL ME DETAILS TO PUT THERE FROM hmailserver?
![capture2](https://user-images.githubusercontent.com/37704143/48817688-78f47300-ecfc-11e8-9768-2b545f9c583c.PNG)
![capture3](https://user-images.githubusercontent.com/37704143/48817689-798d0980-ecfc-11e8-805a-8e0e2dbeb59f.PNG)
