### ISSUE TITLE
gophish login error 

### ISSUE THREAD

**Issue by tzw2024** [gophish/gophish#3221] opened 2024-08-14 12:34 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Milo1191** [comment] 2024-08-15 19:57
I'm not part of the owner of this project, but when you start to run the program at the start of the logs, you will see a password that is generated. Use that then it will ask you to set a new password up. Image below from where I found mine. 

![image](https://github.com/user-attachments/assets/c783b354-bf6d-425b-8fef-0463e80eb27e)

**Comment by jordan-wright** [comment] 2024-08-17 01:34
Closing as a duplicate of https://github.com/gophish/gophish/issues/3222.

Thank you for providing support here @Milo1191!

**Closed by jordan-wright** 2024-08-17 01:34 UTC

**Comment by gideonmarcus** [comment] 2024-09-21 22:33
> I'm not the owner of this project, but when you run the program, you'll see a password generated at the beginning of the logs. Use that password, and then you will be prompted to set up a new one. The image below shows where I found mine
> 
> ![image](https://private-user-images.githubusercontent.com/152124933/358371748-4c55d0a8-0731-4cba-8be0-b98074048c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTgyOTEsIm5iZiI6MTcyNjk1Nzk5MSwicGF0aCI6Ii8xNTIxMjQ5MzMvMzU4MzcxNzQ4LTRjNTVkMGE4LTA3MzEtNGNiYS04YmUwLWI5ODA3NDA0OGMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQyMjMzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWExMWRiYjJkYzJjOTgxY2Y1MjBjZDIwMmY2YjkzMTRiNDIyYjUyYjQyYzcwYTgwYjZmY2ExN2YyZjM5M2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.umZbd7XRqoLP8X2dRP60bPvO4L2qaowsH7vq3gvcCds)

even if i type that password it shows invalid
