### ISSUE TITLE
"record not found" on startup after upgrade

### ISSUE THREAD

**Issue by REBELinBLUE** [gophish/gophish#1895] opened 2020-07-13 21:29 UTC
Previously using 0.8.0 and I switched my deployment to use the `gophish/gophish:latest` image and on startup I just get

```
time="2020-07-13T21:19:59Z" level=warning msg="No contact address has been configured."
time="2020-07-13T21:19:59Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200619000000
time="2020-07-13T21:20:00Z" level=error msg="record not found"
time="2020-07-13T21:20:00Z" level=fatal msg="record not found"
```

I switched logging to debug and don't get any additional information, any idea how I can find out what record is not found?

The migrations table looks like this so it seems to have migrated fine.

<img width="683" alt="Screen Shot 2020-07-13 at 22 27 50" src="https://user-images.githubusercontent.com/2143908/87355360-2a8e8a80-c558-11ea-8427-eebacbcaaec1.png">

**Comment by jordan-wright** [comment] 2020-07-17 03:58
Hey there!

I'm afraid that thanks to my lack of adding informational logging (whoops!) it's not clear what's going on here.

It might be tedious, but you might try other versions to see where exactly things break. Beyond that, any information you have about your database (what users you have, how many campaigns, etc) might help track things down.

Sorry for the trouble!

**Comment by REBELinBLUE** [comment] 2020-07-27 20:32
Apologises for the late reply, I shall have a play around at work tomorrow, may take some time though as the only docker images you've published are `0.9.0` and `latest` so I'd have to build images for different versions

**Comment by bauxi** [comment] 2020-09-07 10:23
Same issue here. I upgraded from version 0.10.1. Here is my debug log during startup:

```
time="2020-09-07T12:22:36+02:00" level=warning msg="No contact address has been configured."
time="2020-09-07T12:22:36+02:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 20200116000000, target: 20200730000000
OK    20200619000000_0.11.0_password_policy.sql
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql
time="2020-09-07T12:22:36+02:00" level=error msg="record not found"
time="2020-09-07T12:22:36+02:00" level=fatal msg="record not found"
```

The same database works with the previous gophish version.

**Comment by bauxi** [comment] 2020-09-09 15:21
I figured it out. The update failed because I renamed my admin account to something else than "admin". So this could probably affect a small amount of people.

**Comment by REBELinBLUE** [comment] 2020-09-09 21:33
Oh, I shall take a look at that on our install, I never got round to trying but I am almost certain that they changed the account name

**Comment by glennzw** [comment] 2021-03-07 11:23
Closing as duplicate of https://github.com/gophish/gophish/issues/1963

**Closed by glennzw** 2021-03-07 11:23 UTC

**Comment by bbrendon** [comment] 2021-06-21 21:55
ahhH! I deleted the default admin account. that might be my issue!

**Comment by gaidis18** [comment] 2021-12-20 15:00
Hey! I had the same problem today, and the problem is really related to changing the name or deleting the admin user.

In my case, I had changed the name.

To adjust, i used SQLite Studio, and opened the gophish.db file, after that I opened the 'users' field, and selected the 'data' view. So I changed the username from role admin to 'admin' again, and committed it.

**Comment by Netron27** [comment] 2022-05-17 12:02
Hello @gaidis18 
I have the same problem
I had changed the gophish admin several months ago.
And yesterday when I changed the conf file to change the ip, I can't launch gophish anymore. I tried to follow your procedure but I can't; can you please tell me more?

Netron27

**Comment by Netron27** [comment] 2022-05-17 14:23
When I make a modification in the database, I get this error message when I run gophish : 
time="2022-05-17T13:54:09Z" level=fatal msg="database disk image is malformed"
