### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by imal987** [gophish/gophish#859] opened 2017-11-28 11:39 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: I'd like to ask if there is a way to send automatic emails to the targets after they clicked the link to the landing page, it means when the targets receive the email and they click the link it will leads to the landing page and also an automatic email will be sent to the targets, is that second feature possible?  

What are you expecting to see happen? : d

What are you seeing happen? d

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by imal987** [comment] 2017-11-28 11:39
I'd like to ask if there is a way to send automatic emails to the targets after they clicked the link to the landing page, it means when the targets receive the email and they click the link it will leads to the landing page and also an automatic email will be sent to the targets, is that second feature possible?

**Comment by jordan-wright** [comment] 2017-11-30 14:45
Closing this out, since it's a duplicate of #863

**Closed by jordan-wright** 2017-11-30 14:45 UTC
