### ISSUE TITLE
Feature Request - Campaings

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#758] opened 2017-09-19 15:01 UTC
When conducting campaigns, I don't always send just one email, or all emails at once, or to all users at the same time.  It can be mixed.  Some users may get one email at one time while another group receives a different email at a different time.  They are all the same "campaign", so it would be nice to be able to have them grouped together.

**Comment by jordan-wright** [comment] 2017-09-20 01:45
Thanks for getting in touch!

This is pretty well covered by other issues. For example, sending emails at different times is covered by #611.

I'm afraid we won't be implementing the ability to send different emails to different users in a single campaign. The design of Gophish is heavily tied to the idea that all users see the same emails, the same landing pages, etc. You can use the API if you want to do more complex things and break up campaigns like what you're referring to.

Hope this helps! I'll go ahead and close this out as a duplicate of #611 for now. Thanks again for getting in touch!

**Closed by jordan-wright** 2017-09-20 01:45 UTC
