### ISSUE TITLE
GoPhish campaign problem - only shows email sent

### ISSUE THREAD

**Issue by smiller199** [gophish/gophish#1107] opened 2018-06-09 13:10 UTC
Good day,

i've setup a test campaign and sent out the email. The recipient receives the email and the dashboard shows that the email was sent. When the recipient opens or clicks on the email it does not report back to the dashboard.

I've setup gophish on my windows 7 workstation and using test gmail accounts.
The goal is to run this simulation in the organisation but not getting this to work on test machine so concerned at this stage.

Hope to receive some guidance to what i'm doing wrong.

Thanks in advance.

**Comment by jordan-wright** [comment] 2018-06-09 15:34
Hi there!

Thanks for reaching out. What are you using for the URL field when building a campaign? It should point to you Gophish server external IP, or a domain that resolves to that IP.

Also, can you show an example of the template that was used?

Finally, what do you see when you click the link in the email? Do you see the expected page? Do you see a log in the terminal running Gophish indicating that a connection was made?

**Comment by smiller199** [comment] 2018-06-09 19:57
Hi,

Thanks for your response.
Let me start by saying i'm completely new to this and have limited technical experience doing this kind of thing. 
i think my problem is don't have an external ip address or domain name.  is this what must be typed in the url field?

i wanted to test this first in my personal capacity first.  Is it possible to do it affordably\free for a domain external ip?

for the landing page i've imported the office365 login page.
sending account is a gmail account.

i go to the portal link when i click it.
should something else be filled in here?

this is my test email.
"Good Day
Your domain Microsoft office 365 work account has been disabled.
To reactivate go to https://portal.office.com

Thank you for suppoorting Microsoftt

Sincerely
The Microsofft Office 365 Team"

any other suggestions are welcome.

thanks

**Comment by smiller199** [comment] 2018-06-18 18:41
Hi Jordan,

thanks for your response. the free tools are very limited in the number of users. I now have an external ip address and would like to get this working. I've opened the ports on my firewall but still no results return. 
any other pointers for config file or anything else that will allow this to work.

**Comment by jordan-wright** [comment] 2018-06-19 00:18
Hi @smiller199,

I'm afraid we're going to need quite a bit more information in order to figure out what the issue is at this point.

What does the user see when they click the link in the email? What does that link look like? What do you see when in the Gophish terminal when the user clicks the link?

Note that you'll also likely encounter issues using the imported office 365 landing page, since I've heard from other folks that it tends to send information via Javascript instead of using a traditional form.

And also know that while those free tools I mentioned may limit the number of users per campaign, they shouldn't limit the number of campaigns you can run. I can only speak from experience for Duo Insight, but I know you can run as many campaigns as you'd like with that tool if that helps.

**Comment by jordan-wright** [comment] 2018-07-21 20:08
Going ahead and closing this out since there hasn't been any updates in a while.

@smiller199 if you're still running into issues, take a look at the comment above and we can re-open once we have that information.

Thanks!

**Closed by jordan-wright** 2018-07-21 20:08 UTC
Labels: support

**Comment by ayush1407** [comment] 2020-04-30 17:44
Hi @jordan-wright Jordan,

I am also facing kind of same problem.
I hosted GoPhish in one of the public facing server and accessing through a public IP.
I am even able to send mails but when user clicks on link it brings them to login page of gophish.
How can this problem be solved?
Any reply would be highly appreciated
