### ISSUE TITLE
I would like to create a campaign to external listeners but I don't know my external IP ADDRESS

### ISSUE THREAD

**Issue by UCSG123** [gophish/gophish#2127] opened 2021-02-19 18:43 UTC
Hello, I would like to point my external IP address to my gophish server. I have a domain but I pointed to 127.0.0.1 or 192.168.1.11 and It only works in my computer but it doesn't it other computers. Please help me with this. Thank you

**Comment by jordan-wright** [comment] 2021-02-20 13:40
duplicate of #2125

**Closed by jordan-wright** 2021-02-20 13:40 UTC
