### ISSUE TITLE
New feature: track users who open an attachment

### ISSUE THREAD

**Issue by jrmarques666** [gophish/gophish#1606] opened 2019-09-26 09:45 UTC
A great new feature would be an option to attach some file that when opened in a windows machine it connects to gophish and the action is recorded associated to the recipient id. Obviously this attachment must be customised for each recipient. Maybe we can use a Macro in a Word document. If so, we could also allow customisation of the text so to avoid suspicion.

**Comment by jrmarques666** [comment] 2019-09-26 09:47
I see this is a duplicate of https://github.com/gophish/gophish/issues/227. Sorry about that.

**Comment by glennzw** [comment] 2019-09-26 10:47
I too hadn't noticed that thread, and added my $0.02 to it.

**Comment by jordan-wright** [comment] 2019-09-27 02:02
Thanks for sending this in! This is indeed a duplicate of #227. Let's revisit that one soon and see if we can't build something into Gophish in line with @glennzw's suggestions.

**Closed by jordan-wright** 2019-09-27 02:02 UTC
