### ISSUE TITLE
URL Target ID doesn't correspond to GoPhish Target's ID (404)

### ISSUE THREAD

**Issue by stormfleet** [gophish/gophish#1828] opened 2020-05-01 12:38 UTC
What version of Gophish are you using?: 
0.9.0

Brief description of the issue: 
Sent out a phishing campaign to a group of 400 users. Of those 400 users, some of the target RIDs received in the emails did not correspond to Gophish's results RID's, and as a result the web page in the email received resulted in a 404.

What are you expecting to see happen? :
I've used Gophish before, I understand that if I send an email to an individual as part of a campaign, if the RID generated by Gophish (and stored in Gophish's results spreadsheets) is the same as the one sent, so that the link to the landing page contains the same RID as the one exported from Gophish to allow it to track submissions.

What are you seeing happen?
The RID stored by Gophish and the RID supplied in the Email from the {{.URL}} parameters are different.

Example:
Sent a phishing email to: john.doe@aaa.com.
Received email link was: www.aaa.com/?rid=T4goGZ5 - clicking on this link results in a 404 not found.
Exporting results from the campaign containing john.doe@aaa.com, the ID displayed in the sheet was: RkyZzy0

**Comment by jordan-wright** [comment] 2020-05-04 02:32
Hi there!

Thanks for reaching out! This is definitely not expected behavior, and the first I've heard of this happening.

Could you give a bit more information about the setup here? You're correct that every recipient in a campaign is allocated a unique rid value which is used for tracking results, loading pages, and more.

Have you encountered this before or is this something that just started happening? Could you please provide the relevant parts of your email template so that I can take a look at what that looks like?

Additionally, was this a campaign you started on demand or did you schedule it to launch later?

Sorry for all the follow up questions- this is just unexpected so I want to make sure we can get to the bottom of it. In the meantime, I'll try to reproduce this on my end to see if I can figure out what's going on.

**Comment by stormfleet** [comment] 2020-05-06 10:38
No worries I totally get it.

Campaign timing was thrown off because my server hadn't pulled from NTP recently (daylight timesavings amirite), so the campaign was last minute launched on demand. Campaign size for the batch with the peculiar behaviour was around 820, using Exim4 as the mail server without any configuration changes (version 4.90.1-1ubuntu1.4). This was my fault, and resulted in a backlog that caused the emails to leave over the course of an hour. I suspect this might have something to do with it.

Email template containing the URL string was as follows:
`<div class="button-container" style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;" align="center">
<a href="{{.URL}}" style="-webkit-text-size-adjust: none; text-decoration: none; display: inline-block; color: #ffffff; background-color: #3AAEE0; border-radius: 4px; -webkit-border-radius: 4px; -moz-border-radius: 4px; width: auto; width: auto; border-top: 1px solid #3AAEE0; border-right: 1px solid #3AAEE0; border-bottom: 1px solid #3AAEE0; border-left: 1px solid #3AAEE0; padding-top: 5px; padding-bottom: 5px; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; text-align: center; mso-border-alt: none; word-break: keep-all;" target="_blank"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;">Sign Me Up!</span></span></a>

</div>`

**Comment by glennzw** [comment] 2020-06-08 11:11
N.B If you end a campaign all links will 404. Perhaps this was the case here?

**Comment by stormfleet** [comment] 2020-06-08 11:20
No it was definitely still active @glennzw . Just that the exported events and results from Gophish, the RID was different to the one received by the recipient.

**Comment by s-bt** [comment] 2020-07-15 14:22
Same here. The URL in the mail always adds the value '3D' in front of the actual RID. So if the RID is xcYfanH the url is for example http://10.0.0.2/?rid=3DxcYfanH.
I have tested with Linux as well as Windows with the current version 0.10.1

**Comment by glennzw** [comment] 2021-06-20 21:47
The '3D' is quoted printable format; your email client should render that out.

This is a bit old now so I'm closing it out, but feel free to reopen if it's still a problem.

**Closed by glennzw** 2021-06-20 21:47 UTC
