### ISSUE TITLE
Locally hosted images for email/landing site templates

### ISSUE THREAD

**Issue by mcjon3z** [gophish/gophish#220] opened 2016-03-23 17:40 UTC
I may be missing something here, but is there a way to facilitate a locally hosted image on the gophish server to be imbedded into an email or landing site template?

On the email, I tried uploading an image as an attachment to the email and then placing a link in the email to the file name (no relative path) however the image was not displayed in the preview.

**Comment by mcjon3z** [comment] 2016-03-23 17:51
As an update, I did figure out that you can open an image in image editor and then paste the image into the HTML editor and found that it will imbed it as a base64 encoded string so that could be a workable alternative means in certain situations, at least for me...

**Comment by jordan-wright** [comment] 2016-03-23 17:54
Hey @mcjon3z - thanks for the report!

You are able to host local resources that can be accessed via links. We're still working on the documentation for everything, but you can see some "running notes" in #164. 

Eventually, you will be able to put resources under "/static/endpoint/*" and have them served off x.x.x.x:80/static/ to the user, but I have a couple of fixes to make to let that happen.

Good to know about how CKEditor embeds images! Thanks for the heads up!

**Comment by mcjon3z** [comment] 2016-03-23 18:01
I currently use Phishing Frenzy for my campaigns and use the capability to attach images to sites/emails as a means of creating files which are not dependent upon any external resources - you can use them indefinitely without worrying about referencing an external site that changes or goes down. I realize this may be difficult to implement in GoPhish because of the way all of the site and email code is stored in the DB and dynamically served.

I'm going to play with some python scripts to take an html site/file/email and convert all of the images into Base64 imbedded images just to see how it works out. For my personal workflow, that works better than external references. If I get something working, I'll be sure to share. Different language, but maybe there will be something useful there that you want to try to incorporate into your own code.

Biggest hurdle will be to see how different browsers handle a large page with lots of imbedded images.

**Comment by jordan-wright** [comment] 2016-03-23 18:05
Interesting - could you elaborate a bit more on your use case?

Specifically, when you say:

> I currently use Phishing Frenzy for my campaigns and use the capability to attach images to sites/emails as a means of creating files which are not dependent upon any external resources - you can use them indefinitely without worrying about referencing an external site that changes or goes down.

How does Phishing Frenzy accomplish this? Does it base64 encode everything before attaching the resource to the site/email? To my knowledge, that'd be the only way to support images in things like html pages without linking to them where they are hosted elsewhere..

I'm always interested in finding ways that gophish can be more flexible for as many use cases as possible, so please keep me updated!

**Comment by jordan-wright** [comment] 2016-03-23 19:13
@mcjon3z  - Just a heads up, I fixed the static file hosting in #164 as of 49b0646. Hopefully that makes it at least a little easier :smile:

**Comment by mcjon3z** [comment] 2016-03-23 20:16
Sure. PF takes a different approach. Each template had a number of files which are attached. These can be html, php, images, etc. When a campaign is launched all of the files are copied into a temp directory and the Apache configuration file is modified to point a specific vhost to that directory. This allows you to locally host the images and reference them since they get copied into the vhost directory too.

Definitely not as elegant or dynamic as the go phish approach but it does address the limitation of having to host images elsewhere. I have gotten burned several times in engagements using links that point to external sites. Even git reported to my ISP for hosting a fraudulent site once and they tried to shute down.

The base64 option may work great. Just need to test it a bit and see if there are any gotchas with file sizes and browser compatibility.

Kudos to this project. I can see this becoming a valuable tool for myself and many others. I particularly like having templates for emails, landing pages,  and senders segregated. This would allow a lot of flexibility being able to use a scheme in multiple ways without having to constantly modify your template. Want to have a LinkedIn scheme that can harvest creds or pop up a malicious java applet? Just copy the landing page and tweak it once and you have either option at a click.



Sent from my Verizon Wireless 4G LTE smartphone

________________________________

*****Internet Email Confidentiality Disclaimer*****

This communication and any accompanying documents are confidential and privileged. They are intended for the sole use of the addressee. If you receive this transmission in error, you are advised that any disclosure, copying, distribution, or the taking of any action in reliance upon this communication is strictly prohibited. Moreover, any such disclosure shall not compromise or waive the attorney-client, accountant-client, or other privileges as to this communication or otherwise. If you have received this message in error, you should destroy this message and kindly notify the sender by reply email.

Please advise immediately if you or your employer do not consent to internet email messages. Opinions, conclusions and other information in this message that do not relate to the official business of our firm shall be understood as neither given nor endorsed by it.

McGladrey Alliance is a premier affiliation of independent accounting and consulting firms. McGladrey Alliance provides its members with access to resources of RSM US LLP (formerly known as McGladrey LLP). McGladrey Alliance member firms are separate and independent businesses and legal entities that are responsible for their own acts and omissions, and each are separate and independent from RSM US LLP. RSM US LLP is the U.S. member firm of RSM International, a global network of independent audit, tax, and consulting firms. Visit rsmus.com/aboutus for more information regarding RSM US LLP and RSM International. McGladrey®, the McGladrey Alliance logo and the McGladrey Alliance signatures are proprietary to RSM US LLP, while RSM™ is used under license by RSM US LLP.

**Comment by jordan-wright** [comment] 2016-03-24 03:10
So I think you and I are pretty close to being on the same page.

Specifically:

> When a campaign is launched all of the files are copied into a temp directory and the Apache configuration file is modified to point a specific vhost to that directory. This allows you to locally host the images and reference them since they get copied into the vhost directory too.

In this case, it sounds like you would still need to reference the images, etc. by links to your local instance (the phishing server). This is absolutely possible with gophish! That's also what #164 what about.

Any resources copied into the ```static/endpoint/``` directory can be referenced in email templates and landing pages by linking to ```http://x.x.x.x/static/image.png````, where ```x.x.x.x``` is the ip of your gophish instance and ```image.png``` is the resource. You can then reuse the images, etc. across landing pages and templates.

This shouldn't give any issues since clients **have** to be able to reach your phishing server anyway for you to measure results (tracking, etc.).

**Comment by jordan-wright** [comment] 2016-03-24 03:20
Here is a gif showing this in action:

![temp](https://cloud.githubusercontent.com/assets/1317288/14007501/5c47b254-f145-11e5-87ee-5b0d5aa783cb.gif)

**Comment by mcjon3z** [comment] 2016-03-24 17:24
Yep, that looks like it would work for what I'm talking about. I will keep you posted on the base64 option once I have had some time to test. Thanks for the responses!

________________________________

*****Internet Email Confidentiality Disclaimer*****

This communication and any accompanying documents are confidential and privileged. They are intended for the sole use of the addressee. If you receive this transmission in error, you are advised that any disclosure, copying, distribution, or the taking of any action in reliance upon this communication is strictly prohibited. Moreover, any such disclosure shall not compromise or waive the attorney-client, accountant-client, or other privileges as to this communication or otherwise. If you have received this message in error, you should destroy this message and kindly notify the sender by reply email.

Please advise immediately if you or your employer do not consent to internet email messages. Opinions, conclusions and other information in this message that do not relate to the official business of our firm shall be understood as neither given nor endorsed by it.

McGladrey Alliance is a premier affiliation of independent accounting and consulting firms. McGladrey Alliance provides its members with access to resources of RSM US LLP (formerly known as McGladrey LLP). McGladrey Alliance member firms are separate and independent businesses and legal entities that are responsible for their own acts and omissions, and each are separate and independent from RSM US LLP. RSM US LLP is the U.S. member firm of RSM International, a global network of independent audit, tax, and consulting firms. Visit rsmus.com/aboutus for more information regarding RSM US LLP and RSM International. McGladrey®, the McGladrey Alliance logo and the McGladrey Alliance signatures are proprietary to RSM US LLP, while RSM™ is used under license by RSM US LLP.

**Comment by jordan-wright** [comment] 2016-03-25 21:59
Good deal. I'm going to go ahead and close this out for now, but let me know if you run into any issues!

**Closed by jordan-wright** 2016-03-25 21:59 UTC
Labels: support

**Comment by Wh1teHat65** [comment] 2017-08-05 16:02
In order to preserve the campaign and not hovered over stand out, is it possible to substitute the variable {{.URL}} as the path to the server so that the selected phishing domain is provided instead of an IP address?

(e.g.  http://{{.URL}}/static/{campaign_specific_subfolder}/logo.png )

**Comment by jordan-wright** [comment] 2017-08-05 17:37
Hey there!

The URL template tag simply puts in whatever you use as the "URL" field when making the campaign. If in that field you put a domain that resolves to the Gophish server, that will work.

You can also host static assets on the server. You'll find documentation on how to do that here https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html

**Comment by dsmurf** [comment] 2018-06-19 11:35
Hi Jordan
I can't get this to work.
then i do http://site/statis/endpoint/logo.png i get a 404 page.
same if i make a .html.

**Comment by Wh1teHat65** [comment] 2018-06-19 13:03
@dsmurf:  First, GoPhish is an amazing tool and we use it every week. I believe its superior in every way to all the other commercial and open-source tools we tried.  With that said, the hosting of additional content on the server has never worked for us either ¯\_(ツ)_/¯.  

No worries, there is a simple fix.  Use a 3rd party to host those items (banners, logos, and other pre-text deliverables).  In many cases, you can find the images and logos you want already in Google Images; why host them when you can just point to them?  In either case, it allows you to get that consist look and feel you need in your pre-text and campaign delivery.  If you are going to manage hosting it yourself, there are a number of free or low-cost hosting sites on the internet:  https://hosting.review/web-hosting/free-website-hosting/  

Finally, one cautionary note I would offer is, make sure you do not host anything that might be scanned or classified as malicious on the same site as where you host your images and other non-malicious content.  Otherwise, that url could be flagged by proxies and blocked.  -- Hope this helps.

**Comment by jordan-wright** [comment] 2018-06-19 14:11
Hi @dsmurf,

So you'll want to put the image under the `static/endpoint` directory in your folder structure. So, my Gophish folder may look something like this:

```
/
    static/
        endpoint/
            logo.png
```

Then, to actually reference it in the phishing server, you would do `http://site/static/logo.png` (note that we don't include "endpoint" here).

Hope this helps!

**Comment by dsmurf** [comment] 2018-06-26 07:31
@Wh1teHat65 It sort of helps. I would wrather i could refer to the items and pictures on my gophish.
I must agree with you though, gophish is a awsome tool. It is still missing a few features.

**Comment by dsmurf** [comment] 2018-06-26 07:32
@jordan-wright i did that, it does not work.

**Comment by Joshua-Bornman** [comment] 2018-07-05 06:52
@jordan-wright I also seem to be having this issue now. I tried to just put the url (`http://ipaddress/static/Phishing-screenshot.png`) in a browser and it doesn't find the file. It is saved in `username@host:/static/endpoint`

**Comment by justaskingquestions** [comment] 2018-07-10 13:34
I also found that while campaign URLs may have a sub-folder like `http://myip/foocampaign`, it would seem that you cannot include static resources into such campaigns by referencing them using like  `./static/email.png`.

Directory structure in /opt/gophish/static/endpoint:
```
root@mail:/opt/gophish/static/endpoint# ls -lR
.:
total 208
drwxr-xr-x 2 gophish gophish   4096 Jul 10 12:46 css
-rw-r--r-- 1 gophish gophish   1088 Jul 10 13:08 default.css
-rw-r--r-- 1 gophish gophish  10781 Jul 10 13:08 email.png
drwxr-xr-x 2 gophish gophish   4096 Jul 10 12:46 images
-rw-r--r-- 1 gophish gophish  10358 Jul 10 13:08 logo.png
-rw-r--r-- 1 gophish gophish 175710 Jul 10 13:08 phishing.jpg

./css:
total 4
-rw-r--r-- 1 gophish gophish 1088 Jul 10 12:46 default.css

./images:
total 196
-rw-r--r-- 1 gophish gophish  10781 Jul 10 12:46 email.png
-rw-r--r-- 1 gophish gophish  10358 Jul 10 12:46 logo.png
-rw-r--r-- 1 gophish gophish 175710 Jul 10 12:46 phishing.jpg
```
I tried both storing the resources directly in /opt/gophish/static/endpiont and also tried moving them to sub-directories (cleaner IMO). Both to now avail.

See the log output below:
```
Jul 10 13:09:01 mail gophish[836]: 127.0.0.1 - - [10/Jul/2018:13:09:01 +0000] "GET /foocampaign/?rid=xPeTcxL HTTP/1.0" 200 1327 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jul 10 13:09:01 mail gophish[836]: 127.0.0.1 - - [10/Jul/2018:13:09:01 +0000] "GET /foocampaign/static/default.css HTTP/1.0" 404 19 "http://foodomain.tldfoocampaign/?rid=xPeTcxL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jul 10 13:09:01 mail gophish[836]: 127.0.0.1 - - [10/Jul/2018:13:09:01 +0000] "GET /foocampaign/static/logo.png HTTP/1.0" 404 19 "http://foodomain.tldfoocampaign/?rid=xPeTcxL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jul 10 13:09:01 mail gophish[836]: 127.0.0.1 - - [10/Jul/2018:13:09:01 +0000] "GET /foocampaign/static/phishing.jpg HTTP/1.0" 404 19 "http://foodomain.tldfoocampaign/?rid=xPeTcxL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jul 10 13:09:01 mail gophish[836]: 127.0.0.1 - - [10/Jul/2018:13:09:01 +0000] "GET /foocampaign/static/email.png HTTP/1.0" 404 19 "http://foodomain.tldfoocampaign/?rid=xPeTcxL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```
As you can see, the campaign tracking link works fine while the resources result in a 404

**Comment by Joshua-Bornman** [comment] 2018-07-11 07:30
I managed to figure out my issue. Turns out I was trying to save it in the server's static folder and not the static folder in gophish

**Comment by hatermind** [comment] 2019-02-01 10:59
Hi,

I have created some files under `gophish-0.7.1/static/endpoint/` path

`ubuntu:~$ cat gophish-0.7.1/static/endpoint/asd`
`sample text`


But i have found out that i can only access to them through the admin_server instance (`https://localhost:3333/endpoint/asd`). So i cant get the files using the phish_server (`http://localhost/endpoint/asd`)

I have been reading this post and others related to this one, and as i understood this is not the expected behaviour. As i understand the files should be available from the instance the users will be accessing to, am i right? They shouldnt have access to the admin instance.

Guess i am doing something wrong, hope you can help me ;)

**Comment by adrigondite7** [comment] 2019-04-04 07:50
¿Puedes documentar esto en la guía Gophish?

"Activos estáticos 
Es posible que haya ocasiones en las que desee almacenar activos como páginas HTML, recursos CSS / JS u otros archivos estáticos. Para usarlos en Gophish, simplemente muévalos bajo el directorio estático / punto final. A continuación, puede consultarlos utilizando el URL http [s]: // phishing_server / static / filename. Para obtener más información, consulte este problema ".

**Comment by adrigondite7** [comment] 2019-04-08 11:09
Can you document this in the Gophish guide?

"Static assets
There may be times when you want to store assets such as HTML pages, CSS / JS resources or other static files. To use them in Gophish, simply move them under the static / endpoint directory. You can then consult them using the URL http [s]: // phishing_server / static / filename. For more information, see this problem. "

**Comment by brimade-ugp** [comment] 2025-02-06 10:14
hello, so i'm intern for few weeks and i made a gophish campaign.
It was really hard to make our statics images working. Also we couldn't instantiate them as you did, in fact we had to put them in static, no other subfiles and refer them as "<img src=logo.png>" in the html without addresses or files.

If someone is getting same try this maybe it will help
