### ISSUE TITLE
Unable to bulk import via CSV.

### ISSUE THREAD

**Issue by HanSolo71** [gophish/gophish#1388] opened 2019-03-08 17:18 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.71

Brief description of the issue: Unable to import users from CSV

What are you expecting to see happen? : Users be imported from CSV

What are you seeing happen? Nothing, I upload the test CSV with these contents from IE, Chrome, and Firefox and nothing happens.

First Name,Last Name,Position,Email
Richard,Bourne,CEO,rbourne@morningcatch.ph
Boyd,Jenius,Systems Administrator,bjenius@morningcatch.ph
Haiti,Moreo,Sales & Marketing,hmoreo@morningcatch.ph

Thinking it was an issue with my formatting I tried creating this in both Notepad++ and Excel 2016, both have the same issue. I have ensured encoding is UTF-8.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create CSV from data
 * Step 2 - Upload CSV using bulk upload
 * Step 3 - Nothing happens

**Comment by jordan-wright** [comment] 2019-03-10 20:50
Do you have the same experience when using Chrome?

**Comment by HanSolo71** [comment] 2019-03-10 20:55
Yes, tested in Chrome, Edge, and Firefox.

**Comment by S0larflare** [comment] 2019-03-19 09:41
Does the console show anything when you try to upload it? Also, if you switch the Email and Position columns around (so position is last), does it work then?

**Comment by HanSolo71** [comment] 2019-03-26 14:27
Nothing is shown and moving the columns changes nothing.

**Comment by jordan-wright** [comment] 2019-03-27 01:36
Hi @HanSolo71,

Could you please attach the CSV you're uploading? You should be able to drag/drop it into a comment to upload it. Having the raw file will help us out with testing.

Thanks in advance!

**Comment by McFly2229** [comment] 2019-04-19 06:33
Having run into this very problem as well, I would like to share my experiences with you.

For me, the reason the CSV file not being imported was that it was lacking the headline including column headers. With this file, the behaviour was exactly as described by HanSolo71: absolutely no feedback on the UI while network monitor shows an empty JSON string array returned as response to the POST request.
Having added the CSV column headers, the import worked just fine.

So for me the issue is rather a lack of error handling (and user guidance) than a technical issue per se.

**Comment by jordan-wright** [comment] 2020-08-08 20:23
Closing this since there haven't been any updates in months. I appreciate you sharing your experience @McFly2229. I'll see if I can make some tweaks to show an error message if the expected column headers aren't found.

**Closed by jordan-wright** 2020-08-08 20:23 UTC

**Comment by Dretreyt** [comment] 2024-02-27 16:26
Hi, I have experienced the same sort of problem, 
I can download the template, and import it and it will add the generic line, but when I use CSV with any other data in it, in the correct column layout , nothing loads.
