### ISSUE TITLE
Campaign Results Disappeared/Reverted

### ISSUE THREAD

**Issue by expectmore-commscope** [gophish/gophish#1080] opened 2018-05-25 14:41 UTC
Thank you for making an intuitive and easy to use framework!

What version of Gophish are you using?:  v0.5.0

Brief description of the issue: Results partially disappeared

What are you expecting to see happen? : An accurate campaign result

What are you seeing happen? : Results fluctuating

Longer Description : I ran a few concurrent campaigns and saw the results in the before image after a few hours. Decided to let it run a little longer and after approx 4 more hours from the last sighting, I was surprised to see the results showed a lower figure. Some targets that indicated as "clicked" now showed only "email opened". No changes were made after the campaigns were run, only the dashboard was being monitored from time to time.

Before : 
![image](https://user-images.githubusercontent.com/23272419/40550187-0034ac2c-606c-11e8-8ae0-9ec2603e090d.png)

After : 
![image](https://user-images.githubusercontent.com/23272419/40550217-1103869a-606c-11e8-827b-797c35df8ad5.png)

**Comment by S0larflare** [comment] 2018-05-25 14:46
Have you deleted any campaigns in the interim period?

Sent from my iPhone

On 25 May 2018, at 15:41, expectmore-commscope <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for making an intuitive and easy to use framework!

What version of Gophish are you using?: v0.5.0

Brief description of the issue: Results partially disappeared

What are you expecting to see happen? : An accurate campaign result

What are you seeing happen? : Results fluctuating

Longer Description : I ran a few concurrent campaigns and saw the results in the before image after a few hours. Decided to let it run a little longer and after approx 4 more hours from the last sighting, I was surprised to see the results showed a lower figure. Some targets that indicated as "clicked" now showed only "email opened". No changes were made after the campaigns were run, only the dashboard was being monitored from time to time.

Before :
[image]<https://user-images.githubusercontent.com/23272419/40550187-0034ac2c-606c-11e8-8ae0-9ec2603e090d.png>

After :
[image]<https://user-images.githubusercontent.com/23272419/40550217-1103869a-606c-11e8-827b-797c35df8ad5.png>

**Comment by expectmore-commscope** [comment] 2018-05-25 14:50
Nope, just left it as is after launching the campaigns.

**Comment by jordan-wright** [comment] 2018-05-25 17:16
Huh... that's... not expected. 😳 

So assuming that there was no activity except watching the results roll in, I guess the next step would be to download the events from the campaigns and analyze those to see if they match up. You can look at both the "results" (for the final status) as well as the raw events to determine what numbers you're seeing.

If all that fails, I'd then turn to the database to verify the data there. Just to make sure, nothing happened to the database while the campaigns were running, right?

It's definitely odd to see numbers drop like that, and I'm afraid at first glance I don't know what would cause something like that to happen. We'll work together to see if we can track this down.

Sorry again for the hassle!

**Comment by expectmore-commscope** [comment] 2018-05-26 14:18
So when I compare the events with the results. I do see more unique clicked events.
Checked the DB (The same data I retrieve from results, and events exists in their respective tables).
I'm guessing, when the server receives a callback from the tracker it is somehow overriding the clicked status. Not sure how it's "unsending" emails however.
Example : 
![image](https://user-images.githubusercontent.com/23272419/40577104-9b86bdfc-6132-11e8-80b4-876c5c267640.png)

**Comment by jordan-wright** [comment] 2018-05-26 21:02
Hmmm.... it's _possible_ that closing the tab might cause issues. I have it on the "Todo" list to update the campaign generation to use a database transaction as opposed to running each SQL command separately since, you're right, it makes things slower.

The status regression seems really odd to me, only because there are [safeguards](https://github.com/gophish/gophish/blob/222399c5f60664f3968b7ffb66ccfd0d7b8c62df/controllers/phish.go#L65) in place to prevent that exact behavior. The proper behavior is that the event will be added but the overall result status won't be updated. And you're saying that on the result row in the table, the status had changed back to "Email Opened"?

**Comment by expectmore-commscope** [comment] 2018-05-27 00:09
Yes, the result row in the table shows "Email Opened"
Results Table Query : 
![image](https://user-images.githubusercontent.com/23272419/40581199-d747cae6-6184-11e8-8088-4cceb634ba36.png)

Events Table Query : 
![image](https://user-images.githubusercontent.com/23272419/40581208-3578f02c-6185-11e8-9da7-7c3964ba9a9d.png)

**Comment by tcrimsonk** [comment] 2018-06-25 19:41
I just wanted to report I'm experiencing the same behavior.  The count of Sent, Opened, and Clicked are all much lower than they previously were.  Many targets have reverted to a status of Sending in the Results export, even though the Events export shows opens and clicks.

**Comment by jordan-wright** [comment] 2018-09-27 00:50
I apologize for the delay following up to this one, y'all.

@expectmore-commscope, do you by chance remember if this is something that happened as a result of an upgrade? I'm trying to determine if a database schema upgrade may have inadvertently caused this.

Otherwise, if you've run any campaigns recently, have you encountered the issue again? I'm seeing a few folks report similar results, though I'm not quite convinced they're 100% all connected so I'm trying to follow up with each one 😄 

Sorry again for the late response here!

**Comment by jordan-wright** [comment] 2018-09-27 00:50
Like @tcrimsonk, do you recall if your lower numbers happened after an upgrade, or if they occurred over time after a campaign was in progress?

**Comment by jordan-wright** [comment] 2019-12-06 02:43
Hey there!

I've merged 44f8840, which I anticipate fixes this issue. There are a couple of other PR's I hope to get merged in, then I'll cut a new release and you can take it for a spin 😄 

Sorry again for all the hassle! Hopefully this makes things work like a charm.

**Closed by jordan-wright** 2019-12-06 02:43 UTC
Labels: bug, support
