### ISSUE TITLE
max connection attempts reached when sending test email from new profile

### ISSUE THREAD

**Issue by ioannoug** [gophish/gophish#963] opened 2018-02-08 09:07 UTC
Hello, I want to use our Exchange server (in the same LAN) for sending emails.
I setup a new Sending Profile and then try to send a test e-mail.
I have captured the SMTP conversation in Wireshark and it seems like the client (the machine running the GoPhish service) closes the connection by sending a QUIT command (see below - IP addresses and hostnames redacted).

![handshake](https://user-images.githubusercontent.com/13318041/35964071-4ffb778c-0cbf-11e8-88bd-6435ca1dffb9.PNG)

This happens 10 times and then stops (perhaps related to the max connection attempts?)
Any ideas appreciated.
Thanks in advance

**Comment by jordan-wright** [comment] 2018-02-08 22:17
Thank you for providing the Wireshark capture!

Are there any logs from the terminal you can share? It seems to me that this is probably related to #959, which makes me think there might be something going on with the new mailing refactor.

**Comment by ioannoug** [comment] 2018-02-09 07:56
Thank you for the reply!
I am running the service from a windows machine, the only log I can find is the cmd output:
```
2018/02/09 09:20:48 mailer.go:78: Mailer got 1 mail to send
127.0.0.1 - - [09/Feb/2018:09:20:48 +0200] "POST /api/util/send_test_email?api_key=8c36120a2500f5f163d316efd188830c9a723ea51fc5d73e394ace04e92630dc HTTP/1.1" 500 86 "http://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
```
BTW I have tried the same with my antivirus disabled but it didn't make any difference.
Do you think there may be other logs?

**Comment by jordan-wright** [comment] 2018-02-10 23:17
Hmm... you don’t see any logs after that? And just curious, is it only when sending test emails or does it occur when running a campaign, too?

**Comment by ioannoug** [comment] 2018-02-12 08:14
Nope, no more logs. 
I am running this from a windows machine (gophish.exe) is there an option to increase verbosity?

Tried launching a campaign, the log is now: this:
```
2018/02/12 10:10:07 mailer.go:78: Mailer got 1 mail to send
2018/02/12 10:10:07 maillog.go:131: Erroring out result L7pWDGd
```
The admin interface shows this:
![campaign](https://user-images.githubusercontent.com/13318041/36087901-640e8eb4-0fdd-11e8-8711-ff30d082c0bc.PNG)

Plus,  the network pcap is identical.

**Comment by hummelm10** [comment] 2018-02-12 21:52
I am having the same issue with postfix 3.1.0-3ubuntu0.2 and the linux 64 bit release of v0.5.0 on Ubuntu 16.04.

**Comment by mantis-le-sin** [comment] 2018-02-13 15:15
I have the same issue when sending the test email using google. Ubuntu 64

**Comment by jordan-wright** [comment] 2018-02-13 15:42
Hey everyone,

I apologize for the delay on this. I'm working to track this down asap. I'll hopefully have a fix (and a new release) published by the end of this week. As soon as I determine the root cause, it'll get fixed.

I appreciate everyone's patience!

**Comment by mantis-le-sin** [comment] 2018-02-13 15:56
thanks dude!

**Comment by jordan-wright** [comment] 2018-02-15 03:51
I can't seem to reproduce this... I downloaded the latest windows x64 bit release, extracted the files, and tried two different options:

* Installing [Mailhog](https://github.com/mailhog/MailHog) and testing with an SMTP profile pointing to localhost:1025. Sending a test email works with no issues.
* Setting up an SMTP profile pointing to smtp.gmail.com:587 with my email/application password. Sending a test email works with no issues.

Can anyone provide more steps y'all are taking to reproduce this issue? It sounds like a bug, but I can't quite seem to make it happen on my end.

Alternatively, if anyone is building from source, don't hesitate to add logging to the `mailer` package that you think might help track things down.

Sorry again for the trouble. I'll be working to track this down as quickly as possible and I appreciate all the help!

**Comment by ioannoug** [comment] 2018-02-15 12:23
I can confirm that it worked using gmail's smtp service.

**Comment by hummelm10** [comment] 2018-02-15 12:35
I used a fresh install of Ubuntu 16.04 and the repository version of postfix and just the latest release unzipped. I can telnet to port 25 and send email through postfix and I can see that the postfix service is running. I can try adding some additional output from the mailer and rebuilding it.

**Comment by jordan-wright** [comment] 2018-02-15 14:18
Ok, cool, at least we're seeing the same things @ioannoug. @hummelm10 thanks for the steps to reproduce. I don't have an Exchange server handy but I can definitely get a postfix install set up. I'll give that a shot in the next couple of days and report back.

**Comment by ten85p** [comment] 2018-02-17 21:19
what do i need to set this up? do i need a cpanel or what?

**Comment by jordan-wright** [comment] 2018-02-17 21:29
@ten85p set what up? Gophish? You'll want to refer to our [excellent documentation](https://getgophish.com/documentation/) on how to setup Gophish for your system.

**Comment by jordan-wright** [comment] 2018-02-17 22:00
Just providing an update here - I've gotten the chance to test this out on a Debian VPS with postfix (default configuration installed) and had no issues when pointing my SMTP profile to localhost:25 and sending to a gmail address. The message was in spam, but it was delivered without issue.

Can y'all confirm you see everything work as intended in a previous release? I want to continue exploring this, but have yet to be able to reproduce this issue at all on my end after trying various OS / mail servers ☹️

**Comment by ioannoug** [comment] 2018-02-20 07:34
Hi jordan-wright,
Tested the same scenario with the 0.4 version (windows client, Exchange 2010)
I now have the following error when I send the test e-mail: "unencrypted connection". 
I hope this is helpful :)

**Comment by dingosnax** [comment] 2018-02-20 20:45
Just thought I'd share, I was getting the same error on test emails using a gmail account until I went into the settings on that gmail account and allowed low security apps.  Might be unrelated to the issues above, but I thought worth mentioning.

**Comment by jordan-wright** [comment] 2018-02-21 02:17
@ioannoug Thanks for testing so quickly! So, just to be sure, the email does _not_ send when using version 0.4? I could see the (non-ideal) case of having a generic error in place of the "max connections" error, but what I'm trying to determine is if this is a regression or not in that the email would send with 0.4, but it wouldn't send in 0.5. I haven't yet had anyone confirm that or not.

The "unencrypted connection" error appears when the server doesn't implement TLS (specifically when it doesn't return the `STARTTLS` extension after the client hello). From the pcap, it _appears_ that's the case here, but it's hard to confirm since the packet output is truncated.

**Comment by ioannoug** [comment] 2018-02-21 08:47
@jordan-wright I see what you mean. You are correct about TLS, the e-mail server does not return this extension. Are you saying that the e-mail should go regardless of the error?

The only difference I notice between 0.4 and 0.5 is that in the latter, the test e-mail is sent 10 times (hence the _maximum connection attempts_ error?) whereas in 0.4 it is only sent once.

Anyway, the email is _not sent_. I am sorry I couldn't be of much help :(

**Comment by jordan-wright** [comment] 2018-02-23 05:07
@ioannoug so what you're likely seeing is that the same underlying error is being thrown, but with the new mailer logic, Gophish is retrying 10 times before it gives up. So this doesn't appear to be a regression.

The best course of action is to enable TLS on your mail server. This is just best practice in general since, as it stands, it does not appear that emails are being encrypted before being received. This could allow eavesdroppers to view the contents of emails in transit.

Since everything that I can see indicates that this isn't a regression, I'm going to remove the "bug" label. However, I won't close the issue quite yet. I'd like to do some exploration to see if I can make the errors more clear so that instead of seeing "max connections reached" you'd see the original error. This would help with troubleshooting moving forward.

I appreciate everyone's patience! Don't hesitate to let me know if you have any questions.

**Comment by ioannoug** [comment] 2018-02-23 06:53
@jordan-wright thanks for all the help!

**Comment by raphagibello** [comment] 2018-02-27 20:12
Hello Jordan and everyone, I'm having the same errors show up.
I'm using the binary version on a debian 9.3 VPS I built today, trying both gmail and mail.com gives me the same error, "max connections reached" after 1min, the only output on the logging/running terminal of GoPhish is the following:

 2018/02/27 19:52:20 mailer.go:78: Mailer got 1 mail to send

The configs I'm running are the following, however the email I'm running a legit one with the right password. I have set the allow insecure/low security apps on google.


![image](https://user-images.githubusercontent.com/26435576/36752212-1f53baaa-1be1-11e8-9fdc-867155db420e.png)

**Comment by shanebo50** [comment] 2018-02-28 17:55
I also experienced this issue when using gmail as the host. As @dingosnax mentioned above, allowing less secure apps on your google account seems to clear it up. Also had to remove two-factor authentication on my account in the process... not really ideal, but it seems to work for now.
Here's an article about allowing less-secure apps:
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by Dantewhyte** [comment] 2018-03-08 06:53
Hey Jordan
I'm experiencing this same max connection issue and i really don't know what to do. 
a little help here? anyone?

**Comment by Dantewhyte** [comment] 2018-03-08 06:56
@jordan-wright I really need help here, I've been stuck on the "max connection" issue and i just can't seem to send any test emails
Please reply asap

**Comment by Dantewhyte** [comment] 2018-03-08 10:35
Anyone here??

**Comment by jordan-wright** [comment] 2018-03-08 14:57
@S0larflare is, as always, absolutely correct. @Dantewhyte, please know that everyone here is volunteering their time, so expecting a response in 4 hours is unreasonable. And we'll definitely need more information to help troubleshoot.

I've outlined a plan [above](https://github.com/gophish/gophish/issues/963#issuecomment-367911269) to try and make this more user friendly but haven't merged things in yet. In the meantime, it is almost certain that there's some kind of network/authentication issue preventing Gophish from sending the email with the current configuration.

**Comment by Dantewhyte** [comment] 2018-03-08 20:51
@S0larflare @jordan-wright It works!!! Thanks for the help, Grazie

**Closed** 2018-03-23 03:05 UTC
Labels: support

**Comment by jordan-wright** [comment] 2018-03-23 03:06
Hey everyone,

I've fixed this where now you will see the underlying error being reported alongside the "max connection attempts exceeded message":

![image](https://user-images.githubusercontent.com/1317288/37809422-409bf0c6-2e1d-11e8-9c91-4eea0e0efd48.png)

Hope this helps!

**Comment by jbonatelli** [comment] 2018-03-23 19:03
I've tried Hotmail and Gmail but i cant send e-mail test !!! Don't now what i need to do to fix this issue.

**Comment by S0larflare** [comment] 2018-03-23 19:04
If you can build from the latest source, there is now enhanced error reporting for this, so it might help track down where the issue lies

Sent from my iPhone

On 23 Mar 2018, at 19:03, jbonatelli <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tried Hotmail and Gmail but i cant send e-mail test !!! Don't now what i need to do to fix this issue.

**Comment by jbonatelli** [comment] 2018-03-23 19:08
I have a fresh copy from the lastest version of GoPhish.

**Comment by jordan-wright** [comment] 2018-03-25 02:45
@jbonatelli just make sure that you’re building Gophish from source, not using a precompiled binary. If you’re building from source, you’ll have a  better error message.

**Comment by rurapenthe** [comment] 2018-04-02 18:09
I'm having the same problem on 0.5.0
I've tried;
Zoho Mail's SMTP
Amazon SES SMTP

Both return the same error, however if I use telnet on the GoPhish host to send email it works perfectly. 
Jordan-wright, If you can't reproduce i would be happy to share my Amazon SES creds with you to try and see if the error persists your side.

**Comment by rurapenthe** [comment] 2018-04-02 19:23
Okay I checked out the latest version from source and built it.

It seems the max connections is, as was mentioned, a catch-all error - with the actual error now showing in the new build. In my case it was an auth problem. 

So all is well. thanks for the hard work.

**Comment by f3max** [comment] 2018-04-12 09:38
@shanebo50  thanx man .. worked. 

https://myaccount.google.com/lesssecureapps  

[gmail]

check this page and ..  turn on Allow less secure apps...

**Comment by docsewell** [comment] 2018-11-26 17:38
I got this message on 11/26/2018 until I went into my sending profiles and added :465 (SMTP / TLS port number) to the end of my server name.  Then it started working.

**Comment by quarkman142** [comment] 2019-02-18 03:53
Same problem on Kali Linux 2018.4 ... very odd too as it was the first and only connection attempt after several reboots.  Coded smtp as 127.0.0.1:25 or localhost:25.  What's going on guys?

**Comment by knaave** [comment] 2019-03-18 15:05
Hi,

I have an issue as well, unfortunately. Error: Max connection attempts exceeded - dial tcp [::1]:25: connect: connection refused. Unsure what's causing it.

**Comment by security-prince** [comment] 2020-05-13 12:26
Hi @jordan-wright  , i am having a similar error on my end, in my case I am using gophish v0.9.0 and  Gmail SMTP to send out emails, for me, I tried sending out the emails to over 600 users at once but after 78 success I started getting this error `Error Max connection attempts exceeded - 454 4.7.0 Too many login attempts, please try again later. o6sm14466556pfp.172 - gsmtp`, what i am wondering is does gophish tries and logs in to Gmail SMTP for sending each email? if yes may be this is what is causing this error. As for logs I checked the error log for gophish i am seeing this error in it `2020/05/13 12:22:36 http: TLS handshake error from <IP>: remote error: tls: unknown certificate`

**Comment by kyleian** [comment] 2021-09-10 09:09
For an AWS SES conf, although :25 is supported by the SES SMTP settings, updating the gophish sender profile to use :465 resolved max connection attempt errors in my setup. Hope this helps someone.

**Comment by lypacd** [comment] 2022-10-31 11:57
我使用的是163邮箱，将邮箱服务器端口从25改为465则可以成功发送
