### ISSUE TITLE
Export Results & Events to CSV Not Working 

### ISSUE THREAD

**Issue by JGoLabs** [gophish/gophish#374] opened 2016-09-18 13:46 UTC
When you attempt to export the results of a Campaign to CSV (either events or results) you get the following behavior:

1 - On Mac there is no feedback - the CSV is never generated and the progress meter in the address bar just hangs.  You can click elsewhere and do other things, but there is no CSV.

2 - On Windows you are asked if you want to download the file (results.csv or events.esv depending on your choice) and then are told that the file couldn't be downloaded.

**Comment by jordan-wright** [comment] 2016-09-26 02:29
This is a duplicate of [this question](https://github.com/gophish/gophish/issues/250) and is a known issue. The root cause is that Safari does not support the `download` attribute. The long term fix is that I'm going to put in an API endpoint to handle CSV downloading instead of doing it with Javascript, but I have other things I need to work on first.

**Closed** 2016-09-26 02:29 UTC
Labels: duplicate
