### ISSUE TITLE
Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful on office 365

### ISSUE THREAD

**Issue by jayesh1974** [gophish/gophish#1853] opened 2020-06-02 15:16 UTC
What version of Gophish are you using?: 10.1

Brief description of the issue: Can't use Office 365 SMTP to send mails

What are you expecting to see happen? : I want to send email using office 365 SMTP from Godaddy

What are you seeing happen?: I can see the below error:
 Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [SG2PR01CA0106.apcprd01.prod.exchangelabs.com]
Please note that I am using office 365 SMTP from Godaddy associated with my domain. My POP and IMAP are enabled in the mail.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - sender profile SMTP settings 
Host: smtp.office365.com:587

**Comment by jayesh1974** [comment] 2020-06-02 15:20
time="2020-06-02T20:42:22+05:30" level=error msg="Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [SG2PR01CA0106.apcprd01.prod.exchangelabs.com]"
time="2020-06-02T20:42:22+05:30" level=info msg="127.0.0.1 - - [02/Jun/2020:20:40:27 +0530] \"POST /api/util/send_test_email HTTP/2.0\" 500 174 \"https://localhost:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36\""

**Comment by jordan-wright** [comment] 2020-06-06 15:07
Hi there!

This appears to be a duplicate of #1822. I'd recommend taking a look at the comment at https://github.com/gophish/gophish/issues/1822#issuecomment-634006115 to see if it helps track down the issue.

Thanks!

**Closed by jordan-wright** 2020-06-06 15:07 UTC
