### ISSUE TITLE
Feature Addition: Pagination

### ISSUE THREAD

**Issue by ghost** [gophish/gophish#1609] opened 2019-10-01 10:20 UTC
Hi there!

We are using Gophish 0.8.0. Most of the work is like integration of Gophish system to Moodle LMS.

Brief description of the issue: 
We find out the most of GET API (Ex. GET ALL TEMPLATES, GET ALL LANDING PAGES) does not support pagination. Now to solve this problem we are directly making request to MYSQL server
to fetch the results.

What are you expecting to see happen? :
We are expecting that their should be some query parameters which we can pass in request
to limit the number of result fetching from the system.

What are your ideas about adding pagination as feature ?

**Comment by jordan-wright** [comment] 2019-11-11 20:42
Closing this since it's a duplicate of #29 and the user who created the issue has since deleted their account.

**Closed by jordan-wright** 2019-11-11 20:42 UTC
