### ISSUE TITLE
Webhook has improperly formatted JSON

### ISSUE THREAD

**Issue by Al-TSN** [gophish/gophish#1798] opened 2020-03-27 20:33 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.9

Brief description of the issue: The JSON returned with the webhook is in improperly formatted. The details key is included as a string.
`{'campaign_id': 8481, 'email': 'Johnd@company.com', 'time': '2020-03-27T19:07:41.1507272Z', 'message': 'Email Opened', 'details': '{"payload":{"rid":["b4AjagC"]},"browser":{"address":"108.5.157.206","user-agent":"Mozilla/4.0 (compatible; ms-office; MSOffice 16)"}}'}`

As you can see there are extra quotes before and after the detail key.

What are you expecting to see happen? :
`{
	'campaign_id': 8481,
	'email': 'Johnd@company.com',
	'time': '2020-03-27T19:07:41.1507272Z',
	'message': 'Email Opened',
	'details': {
		"payload": {
			"rid": ["b4AjagC"]
		},
		"browser": {
			"address": "108.5.157.206",
			"user-agent": "Mozilla/4.0 (compatible; ms-office; MSOffice 16)"
		}
	}
}`
What are you seeing happen?

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2020-03-28 01:13
Hey @Al-TSN!

Thanks for reaching out! While this isn't preferred behavior, it is expected since Gophish does return the `details` key as a string due to historical reasons.

In the future, it's possible that we could change the [object definition](https://github.com/gophish/gophish/blob/master/models/campaign.go#L82) to be a `map[string]string` or similar, but I'm a bit hesitant to do so without more consideration since this would break existing API clients.

I'll think on this a bit more and will get back to you. Thanks again for getting in touch!

**Comment by Al-TSN** [comment] 2020-03-28 10:43
Possible to create a details_map key and have both to maintain backwards compatibility?

However, now that we understand we can handle.

**Comment by jordan-wright** [comment] 2020-05-23 16:04
Since this is the expected behavior, I'm going to go ahead and close this one out. Eventually I'll see about moving this to a map but I don't anticipate I'll have the cycles to handle it soon.

Thanks for sending this in!

**Closed by jordan-wright** 2020-05-23 16:04 UTC
