### ISSUE TITLE
{{.URL}} Placeholder overwrites entire Anchor element instead of just `href` value

### ISSUE THREAD

**Issue by ndom91** [gophish/gophish#1758] opened 2020-02-26 11:33 UTC
What version of Gophish are you using?: **0.9.0**

#### Brief description of the issue: 

In Email Templates, when entering, for example:

```
<a href="{{.URL}}">https://drive.google.com/file?id=123abc</a>
```

The resulting Email replaces the entire anchor element, including the text which gets displayed with the gophish listener URL. 

#### What are you expecting to see happen?:

I want it to be like this:

```
<a href="https://listener.gophish.example.com?rid=123">https://drive.google.com/file?id=123abc</a>
```

Instead, it ends up like this:
```
<a href="https://listener.gophish.example.com?rid=123">https://listener.gophish.example.com?rid=123</a>
```

Is there any way to have the `{{.URL}}` placeholder only replace the `href` value?

**Comment by jordan-wright** [comment] 2020-03-01 01:54
I'm having trouble reproducing this. In my email template, I have:

```html
<html>
    <head></head>
    <body>
        <a href="{{.URL}}">https://drive.google.com/file?id=123abc</a>
    {{.Tracker}}</body>
</html>
```

Then, I create a campaign with `http://notgoogle` as my URL. The email I receive contains:

```html
<html>
    <head></head>
    <body>
        <a href=3D"http://notgoogle?rid=3DiIDfGky">https://drive.google.com=
/file?id=3D123abc</a>
    <img alt=3D'' style=3D'display: none' src=3D'http://notgoogle/track?rid=
=3DiIDfGky'/></body>
</html>
```

Which appears to be the expected output. I'm going to go ahead and close this out for now since things appear to work as intended, but if you could please provide a template you're using that reproduces the issue, I'd be happy to continue troubleshooting.

Sorry I couldn't be of more help!

**Closed by jordan-wright** 2020-03-01 01:54 UTC

**Comment by ndom91** [comment] 2020-03-01 14:57
@jordan-wright yeah so I ran a few test campaigns, only sending it to myself, and the emails always exhibited the behavior I explained above.

However, once I ran an actual campaign and targeted all other colleagues, it was working as you described / I expected. 

Other than the target group I didnt change anything, so I'm not sure what was going on. 

So yeah you can keep this closed as far as I'm concerned.

**Comment by jordan-wright** [comment] 2020-03-01 15:59
Out of curiosity, did the group you sent the campaign to use the same email service you do?

As in, I’m wondering if this is an issue where your email provider is (helpfully!) rewriting links to their actual origin to prevent this kind of phishing.

However, if the campaign recipients use the same email provider then that would lean towards disproving my theory :)

**Comment by ndom91** [comment] 2020-03-01 16:37
Yeah so we're all using Gmail (G Suite), which is the sender im using as well.
