### ISSUE TITLE
Can't add users or email templates

### ISSUE THREAD

**Issue by JellyWelly** [gophish/gophish#1005] opened 2018-03-12 11:37 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0 

Brief description of the issue: 
Issue 1. Trying to add users, I've gone to Users & Groups, Created a group, Done bulk upload, Can see all the users in the preview box below all in the correct fields (297 Users) press Save, it says the group has been updated but no users actually go in there. I've followed various threads about doing it UTF-8 format, swapping the position and email field around. None work

Issue 2.  Can add a new email template, I've created one, Can view it in the preview before saving the template, All looks good, press save template, tells me its saved ok but it's not in the email templates list, If I try create it again using the same template name, it says I can't as it already exists. Doesn't matter if I do a complicated one or a simple 'Hello' still doesn't appear in the list.

What are you expecting to see happen? : In both instances for it to actually appear but never

What are you seeing happen? As above, it's saying its saved on both instances but there's nothing there.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by JellyWelly** [comment] 2018-03-12 16:34
Good Afternoon,

Just wanted to confirm, It's not just uploading users, I can't add them manually either.

**Comment by S0larflare** [comment] 2018-03-12 16:53
Perhaps the problem is that your database is read only or there isn't any space? Are there any errors on the console when you're doing this?

**Comment by jordan-wright** [comment] 2018-03-12 23:08
Hi @JellyWelly, thanks for reaching out! As @S0larflare suggested, one of the best things to check for are:

* Logs in the developer tools for your browser (are there any console errors being thrown?) when you attempt to submit the forms
* Logs in the terminal running Gophish when you attempt to submit the forms

If you could provide those logs to us, we can continue troubleshooting.

Thanks!

**Comment by JellyWelly** [comment] 2018-03-13 07:15
Hi,

Thanks for the reply, here’s what I  can see in the logs

[cid:image001.png@01D3BA23.369D0C40]

**Comment by S0larflare** [comment] 2018-03-13 08:10
Can't see the image there I'm afraid...

That aside, the implication that you work for Haribo has just made my morning...and given me a craving for goldbears.

**Comment by JellyWelly** [comment] 2018-03-13 09:05
Hi thanks for the replies
 Updated image, on the previous post
Don't see any errors in the developer tools (Used EDGE, IE and Firefox).

**Comment by S0larflare** [comment] 2018-03-13 14:22
I'm wondering if the group name or the user id isn't getting set right in the database. Might be barking up the wrong tree but if you look at the users table, is the id there the same as the user id in the groups table and are the names correct in there (or is it blank?). The errors you've shown are from GetGroup() and GetGroupByName().

**Comment by JellyWelly** [comment] 2018-03-13 15:03
Hi S0larflare, 

In the users folder I can only see the admin account. If I go into 'Targets' I can see the users I've uploaded but there is no group field in this table. The ID's are just sequential up to 299

![users1](https://user-images.githubusercontent.com/37294856/37349606-bc1461e4-26ce-11e8-986d-7cdefe797737.JPG)

In groups I see

![groups](https://user-images.githubusercontent.com/37294856/37349781-1297c5a6-26cf-11e8-9b9e-1566efa40b20.JPG)

Also in the web I must say they don't display the users or the groups. 

Should I just delete the entire DB and rebuild from scratch ?

**Comment by S0larflare** [comment] 2018-03-13 15:08
If you haven't done anything so far that you need to keep, deleting the db and starting again might be worth it, if only to rule out some weirdness on that end. Yes it was the users table I was after, the one with just admin (or any other 'gophish users' if you have added any extras) as I wanted to make sure that the ID matched the user_id. If you havent added any it should look just like:

id|username|hash|api_key
1|admin|<password hash>|<api

**Comment by JellyWelly** [comment] 2018-03-13 15:36
Hi,

Right some weirdness here, I've deleted the db and rebuilt it. Added a new group and uploaded some users to it. I have to log off the browser and back in to see the changes reflect (Used Edge, IE11 and Firefox 55.0.1 (32-bit)),

By logging in and off at each stage, I've been able to set up an email template and campaign and send it to myself. Now I have other issues :o which I'll have to research on the forum here and see.

**Comment by jordan-wright** [comment] 2018-03-14 00:44
> I have to log off the browser and back in to see the changes reflect

That's awfully peculiar. I haven't heard of that before. Just curious, do you have any extensions or other things that might be messing with the session cookies? Are there any logs from the terminal when you've added the object and refreshed the page that might give away what's going on?

Finally, you might check with Chrome, since that's what I use for development. I try to design things such that they work in other browsers, but don't have the time to check everything.

 > the implication that you work for Haribo has just made my morning...and given me a craving for goldbears.

Haribo Gold Bears are the best gummy bears there are. I am willing to fight people who say otherwise 😜

**Comment by JellyWelly** [comment] 2018-03-14 08:09
> That's awfully peculiar. I haven't heard of that before. Just curious, do you have any extensions or other things that might be messing with the session cookies? Are there any logs from the terminal when you've added the object and refreshed the page that might give away what's going on?

No other extensions they are all base browsers, Tried in Chrome this morning and it works perfectly.

I do have some other queries that'll I'll log in a different thread, Thanks for all your help on this so far.

**Comment by jordan-wright** [comment] 2018-03-21 04:15
Since things do appear to work in Chrome, I'm going to go ahead and close this one out. I'll do some digging on my own when I get a chance to verify that I don't encounter this issue with a default installation in IE/Firefox. If I run into the same issue you did @JellyWelly, I'll re-open this to track a fix. Otherwise, we can chalk it up to "weirdness", I suppose. 😄

**Closed by jordan-wright** 2018-03-21 04:15 UTC
Labels: support

**Comment by vinojebastin** [comment] 2023-11-08 10:37
I am getting this error " Error inserting template into database" please someone help me to save an email template

**Comment by Leo-Aqua** [comment] 2024-03-04 20:42
sqlite3 is probably not installed, install it with:
`sudo apt update && sudo apt install sqlite3`
