### ISSUE TITLE
The campaign results( csv files) have captured few incorrect details

### ISSUE THREAD

**Issue by patilprateek** [gophish/gophish#496] opened 2016-12-19 09:06 UTC
Hi All,

2 queries in all:-

1) I was doing a test with gophish earlier limited to a small group of people, and was successful. However, when i happened to roll a campaign with close to 1000+ users, although it was successful, i happened to receive feedback from end users that they did not happen to click on the phish link, but my report says that it was sent to the user & was success. Am sure that the users who have given those feedback are genuine, as when i backtracked the IP's captured in the report, it points to some another users machine.

Also when i asked my colleague to open the email and get phished - the output was that i can only see the mail sent to him, and it doesn't show me details that he opened the mail, and then got phished or not.

What could be the reason for this to happen, since if this is the case, we actually cant have a fair/ accurate number of who did get phished?

2) In the results, the users who get phished, we can details of their IP and also the browser info - from where does it pick that up, since all the users getting phished show the info as - {"payload":{"rid":["e9d80dcfad8e7edb3d545f60ab4ea63ab8d28e5b2a8d6beacf9e7578e3"]},"browser":{"address":"x.x.x.x",**"user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)** like Gecko"}} - I am using chrome  to create, track the campaign & its output - but the info shows mozilla?

**Comment by patilprateek** [comment] 2016-12-20 12:27
Was able to identify the 1st issue after doing some analysis, the original email if sent to the designated recipient and he clicks on the link, is the desired output. But if the email was forwarded/ attached and then sent to person B and this person click on the mail, the email ID captured in the report is of person A, but the IP address captured is of person B's machine. Is this normal mechanism/ or have i misconfigured on something at my end?

**Comment by S0larflare** [comment] 2016-12-20 14:31
That's normal. The ID given is unique to the user, ie based upon their email address. That ID is generated and put into the link for that email, so if that email is forwarded to somebody, gophish would assume that somebody is the person that they sent it to. It would be pretty difficult to have it work any other way to be honest.

**Comment by jordan-wright** [comment] 2016-12-21 03:56
@S0larflare is absolutely correct. This is intended behavior. The id added to the end of each link is unique for each recipient. Whenever the link is clicked, it's registered as that user.

I don't know of any better way to do this, but I'm always open to suggestions! 

That log indicates that the browser user agent of the person who clicked the link, not your machine.

I'll go ahead and close this out since this is all intended behavior. I don't see anything in here that would indicate a bug in gophish.

**Closed by jordan-wright** 2016-12-21 03:56 UTC
