### ISSUE TITLE
See campaign settings in the UI

### ISSUE THREAD

**Issue by teex** [gophish/gophish#960] opened 2018-02-07 13:19 UTC
What version of Gophish are you using?: 
0.5

Brief description of the issue: 
If this functionality is already avaialbe, please close this issue. If not I guess it is more of a feature request than an issue.
I cannot see the settings (such as email templates, landing pages etc. Basically the "launch campaign dialogue) for a campaign that has been launched, nor change them. I am sure they can be accessed by looking in the database, or might also be using the api, but it would be nice to have it in the UI. In the long term it would also be nice be able to change settings for campaigns that has not started yet.

What are you expecting to see happen? :
Well, the settings of the specific campaign would be nice.  :)

What are you seeing happen?

Dont see the settings at all.

Please provide as many steps as you can to reproduce the problem:
1. Create a campaign.
2. Click on the icon for the details of the campaign. 
3. Try to find the "settings" or "configuration" button;)

**Comment by S0larflare** [comment] 2018-02-07 13:26
Would you be able to provide any screenshots to show what you mean?

Sent from my iPhone

On 7 Feb 2018, at 13:19, Henrik Åmark <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Gophish are you using?:
0.5

Brief description of the issue:
If this functionality is already avaialbe, please close this issue. If not I guess it is more of a feature request than an issue.
I cannot see the settings (such as email templates, landing pages etc. Basically the "launch campaign dialogue) for a campaign that has been launched, nor change them. I am sure they can be accessed by looking in the database, or might also be using the api, but it would be nice to have it in the UI. In the long term it would also be nice be able to change settings for campaigns that has not started yet.

What are you expecting to see happen? :
Well, the settings of the specific campaign would be nice. :)

What are you seeing happen?

Dont see the settings at all.

Please provide as many steps as you can to reproduce the problem:

  1.  Create a campaign.
  2.  Click on the icon for the details of the campaign.
  3.  Try to find the "settings" or "configuration" button;)

**Comment by teex** [comment] 2018-02-07 14:32
This is the information that would be nice to see, after the campaign has been created.
![capaign settings](https://user-images.githubusercontent.com/2184959/35921820-10205dba-0c1c-11e8-98bc-bab2a1512cc5.PNG)

**Comment by S0larflare** [comment] 2018-02-07 14:35
If you go to the campaigns page, which shows all the current campaigns, and hover over the status, you should get a bubble with most of the info you are interested in. Something like this (it will look different as this was something that I homebrewed prior to Jordan adding the feature)

![image](https://user-images.githubusercontent.com/8939757/35921953-19967512-0c14-11e8-8e96-a876f43ca238.png)

**Comment by teex** [comment] 2018-02-07 14:58
Yeah, I've seen that. It would be nice to see all the settings tho, such as what group(s) one actually selected when launching the campaign. If it is too much hassle I'll just use the API, but was more thinking that it might be a nice future feature:)

**Comment by S0larflare** [comment] 2018-02-07 15:04
You can use the api ( I believe all the info is within the campaign api call, though can't be 100% without checking). Alternatively, as a bit of an untidy but quick and easy solution, yo ucan click on copy campaign, this should inherit all the settings of the campaign for you to see at a glance.

I did look in to having a 2nd tab within the campaign results screen but in the end I would have had to add some new api calls in order to grab any extra data and I didn't have a need for any of it, so never bothered any more:


![image](https://user-images.githubusercontent.com/8939757/35923419-17b127ac-0c18-11e8-876b-2d00c045cff2.png)

**Comment by teex** [comment] 2018-02-07 15:07
I'll just go with the api then. Thank you for looking into it:)

**Comment by jordan-wright** [comment] 2018-02-07 23:57
Thanks for all the great follow-up @S0larflare! I'll go ahead and close this one out. @teex I definitely recommend checking out the API, since it should have the info you're looking for. Let us know if you run into any other issues!

**Closed by jordan-wright** 2018-02-07 23:57 UTC
