### ISSUE TITLE
Gophish results.csv and status reporting issue

### ISSUE THREAD

**Issue by IAMPi** [gophish/gophish#529] opened 2017-02-03 02:38 UTC
Greetings, 

I'm running 0.3-dev (compiled ~2weeks ago).  Is it intended that the users status be over written by the last event?  As an example if a user has submitted credentials and then goes back and clicks the link then their status shows up as clicked link.  This is also true in the exported results.csv.

**Comment by jordan-wright** [comment] 2017-02-03 02:40
Hmmm... that's not intended. I'll investigate and will see if I can reproduce the issue.

**Comment by IAMPi** [comment] 2017-02-03 03:24
Much appreciated Jordan.  I would like to note that events.csv does record all events correctly so at the end of the day the data is there.

**Comment by jordan-wright** [comment] 2017-02-11 02:15
Hey @IAMPi,

I'm having difficulty reproducing this issue with the latest source. If I click the link, the status is "Clicked Link", if I submit credentials the status is "Submitted Data", and if I click the link again, the status is still "Submitted Data".

Can you confirm this bug is present in the latest source?

**Comment by IAMPi** [comment] 2017-02-11 15:55
Hey Jordan,  

I'll need a few days to upgrade but I did look through the latest campaign(~400 users) and of course its everyones favorite type of bug....intermittent/inconsistent.  We have users that submitted data and then clicked the link again and they show up as submitted(which is what I assume is correct). 

Also note I've see this bug in smaller user group set of 4 users that we use to test a campaign before launching.

**Comment by jordan-wright** [comment] 2017-02-11 22:02
Oh how interesting! Would you be willing to post the relevant events csv entries for a single user who experienced this? Feel free to redact the email address.

My only guess is that something they are doing is causing this to happen.

**Comment by cclements** [comment] 2017-02-17 21:01
Hey Jordan, I'm having this same issue with a campaign from gophish compiled at the latest commit.  The webui reports the users status as the last action they took rather than the highest severity action they took.  E.g. if they submitted credentials but then click the link again, the status shows as "clicked link"

**Comment by jordan-wright** [comment] 2017-02-19 21:32
@cclements Thanks for letting me know!

Would you be willing to post the "raw events" output for the affected user? It seems like this is only happening under certain circumstances, so it'd be good to track down what's causing this.

**Comment by jordan-wright** [comment] 2017-02-20 00:54
Also, when this is occurring, is it just the web ui that is reporting the wrong status, or does it also show up in the exported "Results" CSV?

**Comment by cclements** [comment] 2017-02-20 03:11
Both in the webui and in the results csv.  Events csv is correct, however.

**Comment by jordan-wright** [comment] 2017-02-20 04:04
Interesting.. what are the events for that user you see in events.csv? As much information as you'd be willing to provide would be helpful.

**Comment by jordan-wright** [comment] 2017-02-23 00:37
Hey @cclements and @IAMPi - just checking in. Would either of y'all be willing to post the contents of `events.csv` for an affected campaign. All we need is the (email redacted) logs for a recipient who was affected by this bug.

Chances are, something in the flow they're doing is causing this to happen and seeing the events themselves would help me a ton in troubleshooting this.

**Comment by IAMPi** [comment] 2017-02-23 04:43
Hey Jordan, 

I've uploaded three versions of the sample data.  While compiling the data I did notice that almost all users who submitted credentials(and it was recorded correctly)  had no additional events.  If the user did have additional evens it was usually a single link click from the customers mail filter solution.  Is it possible its when a user registers multiple events from a different IP causes the problem?  Though user3 in the sample data I provide doesn't really support that theory.


![image](https://cloud.githubusercontent.com/assets/3022045/23245077/e034861c-f957-11e6-9daf-878c2673029f.png)
[gophish_data.pdf](https://github.com/gophish/gophish/files/795552/gophish_data.pdf)
[gophish_data.xlsx](https://github.com/gophish/gophish/files/795554/gophish_data.xlsx)

**Comment by jordan-wright** [comment] 2017-02-23 04:52
Ah, that's perfect! I'm almost positive I see the problem.

I'm guessing that the new status is "Email Opened", right? It looks like when I changed the statuses to say things like "Clicked" or "Submitted Data", I forgot to update the check on "email opened".

I'll verify everything and will push out a fix tomorrow evening. If all looks good, that will be the final thing I wanted to knock out before releasing the new set of binaries!

Thanks so much for sending over this data!

**Comment by IAMPi** [comment] 2017-02-23 05:12
I looked through all the users who had their "Submitted" status overwritten as "clicked". All had an additional "Open" event after the submit but prior to the new click.   I'm assuming that once their status was reset to "Open" then they could further changed to a click status if they clicked. This supports your theory.


This users end status is "Clicked"
![image](https://cloud.githubusercontent.com/assets/3022045/23245562/7522d438-f95b-11e6-9703-6157ba7781a1.png)

**Comment by jordan-wright** [comment] 2017-02-24 05:23
Sorry for the delay! This should be fixed as of d67dcc889a124a70a25fd6eab7677952e3f33ab4.

Thanks again for your patience and help in getting this resolved!

**Closed** 2017-02-24 05:23 UTC
Labels: bug
