### ISSUE TITLE
Feature Request - Preview & Test Landing Pages

### ISSUE THREAD

**Issue by RCPMAD** [gophish/gophish#606] opened 2017-04-26 12:50 UTC
This would be very useful because at the moment I have to use a second tool to edit a landing page and run a campaign each time I want to see how it look like. I sometimes need to edit a page to leave clues for users to identify the website as malicious but also because some websites have cloning protection and they cannot be imported. Some imported websites will still capture passwords even when told not to do it. Would be extremely useful to have the option to generate a test landing page where we can see how it looks like and test with credentials.

**Comment by jordan-wright** [comment] 2017-04-26 13:36
It's possible to see what a landing page will look like by clicking the "source" button in the editor. There's also a full screen option.

Is this what you're referring to, or are you talking about actually testing credentials against it?

**Comment by RCPMAD** [comment] 2017-04-26 14:13
I am aware of the source and full screen button but I am not always getting the perfect preview. Testing credentials against it would be very useful.

**Comment by jordan-wright** [comment] 2017-04-27 23:00
Looks like this one is a dupe of #114, so I'll close it out in favor of that issue.

Rest assured - this is one of the things I want to get knocked out. I'll just need to figure out the best way to make that happen since pages right now are generated dynamically when the request is received. 😄 

Thanks for sending in this issue!

**Closed by jordan-wright** 2017-04-27 23:00 UTC
