### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by coreyfire** [gophish/gophish#206] opened 2016-03-10 20:21 UTC
Put the ability to stagger emails, send randomly, send on schedule, etc. 

I did not see this asked yet, and the only way I have figured out a work around for this is to create separate campaigns to send the email individually. This kills the reporting feature of GoPhish. 

I would really like to see this implemented, or if it is already, how to do this. 

Thank you so much in advanced! I really like GoPhish so far, it is easy, and fantastic!

**Comment by jordan-wright** [comment] 2016-03-11 05:09
Hey @coreyfire - thanks for the suggestion! It looks like this might be a dupe of #110.

I'm going to go ahead and close this one out, since we'll keep the discussion on that issue. Just know that this is absolutely in the works :smile:

**Closed by jordan-wright** 2016-03-11 05:09 UTC
