### ISSUE TITLE
accents (é and à) not well encoded in users bulk import

### ISSUE THREAD

**Issue by Obyka** [gophish/gophish#1694] opened 2019-12-14 20:33 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
 0.7.1 
Brief description of the issue: 
When I import users via CSV, those with a name containing an accent (e.g é) are not correctly encoded.
What are you expecting to see happen? :
Accents supported the same way as when you create a user manually
What are you seeing happen?
![image](https://user-images.githubusercontent.com/28777250/70854231-3b3f2b00-1eb9-11ea-95c0-ac1d4f0c1538.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Creating a new group
 * Step 2 -  Importing users via CSV containing name such as André, Mélanie, ...

**Comment by jordan-wright** [comment] 2019-12-14 21:03
Hi there!

I think this is a duplicate of a previous issue. But just in case, could you please upload a CSV that reproduces this issue? And which browser are you using?

**Comment by Obyka** [comment] 2019-12-14 21:11
Hi,
Thanks for your quick answer. 
I'm using Firefox (up to date)

While trying to upload the CSV, I noticed that if I copied then pasted the content in a plain .txt file then import it in Gophish, it works just fine, so I guess AINSI was not supported ?

Here is an example (couldn't upload my real one for NdA)

[issueCSV.txt](https://github.com/gophish/gophish/files/3964350/issueCSV.txt)

And here is the associated output.

![image](https://user-images.githubusercontent.com/28777250/70854642-9d4e5f00-1ebe-11ea-8426-f68e9ead44fc.png)

PS : Thanks for your work and the great tools you guys provide :)

**Comment by bhayes-zd** [comment] 2020-11-20 00:04
@Obyka  I'm kinda late to the thread here, but here is a bit of Go you can use to circumvent this by using the API to submit users. It takes in a spreadsheet, converts the characters into utf-8 compatible chars, and outputs a JSON payload that seems to work fine as a POST request against the `/api/groups` API endpoint. Hope this helps anyone else who stumbles across this issue.

https://gist.github.com/bhayes-zd/9687b76342a8df84c5c4b7da4f5a1b48

**Comment by Obyka** [comment] 2020-11-28 19:31
> 
> 
> @Obyka I'm kinda late to the thread here, but here is a bit of Go you can use to circumvent this by using the API to submit users. It takes in a spreadsheet, converts the characters into utf-8 compatible chars, and outputs a JSON payload that seems to work fine as a POST request against the `/api/groups` API endpoint. Hope this helps anyone else who stumbles across this issue.
> 
> https://gist.github.com/bhayes-zd/9687b76342a8df84c5c4b7da4f5a1b48

Thanks for your answer! 
My project is now over, but I'm sure your code will help many others persons :)

**Closed** 2021-06-20 21:42 UTC
