### ISSUE TITLE
.csv to users & Groups

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1222] opened 2018-10-02 08:02 UTC
I live in Denmark and we have special characters that, when i import users from a .csv files, the special characters are changed. what should look like Hej Henrik Kraiø looks like
![udkliprewtr4ewt](https://user-images.githubusercontent.com/38277384/46336031-d25bf200-c629-11e8-96a2-8d78c42d4deb.PNG)
is this a mistake, it does this, and can it me fixed.
It works when i manual make a user.

**Comment by jordan-wright** [comment] 2018-10-04 21:41
Hey @dsmurf,

Thanks for reaching out! This appears to be a duplicate of #152 which also covers unicode characters in CSV imports. I'm afraid we don't have a fix in place yet. Hopefully I'll have some time soon and can address it.

For now, to keep issues consolidated, I'm going to close this one out so we can track everything through #152.

Thanks again for getting in touch!

**Closed by jordan-wright** 2018-10-04 21:41 UTC
