### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by juniorzee** [gophish/gophish#1269] opened 2018-11-09 18:21 UTC
Please how do i set my gmail smtp? cause this is the feedback im getting at my send test email "dial tcp: lookup smtp.gmail.com: no such host or Max connection attempts exceeded - 534 5.7.14 Please log in via 5.7.14 your web browser and then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 v10-v6sm14000215wrq.4 - gsmtp". how do i solve this issue???????  and again how do i make my gophish a website????

**Comment by jordan-wright** [comment] 2018-11-10 03:43
Hi @juniorzee,

Thanks for reaching out. This appears to be a duplicate of #1260. I recommend following all the steps from that link (including solving the captcha). If, after following all those steps, you still encounter that error, please let us know on that issue and we can continue troubleshooting.

**Closed by jordan-wright** 2018-11-10 03:43 UTC

**Comment by juniorzee** [comment] 2018-11-10 08:36
now, how do i make my gophish a website? i dont want to host it locally
please

**Comment by juniorzee** [comment] 2018-11-10 22:00
how do i make my gophish a website? i dont want to host it locally

**Comment by jordan-wright** [comment] 2018-11-10 22:14
Hi @juniorzee,

We try to keep issues self-contained to a single problem. Since this is a separate request, please open a new issue and provide all the information in our issue template. This asks all the necessary information we need to be able to help troubleshoot effectively. Without that information, I'm afraid there isn't much we can do to help.

**Comment by juniorzee** [comment] 2018-11-11 18:01
What I'm trying to say is, I want to make my gophish a website and not host it locally cause hosting it locally, anytime I close my gophish.exe everything erase and I have to start all over again

**Comment by Frank4207** [comment] 2018-12-04 10:08
pls in need of SMTP for paypal

**Comment by bilaljavaidd** [comment] 2024-07-11 15:29
Max connection attempts exceeded - dial tcp: lookup smpt.gmail.com: no such host     what ca i do now ???
