### ISSUE TITLE
landing page 404 

### ISSUE THREAD

**Issue by phathutshedzo1993** [gophish/gophish#1230] opened 2018-10-10 09:20 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: i really need help , i am using windows 10 i want to start my gophish because i have try before can someone take me through a steps or i have to use coding to start my create my gophish , this is the ip address i am using 127.0.0.1:3333 and the phish server 0.0.0.0.:80 , i have try to create campaign but nothings is happening.  

What are you expecting to see happen? :i want to see the landing page open not 404 error 

What are you seeing happen?its showing me the error its not given me what i want to see the the landing page 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2018-10-10 18:02
Hi @phathutshedzo1993,

Thanks for reaching out. I'm afraid without significantly more information, we won't be able to help. Right now, all we're told is:

* You've tried creating a campaign
* It didn't work

That's not enough information for us to troubleshoot what's happening here. Please provide as much information as possible about what exact steps you've taken, how you're testing the landing page, etc.

Thanks!

**Comment by jordan-wright** [comment] 2018-10-15 22:03
I'm afraid this still isn't enough information to figure out the problem.

> what i want to know is when i send the email i am expecting to see the results of my campaign ,i only see the email sent but the other it does not show , ,and my url i am using 127.0.0.1

So I'm guessing that you're the only recipient of this campaign, right? Other people won't be able to reach the IP address 127.0.0.1 since that's only available on the local host. Assuming you're the only person trying to reach the URL (say, if this is a test campaign), then what does the email you receive look like? What does the link you click on look like? What do you see when you click the link?

Please provide **as much** information as possible (screenshots, template/landing page content, logs, etc.), or we simply won't be able to help. 🙁

**Comment by phathutshedzo1993** [comment] 2018-10-16 06:04
then what does the email you receive look like? 
![gophish](https://user-images.githubusercontent.com/40666686/46995237-1d8cff00-d118-11e8-8bee-730b46ba70cc.PNG)

 What does the link you click on look like?
![email temphate](https://user-images.githubusercontent.com/40666686/46995272-4a411680-d118-11e8-83c7-b7e7a275bdc8.PNG)
What do you see when you click the link?
![website 404](https://user-images.githubusercontent.com/40666686/46995287-5a58f600-d118-11e8-8572-bdc9e7b6fe9c.PNG)
 
the landing page is 

![landing page](https://user-images.githubusercontent.com/40666686/46995421-fedb3800-d118-11e8-9486-97501c0401b1.PNG)
the compagh look like the following 

![new compaigh](https://user-images.githubusercontent.com/40666686/46995466-31853080-d119-11e8-9f61-b1eafeb38792.PNG)

then another question that i have for you is how do i make my  URL to be reachable by others , i think if i have the URL that is reachable   by others my question will be answer.
i can send the email and i receive it but when i open the email on the results nothing will show that i have open my email

**Comment by securitygeneration** [comment] 2018-10-16 10:43
The problem is that you're putting 127.0.0.1 in the URL. That IP is not routable from your targets' computers (or rather it will always point their browser to _their own_ computer - which obviously won't have the page you're trying to serve them).

That field needs to contain the URL/domain you've set up and pointed to your GoPhish instance.

**Comment by phathutshedzo1993** [comment] 2018-10-16 12:13
security generation , do i have to create my own URL OR i can just take the one for any site i want to use

**Comment by securitygeneration** [comment] 2018-10-16 13:48
It has to be a URL for a domain that you control, and have pointed an A record to your GoPhish instance's public IP (assuming you're doing this over the internet).

e.g. www.myphishingdomain.com -> A record to -> 123.2.3.12 (your box)

**Comment by phathutshedzo1993** [comment] 2018-10-16 13:58
thanks i will do so

**Comment by jordan-wright** [comment] 2018-10-17 15:59
Thanks for the great discussion everyone!

@phathutshedzo1993, as mentioned by @securitygeneration and @S0larflare, the issue here seems to be networking-related, not Gophish related. In order to have your campaigns be reachable by people not on the same machine as Gophish, you'll need to use an IP address or domain name that resolves externally as your URL.

This is done in a variety of ways, the details of which fall outside of the support we can provide. You may find the guides in the ["Additional References"](https://docs.getgophish.com/user-guide/additional-references) section of our documentation to be helpful.

Since the issue here isn't a bug with Gophish, I'm going to go ahead and close this one out. Thanks again for getting in touch @phathutshedzo1993!

**Closed by jordan-wright** 2018-10-17 15:59 UTC
Labels: support

**Comment by Blackbear710** [comment] 2021-05-12 20:23
I'm having issues capturing data, is there a slack or?
