### ISSUE TITLE
Gophish question by creating landing page 

### ISSUE THREAD

**Issue by ARiITRrIX** [gophish/gophish#867] opened 2017-12-03 22:01 UTC
Hey guys i have a question about the gophish. I want to create a professional phishing page as http://jledlb.sicherheitsgruppe-onlinedurchgang-286384.gdn/542930/haTtWd7ESiXU1vZ/RfkHUQbT8hLW6cu/239262310834/kDLaq5ySKrABpMQ/ZOMI71CigFUNVoy/signin_assoc.handle.php?assoc_handle=jxJgvutBRrKaSOedwkMpZ0h1QFCm9i&openid_claim=yWoRzU1tCh5NXVcbuaLQ&identifier_select=LGpra7fOE6mYTwKRCZJv&pape_max=GU3Zslu9YrKax8zDLI1b6vQen2Bdfg

How do I create or configure my gophish so that it redirects?

I can only phish a page as an example I download the HTML code from PayPal Login and copy it into gophish and that's it. The data will be tapped and the victim will be redirected to what I set on Landing Page.

But I would like to phishen that my victim is forwarded to "subdirectories"

As an example: My victim visits paypalaccountverfication.localtunnel.me

NOW he / she gives her login data THEN ---> LOGIN-ANINMATION (PayPal Blue ring)

Its a fake animation for the victim to think it logs in.

But in reality she will be redirected where to enter her personal information and then her credit or bank information

How can I create a phishing site with gophish that suits my needs.

**Comment by jordan-wright** [comment] 2017-12-04 00:10
To be honest, I can't think of a single scenario where you would have a legitimate, non-malicious reason to phish someone's credit or bank information.

With Gophish support I try my best to help the community use Gophish in scenarios where they are either testing their own organization's exposure to phishing, or have a contract (and permission!) to test another organization's exposure to phishing - this is the only supported use case for Gophish. This is a blurry line when all I see is what's provided in a support request, but that line seems crossed here.

That said, I'm going to close this issue out as-is, since it's my opinion that Gophish isn't being used in the way it was intended.

**Closed by jordan-wright** 2017-12-04 00:10 UTC
