### ISSUE TITLE
Problem importing email templates

### ISSUE THREAD

**Issue by Tiym** [gophish/gophish#732] opened 2017-08-28 16:02 UTC
I created some email templates a while ago, but I'm no longer managing to import emails.

From gmail I select 'show original'.  I have tried copying and pasting into the Gophish and I have also downloaded, opened a text file and copied all into Gophish.  I get as far as seeing the email in the HTML editor, but then it refuses to save.
The following is in my Windows Powershell:
![image](https://user-images.githubusercontent.com/29777917/29781877-8ce30b16-8c12-11e7-9baa-26a3f080feb2.png)
Any thoughts?

**Comment by jordan-wright** [comment] 2017-08-28 16:18
Sounds like there's an instance of "{{" in your template somewhere, which Gophish would then see as a template variable, causing the error. You might check through the email and remove those instances.

Let me know if that helps solve the issue!

**Comment by Tiym** [comment] 2017-08-28 16:35
Thanks Jordan.
I've searched in Notepad for an instance of {{ and there isn't one.
When I try to create a new template the code I have imported at the previous attempt is still there.  I delete it then paste a fresh version.

**Comment by jordan-wright** [comment] 2017-08-28 23:19
It looks like the problem is related to that URL in the template. You might look around that area to see if there are any curly braces- something in there is being caught by Gophish as a template.

If you want to upload a copy of the template here, I could help troubleshoot.

**Comment by jordan-wright** [comment] 2017-08-29 04:27
By the way, as a side note, I fixed that issue where the imported email content wasn't being cleared out of the modal. It's fixed as of ac3fe6aeae6cc0638bab1ede646e70328d8a85b4

**Comment by Tiym** [comment] 2017-08-29 16:55
Thank you, Jordan, I really appreciate the support.
I've managed to create urgent templates manually.
I've just tried to import a couple of new emails and they saved successfully, not sure what the difference is, but, as you suggest, it looks as if it was something to do with the URL.

**Comment by themotu** [comment] 2017-08-29 17:37
A feature to parse a received email would be nice. Just hook gophish to pop or imap and then send it an email with the template being named after the subject.

**Comment by jordan-wright** [comment] 2017-08-29 17:52
Thanks for the suggestion!

To be honest, I'm worried that would be tricky, and probably wouldn't provide much more value than the existing import.

For example, which emails do we import? All of them? This would probably require setting up a dedicated email account for Gophish and then you'd still have to forward the emails over, which isn't much different than viewing the source and copy/pasting. Also we'd have to work out how to poll the mail server at a reasonable rate.

We'd also have to workout how to handle naming conflicts. And should deleting the email in Gophish (or the inbox) cause a deletion in the other? Etc.

For now, I'm probably going to keep the import how it is, but I think I actually have another issue open from a while back that we can use to track this in case there's time in the future to knock it out.

All that said, please keep the ideas coming! I appreciate you reaching out!

**Closed** 2017-09-02 20:44 UTC
