### ISSUE TITLE
Minimum MySQL version?

### ISSUE THREAD

**Issue by alecisec** [gophish/gophish#1530] opened 2019-08-06 02:29 UTC
Is there a minimum version of MySQL supported?
I've only been able to get gophish working on 5.7, 5.6 will always give errors 

ERROR 1071 (42000) at line 299: Specified key was too long; max key length is 767 bytes

when creating the database on first run

**Comment by jordan-wright** [comment] 2019-08-08 15:45
Hey @alecisec,

This appears to be a duplicate of #1336. I haven't had time to figure out a proper fix for MySQL version <= 5.6, so I recommend using 5.7 or higher for now.

Sorry for the hassle! Since we'll be tracking this through #1336 I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2019-08-08 15:45 UTC
