### ISSUE TITLE
Is it possible to check user url random code in campaigns or server

### ISSUE THREAD

**Issue by dickens88** [gophish/gophish#1240] opened 2018-10-18 10:27 UTC
After we create a campaign and send phishing mail to the users, they will receive a mail with phishing url, like ```http://demo.com/?rid=351d6xx ```.  The URL has a random code at last.

My question is, is it possible to check the relationship between user email account and these random codes in the server log or campaigns page?

**Comment by jordan-wright** [comment] 2018-10-18 15:13
Hi @dickens88,

Thanks for reaching out. It looks like this may be a duplicate of #1239 which talks about how to see the `rid` for a given recipient.

I'm planning on posting a change that shows this value in the results view, but for now you can use the "Export Results" feature to download a CSV that maps the result ID to the email.

Since this appears to be a duplicate, I'm going to close this one out in favor of #1239. Keep an eye out there for the upcoming fix 😄 

Thanks again for getting in touch!

**Closed by jordan-wright** 2018-10-18 15:13 UTC

**Comment by dickens88** [comment] 2018-10-19 00:33
Hi Jordan, Thank you so much for the reply, that's really helpful!
