### ISSUE TITLE
Tracker image not loading in email

### ISSUE THREAD

**Issue by arobertson523** [gophish/gophish#1227] opened 2018-10-08 16:10 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
When opening the email the tracker does not change status under "Email Opened." Until I click the link then both the "Email Opened" and the "Clicked Link" update. I am using outlook and know I have to download images but that has stopped working. I checked the email template and it has the {{.Tracker}} but the image isnt loading when i send the email. I have tried sending to both outlook and gmail. Either is updating the "Email Opened" status

What are you expecting to see happen? :
For the "Email Opened" tab to update when i download images.

What are you seeing happen?
The email sends and I open it but until i click the clinks to the landing page the status doesnt update.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional //EN">
<html>
<head>
	<title>Facebook</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">@media all and (max-width: 480px){*[class].ib_t{min-width:100% !important}*[class].ib_row{display:block !important}*[class].ib_ext{display:block !important;padding:10px 0 5px 0;vertical-align:top !important;width:100% !important}*[class].ib_img,*[class].ib_mid{vertical-align:top !important}*[class].mb_blk{display:block !important;padding-bottom:10px;width:100% !important}*[class].mb_hide{display:none !important}*[class].mb_inl{display:inline !important}*[class].d_mb_flex{display:block !important}}.d_mb_show{display:none}.d_mb_show_center{display:table;margin:auto}.d_mb_flex{display:flex}@media only screen and (max-device-width: 480px){.d_mb_hide{display:none !important}.d_mb_show{display:block !important}.d_mb_flex{display:block !important}}.mb_text h1,.mb_text h2,.mb_text h3,.mb_text h4,.mb_text h5,.mb_text h6{line-height:normal}.mb_work_text h1{font-size:18px;line-height:normal;margin-top:4px}.mb_work_text h2,.mb_work_text h3{font-size:16px;line-height:normal;margin-top:4px}.mb_work_text h4,.mb_work_text h5,.mb_work_text h6{font-size:14px;line-height:normal}.mb_work_text a{color:#1270e9}.mb_work_text p{margin-top:4px}
	</style>
</head>
<body bgcolor="#ffffff" style="margin:0;padding:0;">
<table align="center" border="0" cellpadding="0" cellspacing="0" id="email_table" style="border-collapse:collapse;">
	<tbody>
		<tr>
			<td id="email_content" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;background:#ffffff;">
			<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
				<tbody>
					<tr style="">
						<td colspan="3" height="20" style="line-height:20px;">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3" height="1" style="line-height:1px;"><span style="color:#FFFFFF;display:none !important;font-size:1px;">&nbsp; Hi Austin, It looks like you&#39;re having trouble logging into Facebook. Just click the button below and we&#39;ll log you in. &nbsp; Get&nbsp;Back&nbsp;on&nbsp;Facebook &nbsp; If you weren&#39;t trying to log in, let us know . &nbsp;</span></td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="">
									<td colspan="3" height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
								<tr>
									<td align="left" style="height:32;line-height:0px;" valign="middle" width="32"><img height="32" src="https://static.xx.fbcdn.net/rsrc.php/v3/yL/r/vd4aB0GIe9z.png" style="border:0;" width="32" /></td>
									<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
									<td style="" width="100%"><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:19px;line-height:32px;color:#3b5998;">Facebook</span></td>
								</tr>
								<tr style="border-bottom:solid 1px #e5e5e5;">
									<td colspan="3" height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="">
									<td height="28" style="line-height:28px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="">
									<p>&nbsp;</p>

									<p><span class="mb_text" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">Hi,</span></p>

									<p><span class="mb_text" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">It looks like you haven&#39;t&nbsp;logging into Facebook in a while. Just click the button below and we&#39;ll log you in.</span></p>

									<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
										<tbody>
											<tr style="">
												<td colspan="3" height="2" style="line-height:2px;"><span class="mb_text" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">&nbsp;</span></td>
											</tr>
											<tr>
												<td class="mb_blk" style="">
												<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
													<tbody>
														<tr>
															<td style="border-collapse:collapse;border-radius:2px;text-align:center;display:block;border:solid 1px #344c80;box-shadow:inset 0 1px 1px rgba(255, 255, 255, 0.1),0 1px 0 rgba(0, 0, 0, 0.1);background:#4c649b;padding:7px 16px 11px 16px;">
															<center><span class="mb_text" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;"><a href="{{.URL}}" style="color:#3b5998;text-decoration:none;display:block;"><font size="3"><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;white-space:nowrap;font-weight:bold;vertical-align:middle;color:#ffffff;text-shadow:0 -1px 0 #415686;font-size:14px;line-height:14px;">Get&nbsp;Back&nbsp;on&nbsp;Facebook</span></font></a></span></center>
															</td>
														</tr>
													</tbody>
												</table>
												</td>
												<td class="mb_hide" style="" width="100%">&nbsp;</td>
											</tr>
											<tr style="">
												<td colspan="3" height="32" style="line-height:32px;"><span class="mb_text" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">&nbsp;</span></td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
								<tr style="">
									<td height="14" style="line-height:14px;">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="border-top:solid 1px #e5e5e5;">
									<td height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:11px;color:#aaaaaa;line-height:16px;"><br />
									Facebook, Inc., Attention: Community Support, 1 Hacker Way, Menlo Park, CA 94025</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr style="">
						<td colspan="3" height="20" style="line-height:20px;">&nbsp;</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>

<p>{{.Tracker}}</p>
</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  
 * Step 2 -

**Comment by jordan-wright** [comment] 2018-10-08 17:17
Hi @arobertson523,

Thanks for reaching out!

The template looks fine to me, since I see the `{{.Tracker}}` listed. And, if clicking the link works, that tells me that the URL is set up correctly.

At this point, everything _seems_ to point to the issue being on the mail client's end, with no way to really fix that in Gophish. But, to confirm this is the case, I recommend taking a look at the content of the email you're receiving and manually copy/pasting the tracker URL into your browser and making sure that the event shows up in the dashboard. If you see the event show up, then the issue is definitely that the mail client isn't rendering the images.

As one last point, I try to recommend this anytime I see a branded template or landing page, but I see that you're using Facebook's brand within the template. I recommend against using their brand since it could hurt the user's trust in them Instead, you make simple modifications such as removing the logo and other branding to make things more generic. You will almost certainly see the same results in terms of click through rates, and you will avoid potentially infringing on their brand. You can find other tips on #1057.

I hope this helps!

**Comment by arobertson523** [comment] 2018-10-08 17:27
OK I will be sure to avoid facebook in the future. When I look at the source of the email it returned this is what I received for the tracking.

<img src=3D"<img alt=3D'' style=3D'display: none' src=3D' x.x.x.x:8=
080/track?rid=3DXG7Sddg'/>"/>

Where there the “x.x.x.x” is the ip, we also changed in the binary to use 8080 instead of port 80. Don’t know if this causes a problem but Im not sure what to do with this information or if this looks correct.

Austin Robertson

IT Support Specialist
City of Vandalia
[cid:image001.gif@01D21E1E.91BF6F20]

245 James E. Bohanan Drive
Vandalia, OH  45377

Office: 937-415-2369
Mobile: 937-470-5002

**Comment by klamontagne-om** [comment] 2018-10-08 18:39
I have also been having this issue, and manually accessing the /track URL doesn't trigger the "Email Opened" event

**Comment by jordan-wright** [comment] 2018-10-08 19:56
@arobertson523, in this case, manually enter the http://x.x.x.x:8080/track?rid=XG7Sddg URL into your browser and see if the email opened event shows up in the Gophish dashboard.

@klamontagne-om The "=3D" is a type of encoding used for emails called [quoted printable](https://en.wikipedia.org/wiki/Quoted-printable) encoding. In this case, the character code "3D" [corresponds](http://www.asciitable.com/) to the = sign. You can remove the "3D" and just keep the equals sign and it should work.

**Comment by arobertson523** [comment] 2018-10-08 20:08
I got a black screen and Im guessing since I got that and not a 404 page not found error that it is working the way it is supposed to and that it is Outlook/gmail and not gophish

**Comment by klamontagne-om** [comment] 2018-10-08 20:09
Yeah the black screen triggers the "Opened" status, but still wont trigger in either Gmail or ProtonMail

**Comment by arobertson523** [comment] 2018-10-08 20:14
Is there a setting that can be changed in outlook to trigger it

**Comment by jordan-wright** [comment] 2018-10-08 20:27
I'm afraid that supporting individual email clients is outside the scope of support we can provide, but perhaps something like [this](https://knowledgebase.constantcontact.com/articles/KnowledgeBase/5554-images-not-displaying-in-an-email-client?lang=en_US) might help? Many email clients are starting to move away from automatically loading images for privacy reasons, with not much we can do on the Gophish end to prevent it.

And for reference, the "black screen" is actually a 1x1 transparent pixel that's returned, which is typically called a "tracking pixel" in terms of tracking email opens.

@arobertson523, just to confirm, did triggering the tracking manually cause the "Email opened" event to fire in the Gophish dashboard?

**Comment by arobertson523** [comment] 2018-10-10 12:16
Yes, triggering the tracking manually cause the "Email opened" event to in Gophish. I will investigate the link you sent. Thank you

**Comment by jordan-wright** [comment] 2018-10-15 14:34
Going ahead and closing this for now since it appears the issue is indeed on the mail client's end. @arobertson523 if you continue to run into issues and it seems Gophish is the cause, let me know and we can always re-open this to continue troubleshooting 😄 

Thanks again for getting in touch!

**Closed by jordan-wright** 2018-10-15 14:34 UTC
Labels: support

**Comment by bheihn** [comment] 2019-02-12 22:57
I am having the same issue with outlook as well.  However, when I input the tracker directly into my browser it shows "This page isn’t working".  I know someone mentioned it earlier but not sure what the solution was.  http://x.x.x.x:3333/track?rid=p0yX8mx

**Comment by jotunel** [comment] 2021-06-21 23:55
Same issue. It works like a charm on protonmail, but gmail is not rendering the image, so it's not counting gmail's opened emails. I am not sure there is a way to know how many gmail users opened your phishing mail. Is there some sort of setting that seems to make this right? Thanks.

**Comment by crypt0n-root** [comment] 2021-12-25 18:01
Tracking image is not working. I send a test letter and in the source code of the letter there is, http: // xxxx: 3333 / track? Rid = xxxx and this does not trigger the "Message Open" event. Also, when I open the URL directly, I get - 404 Not Found. I tried it in other ways, without ports, with ports, without https, with https too, but it's no use. Help Please.
