### ISSUE TITLE
Go Phish loading loop at landing pages

### ISSUE THREAD

**Issue by mundifitimit22** [gophish/gophish#2596] opened 2022-09-12 12:35 UTC
Hello everyone,
I am trying to add my landing page on gophish, but when I click on landing pages it gets stuck at a loading loop. Also when I click "new pages" to add a landing page it won't save. Please help me fix this issue.

![Screenshot_2022-09-12_08_35_09](https://user-images.githubusercontent.com/112621282/189654967-fa31efc4-4dae-47fc-8b7c-f379ef13d67a.png)
![Screenshot_2022-09-12_08_32_16](https://user-images.githubusercontent.com/112621282/189654974-5f8531d6-8c80-4611-869e-e8313472dcb4.png)

**Comment by glennzw** [comment] 2022-09-12 13:35
Hi there - sorry you're having trouble. Could you hit F12 to view the browser console and see if there are any errors in there, and drop us a screenshot?

**Comment by mundifitimit22** [comment] 2022-09-13 07:02
> Hi there - sorry you're having trouble. Could you hit F12 to view the browser console and see if there are any errors in there, and drop us a screenshot?

Sure, Here are the errors:

![Screenshot_2022-09-13_03_01_27](https://user-images.githubusercontent.com/112621282/189832617-f8a80d37-91bd-40b7-9357-6ec4015de11f.png)
![Screenshot_2022-09-13_03_01_24](https://user-images.githubusercontent.com/112621282/189832622-daf030c4-8d31-4cf2-a5b2-b206e14812e5.png)
![Screenshot_2022-09-13_03_01_05](https://user-images.githubusercontent.com/112621282/189832625-d2f0b7b4-5adc-4634-a818-1ad1f96531a9.png)
![Screenshot_2022-09-13_03_01_00](https://user-images.githubusercontent.com/112621282/189832629-0dc54dcb-7ebd-4211-acfd-7946eafd5992.png)
![Screenshot_2022-09-13_03_00_57](https://user-images.githubusercontent.com/112621282/189832630-197823b5-30c0-4978-af48-b048d6fcb4ed.png)
![Screenshot_2022-09-13_03_00_53](https://user-images.githubusercontent.com/112621282/189832633-8f7b3322-fb9a-4741-a7a7-eecf33e16ec2.png)
![Screenshot_2022-09-13_03_00_44](https://user-images.githubusercontent.com/112621282/189832635-26a4bef4-7e33-4611-a5a9-0c5e3d89ac88.png)

**Comment by glennzw** [comment] 2022-09-13 12:24
So we can see the error there: `ckeditor was blocked due to MIME type ("text/plain")`

I'll try reproduce my side - which version of Firefox are you using? Any plugins in use? Looks like a bobble in the top right there.

Also can you make sure that file exists: https://10.11.11.3:3333/js/src/vendor/ckeditor.js

**Comment by mundifitimit22** [comment] 2022-09-13 14:44
Also I removed all the plugs on mozilla and still it's not working.

**Comment by mundifitimit22** [comment] 2022-09-14 07:53
Please help me someone

**Comment by glennzw** [comment] 2022-09-14 08:45
It works for me in Firefox. The error message is indicating that `ckeditor.js` is being served up as plaintext, which makes me think it's actually a 404 message. Could you try click load this in your browser to make sure it's actually loading the javascript:

https://10.11.11.3:3333/js/src/vendor/ckeditor/ckeditor.js

You can see here that when my browser loads it's served up as content type JS:

![Screenshot 2022-09-14 at 09 41 29](https://user-images.githubusercontent.com/3966613/190106776-ceccb51a-f790-482f-845b-9b9607670a50.png)

**Comment by mundifitimit22** [comment] 2022-09-14 09:19
Hello again. I opened the link that you sent me and I got a 404 error. I will attach a screenshot. Please tell me what can i do next to fix it.

![Screenshot_2022-09-14_05_19_39](https://user-images.githubusercontent.com/112621282/190114952-0790f3ba-1f03-4edf-89df-8dd8528706da.png)

**Comment by mundifitimit22** [comment] 2022-09-15 09:55
Please answer someone. I need help fixing this.

**Comment by glennzw** [comment] 2022-09-15 16:24
That's very strange, it seems you're missing a bunch of gophish files. How did you install it?

You could try re-downloading

**Comment by mundifitimit22** [comment] 2022-09-16 06:41
> That's very strange, it seems you're missing a bunch of gophish files. How did you install it?
> 
> You could try re-downloading

I installed it with "go command". is there anything I can do to fix it?

**Comment by Mr3Jane** [comment] 2022-09-16 08:22
@mundifitimit22 seems like you are serving only `dist` folder of the frontend, which is missing some of the files and `src` where ckeditor and some other libraries are isn't being server over http. If you want to fix your current setup, take a look which folder is being served for frontend, but I'd recommend to just run it in Docker.

**Comment by glennzw** [comment] 2022-09-27 19:48
OK so I think I've figured out what's going on here. When `go get` became deprecated we moved to `go install` - but there's an issue using `go install` with folders called `vendor` as this is a reserved word - so the vendor folder with all the Javascript for rendering charts and editing HTML don't get downloaded (see discussion here https://github.com/golang/go/issues/48332).

The only solution I can think of for now is rather than using `go install` use `git clone https://github.com/gophish/gophish.git`

Alternatively download the precompiled binary.

**Comment by labanana34** [comment] 2022-12-20 08:31
Hello there !

Thanks @glennzw for the tips.
I download the project with `git clone https://github.com/gophish` and then copy the git-clone vendor directory in my working directory.

`cp -R /path/to/gitclone/static/js/src/vendor/ ~/go/pkg/mod/github.com/gophish/gophish@v0.12.1/static/js/src/`

`~/go/pkg/mod/github.com/gophish/gophish@v0.12.1` is the default folder I have by installing with `go install github.com/gophish/gophish@latest`
Check the owner of the folder and file to be sure.

Then I'm able to make an email template, no more endless load.

Best regards,
LaBanana

**Comment by glennzw** [comment] 2022-12-20 10:50
Great I'm glad that worked @labanana34! 

I'm going to close this issue out.

**Closed by glennzw** 2022-12-20 10:50 UTC
