### ISSUE TITLE
Gophish - Report setting - Outlook error

### ISSUE THREAD

**Issue by Shreyasinha1995** [gophish/gophish#1858] opened 2020-06-04 10:51 UTC
Hi,

I am facing the issue in Gophish for Monitor an IMAP account for emails reported by users

Accounting setting<Reporting setting.

When i enter the detail of IMAP host: outlook.office365.com and port 993 it is giving me the error 'Unable to login to outlook.office365.com' and in more info 'imap: unexpected completion status ("EKXCH2 NO LOGIN failed.")'

Can some one help me to resolve the query

**Comment by jordan-wright** [comment] 2020-06-04 13:04
Closing as a duplicate of #1857.

**Closed by jordan-wright** 2020-06-04 13:04 UTC
