### ISSUE TITLE
Unable to reach Gophish listener

### ISSUE THREAD

**Issue by phathutshedzo1993** [gophish/gophish#1250] opened 2018-10-26 11:24 UTC
afternoon
i wanted to ask if you have an office number so i can call and ask about go phish , i have try all but nothing is giving me what i want

**Comment by jordan-wright** [comment] 2018-10-26 12:08
Hi there! I’m afraid we only offer support through Github Issues so that the community can work together to help troubleshoot.

I encourage you to submit an issue here if you continue to run into problem. The key to creating an issue that makes it possible for people to help is to provide as much detail about what you’re doing, what you’re trying to do, and what’s happening instead. There’s no such thing as too much information here. With that in hand, I’m sure we can figure out what’s going on.

I hope this helps!

**Comment by phathutshedzo1993** [comment] 2018-10-26 12:12
hi jordan 
i understand  what you are are saying , i have been running go phish for 6 months but i ma not getting the results on a dashboard , my go phish is sending email and i can open that email but nothing will show on the dashboard the results that i am using , how to i connect or run my go phish to the internet if i should ask

**Comment by jordan-wright** [comment] 2018-10-27 02:01
@phathutshedzo1993,

This seems to be a duplicate of #1230, in which we explained that putting the URL as 127.0.0.1 won't work, since recipients won't be able to reach that IP address. That's a networking concept, not something with Gophish.

Also, as @S0larflare mentioned in https://github.com/gophish/gophish/issues/1230#issuecomment-430258913, having https:// as the URL scheme likely won't work unless you have HTTPS setup on your phishing server (it's unclear if that's the case since we don't know what your config.json looks like). You would need to use http://external_ip_address instead.

@S0larflare is also correct that in your first screenshot, you have the link pointing to Amazon instead of your Gophish server. As we [mention in the documentation](https://docs.getgophish.com/user-guide/documentation/campaigns), this URL needs to:

* Point to your Gophish phishing server
* Be reachable by all recipients

I hope this helps. If you continue to run into issues setting up the networking, I would recommend considering a free third-party managed phishing simulation product. Gophish isn't for everyone, and these third-parties have the benefit of managing everything for you, at the cost of some flexibility. One I can highly recommend is [Duo Insight](https://insight.duo.com/).

**Comment by phathutshedzo1993** [comment] 2018-10-27 16:50
Hi Jordan I know gophish is not for everyone like us may be we are discriminated to use it , but we wanted to use it for the whole university of Johannesburg just to do a campaign but if its not for us in south Africa I understand and I will leave is it is thanks very much Jordan it was an understanding one and I understand.............. Gophish isn't for everyone.thanks I just wanted to create something my self but if you can not help me its fine

**Comment by phathutshedzo1993** [comment] 2018-10-27 16:59
, this URL needs to:

Point to your Gophish phishing server
Be reachable by all recipients
I have a valid URL in the cumpas in which I can use o that when I use it it does not show me good results ,.... Can you give me a config I must use for that

**Comment by phathutshedzo1993** [comment] 2018-10-27 17:14
We need help with config please example i will do and learn please

**Comment by phathutshedzo1993** [comment] 2018-10-27 19:09
I was saying that because it did not make me feel like a person that's why I was saying that you could have been telling me to try rather that discourage me , its not we I believe that in  IT its all about trying and get this better , what you said to me discarage me to work under IT thanks for your opinion and you creation thanks again it was nice knowing Gophish even when I did not get through

**Comment by jordan-wright** [comment] 2018-10-27 19:46
I apologize if I said anything that came off as harsh. My goal is to be respectful to everyone, while being realistic about the support we can provide. If there are specific instances where that line was crossed, please let me know and I'll take it as feedback to do better next time (this offer, of course, extends to everyone in this community). If you'd prefer to discuss this in private, you can reach me at hi@getgophish.com.

Thanks again for getting in touch, and I do hope that you find a solution that works for you. In the future, if you have any questions specific to Gophish, don't hesitate to open an issue and we can troubleshoot.

**Closed by jordan-wright** 2018-10-27 19:46 UTC
Labels: support

**Comment by Blackbear710** [comment] 2021-05-12 20:26
I also am having issues here.   How do I setup the Gophish listener correctly? 

as soon as I add anything into URL Campaign,   it sends Error (Status)
