### ISSUE TITLE
GoPhish in Red Hat 6

### ISSUE THREAD

**Issue by mrpaulo99** [gophish/gophish#546] opened 2017-02-23 19:36 UTC
I have already test Gophish in Debian. Now I'm trying to execute it in Red Hat 6 and have the following error:

./gophish: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./gophish)

I have GLIBC version 2.12-1.132.el6,

How can I solve this dependency? Thanks

**Comment by jordan-wright** [comment] 2017-02-24 05:40
This appears to be a duplicate of https://github.com/gophish/gophish/issues/375. My recommendation would be to either find a way to update glibc, or to download and [compile gophish from source](https://gophish.gitbooks.io/user-guide/content/installation.html#installing-gophish-from-source) using your version of glibc, which appears to work according to the other issue.

I hope this helps! Sorry for the trouble! We try to support as many OS's out of the box, but it's pretty tricky to catch all the edge cases.

**Closed by jordan-wright** 2017-02-24 05:40 UTC
