### ISSUE TITLE
host gophish locally 

### ISSUE THREAD

**Issue by Denzel-Washington** [gophish/gophish#1369] opened 2019-02-20 09:25 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
Possible to host locally without a vps? currently installed on my linux machine and have port forward my ip in my router. so i can access from outside using the external ip: ex: 60.x.x.x
have started gophish server can login internally but can view from external ip. error:404 page not found"

What are you expecting to see happen? :
to be able to view/access landing page ..

What are you seeing happen?
error:404 page not found"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2019-02-24 03:08
Hi @Denzel-Washington,

Thanks for reaching out! It's possible to host Gophish anywhere as long as networking is setup such that the people who are clicking the links in the emails can reach your Gophish server.

If you're seeing the 404 error, things should be working. This is the default response Gophish provides if no `rid` is specified.

Since things appear to be working as intended, I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2019-02-24 03:08 UTC
