### ISSUE TITLE
Issue in change of status 

### ISSUE THREAD

**Issue by Shamya** [gophish/gophish#144] opened 2016-02-12 06:44 UTC
I have launched a campaign and the mails are successfully sent. Even when the mails are opened and the link is clicked, the status still remains as "email sent". What could be amiss ?

**Comment by jordan-wright** [comment] 2016-02-12 12:30
It sounds like one of three things is happening:

* You aren't including the ```{{.URL}}``` template var as the href in a link in the email, as well as including a tracking image using ```{{.Tracker}}``` (or the checkbox in the UI)
* The URL you are including in your campaign does not point to your "phish_server" configuration (default is the gophish host on TCP port 80)
* The targets you are sending emails to cannot reach your server on port 80 - perhaps due to firewall restrictions.

I hope this helps!

**Comment by dhruvin917** [comment] 2016-02-12 15:45
So I have a similar issue. The status is updated within the campaign results but not in the dashboard view. I have included the {{.Tracker}} and the user is redirected to the landing page. WIthin the detailed view of the results it does say "Success" for each status but in the dashboard view it still says "Email Sent"

**Comment by jordan-wright** [comment] 2016-02-12 18:04
So in the dashboard (the main gophish homepage), you see "Emails Sent"? That's expected behavior. The main dashboard is a view over all campaigns, so the campaign status is "Emails Sent", meaning all the emails have been sent.

The campaign results view on the other hand will show you the results per user.

I hope that clears things up! I'll give this issue till tomorrow to hear from @Shamya and if we don't hear anything, or if the info helped, we'll close it out.

**Comment by Shamya** [comment] 2016-02-13 11:39
Comments on your suggestions. Kindly see if anything is missing - 
1) This is my Email template (includes tracker and url):
 ```
<html>
<head>
	<title></title>
</head>
<body>
<p><a href="http://127.0.0.1:3333">http://127.0.0.1:3333</a></p>

<p>{{.Tracker}}</p>

<p><a href="{{.URL}}">{{.URL}}</a></p>

</body>
</html>
```
2) URL in campaign - http://127.0.0.1:3333 (opens Gophish dashboard locally)
3) I am sending the mail to my personal account for now and opening it within my machine when the server is up and the URL is accessible.

**Comment by jordan-wright** [comment] 2016-02-13 16:30
Hi @Shamya - I think there might be some confusion on what each URL does.

So, the admin server (port 3333) is only used for admin purposes. When gophish starts up, there is a separate server called the "phish server" that you should point your targets to. This server listens on port 80.

The reason we let you specify a URL in the campaign modal is in case your server is externally available via a domain name (foo.bar.com, for example).

So, I would start by finding the IP address of your server that clients can connect to, and using x.x.x.x:80 as the URL in the campaign. You can find an example of this in the [user guide](https://getgophish.com/documentation/Gophish%20User%20Guide.pdf): 

> Next, we need to set the URL that the users will be directed to. This need to be the IP address of the gophish host (and port!) that is reachable by the users. This means that if you are only targeting internal users, you would probably be fine using the host’s internal IP address. However, if your targets are coming in externally, you will need to setup gophish to be reachable externally and set this field to be the external (public) IP address.

> It is important to note that you can also use a domain name if the domain resolves to the correct IP
address for the gophish listener!

See if that fixes the issue, and let me know if you run into any other problems! :smile:

**Comment by jordan-wright** [comment] 2016-02-13 17:29
To provide a bit more detail, you can try to use this template:

Note: You don't have to wrap the ```{{.Tracker}}``` in tags if you don't want to. I also removed your other URL.. you can put it back in the template if you wanted it there.

```
<html>
<head>
    <title></title>
</head>
<body>
<p><a href="{{.URL}}">{{.URL}}</a></p>
{{.Tracker}}
</body>
</html>
```

**Comment by Shamya** [comment] 2016-02-13 20:20
@jordan-wright : Thank you ! This makes things clearer. I was able to launch a successful campaign. So the status turned to success. But the transition didn't go through "Email Opened" even with ``` {{.Tacker}} ``` in the email template. I did wait before clicking the URL in the mail to see this transition. Any troubleshooting steps for this ?

**Comment by jordan-wright** [comment] 2016-02-13 20:22
Ensure that your mail client supports displaying images. The tracker works by inserting an image with a unique id, and many mail clients can block images by default.

**Comment by Shamya** [comment] 2016-02-13 21:01
I am testing with gmail and I have "Images from this sender are always displayed" option set for these mails. I still don't see a "email opened status" and the image is still a "?".

**Comment by jordan-wright** [comment] 2016-02-13 22:16
What do you mean when you say the image is still a "?"

Can you provide the (redacted as necessary) source of the email? You can use the "Show Original" option in gmail to get this:

![image](https://cloud.githubusercontent.com/assets/1317288/13030354/1d4eb63e-d26d-11e5-8d82-0fb5a88d7048.png)

**Comment by Shamya** [comment] 2016-02-14 01:04
let me know if this helps -
```                                                                                                                                                                                                                                                           
Delivered-To: 
Received: by 10.107.19.224 with SMTP id ;
        Sat, 13 Feb 2016 12:51:25 -0800 (PST)
X-Received: by 10.140.250.213 with SMTP id ;
        Sat, 13 Feb 2016 12:51:25 -0800 (PST)
Return-Path: <isenbergtest@gmail.com>
Received: from mail-qg0-x230.google.com (mail-qg0-x230.google.com. [2607:f8b0:400d:c04::230])
        by mx.google.com with ESMTPS id 
        for <>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 13 Feb 2016 12:51:25 -0800 (PST)
Received-SPF: pass (google.com: domain of isenbergtest@gmail.com designates 2607:f8b0:400d:c04::230 as permitted sender) client-ip=2607:f8b0:400d:c04::230;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of isenbergtest@gmail.com designates 2607:f8b0:400d:c04::230 as permitted sender) smtp.mailfrom=isenbergtest@gmail.com;
       dkim=pass header.i=@gmail.com;
       dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-qg0-x230.google.com with SMTP id 
        for <>; Sat, 13 Feb 2016 12:51:25 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:mime-version:content-type:to:subject:message-id:from;
        bh=WKAqIe8HdrQvRk3bazBkm0Yyxa6GE4k16j40q79EPZo=;
        b=imfbAFgj+5WoCuERo7V0cdM8uBrfqftdibmg2M/IibxarBFT2f5Z6/DzHK2/gFWeaf
         UvjGLWogwjh+R5ICn4zPVpZ0vjMHKH2NXTvUUMbDG5YeU8ebGh5qmhvRqtDkv3FgNCmH
         rjrcbphTHsjFGuCL4vfjm7D/Un6l3FPrV+nmHHRdl195GebsQ1ElQbNNQ30LRIqX9cbT
         tO16dcVZPRQCwzzYYZQ1Fonl1Dfh1CZiANNjvTnv0K8muyjVCQtLu7BJ7NLDIV9v/6fx
         lQdnE15ADfOO/6jYWGF+6scV0crE2oI7VhgmnvlN/oxI4Ga1CHau0rvfAR/KqFkBJ46W
         AAaw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:date:mime-version:content-type:to:subject
         :message-id:from;
        bh=WKAqIe8HdrQvRk3bazBkm0Yyxa6GE4k16j40q79EPZo=;
        b=U5eAxnHCBRpuBj1oKVfbOE27JusOlNduDnXQhEobhUuC2BloEkUuAviWHMz7Du/rGv
         3Cm6f6knedZyELHgYsatSYZOLLJ4Cy2qv/XMvH4o6N3WqDdJY2HqYOW4IPayaBu0WK53
         n9whnc/ZuMLUiXvjWPbbS0sOfOA42U8kvyU4Y6KK7Z/LHmBPR2UyQhHC+mlLDB49J0PV
         1mTfing13wqhGrxvU+En/U5kiB45/lhwntKunm34UnFckvDRctdtyYP2crIlwMvfJAnl
         uY1gGHn9+2Uf4WoHQ7Vkoy9G6UwRZzRTmh1zaYe8KyTIPGCQEfNS4wHyPbh21s+v0CPn
         oNWQ==
X-Gm-Message-State: AG10YOTSQDOH6TvQNlPF2MK8eY9ztPkO4a9Ng4eijX4PtgCTlnqsuO8vsUe3qBA41kLW+g==
X-Received: by 10.140.38.47 with SMTP id ;
        Sat, 13 Feb 2016 12:51:25 -0800 (PST)
Return-Path: <isenbergtest@gmail.com>
Received: from localhost ([2601:186:8100:438e:6daa:fdcc:f240:1822])
        by smtp.gmail.com with ESMTPSA id f76sm381579qhe.14.2016.02.13.12.51.24
        for <>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 13 Feb 2016 12:51:24 -0800 (PST)
Date: Sat, 13 Feb 2016 15:51:23 -0500
Mime-Version: 1.0
Content-Type: multipart/mixed;
 boundary=795ed21a07fbb63301847714b958f5ee2d6ca4a1ee7761d27a8e3dfb24c1
To: <>
Subject: test
Message-Id: <1455396683814976083.21066.1234020951393371971@MacBook-Pro.local>
From: isenbergtest@gmail.com

--795ed21a07fbb63301847714b958f5ee2d6ca4a1ee7761d27a8e3dfb24c1
Content-Type: multipart/alternative;
 boundary=9cfcc9d337ad2b274b0e9308db03892485b31e92ceff615de948b09ab36e

--9cfcc9d337ad2b274b0e9308db03892485b31e92ceff615de948b09ab36e
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

http://127.0.0.1:3333

--9cfcc9d337ad2b274b0e9308db03892485b31e92ceff615de948b09ab36e
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html>
<head>
    <title></title>
</head>
<body>
<p><a href=3D"http://192.168.1.111?rid=3Df83d3c6025fabf60506d2e6de70e80ee86=
ac84980fc6e9645764b3e8f03b09a8">http://192.168.1.111?rid=3Df83d3c6025fabf60=
506d2e6de70e80ee86ac84980fc6e9645764b3e8f03b09a8</a></p>
<img src=3D'http://192.168.1.111/track?rid=3Df83d3c6025fabf60506d2e6de70e80=
ee86ac84980fc6e9645764b3e8f03b09a8'/>
</body>
</html>
--9cfcc9d337ad2b274b0e9308db03892485b31e92ceff615de948b09ab36e--

--795ed21a07fbb63301847714b958f5ee2d6ca4a1ee7761d27a8e3dfb24c1--
```

**Comment by jordan-wright** [comment] 2016-02-14 01:10
Everything looks fine. The tracker is created and inserted into the email. If you can successfully click the link that points to 192.168.1.111, then the tracking image will also work unless there is an issue with Gmail.

In this case, I'm afraid there isn't much more we can do to troubleshoot since, if anything, this would be an issue on the gmail side. You can watch the gophish logs in the terminal when you open the email to make sure that you see the image being loaded up. You can also use Chrome's developer tools to see if you see the image requests going out of your browser.

However, all that is dependent on your gmail configuration.

**Comment by Shamya** [comment] 2016-02-14 01:49
Thanks Jordan ! When you said "If you can successfully click the link that points to 192.168.1.111, then the tracking image will also work unless there is an issue with Gmail." - Did you mean that the "email opened" status comes up only if the receiver **clicks** on the link ?

**Comment by jordan-wright** [comment] 2016-02-14 02:43
No, if the email client loads images, a request will be made for the tracking image, firing the event.

**Comment by Shamya** [comment] 2016-02-14 02:45
OK. On a side note, before we close this issue - Do we have a copy campaign option right now ? or an option to save the SMTP info ?

**Comment by jordan-wright** [comment] 2016-02-14 02:51
Unfortunately no and no :) 

However, the SMTP one is an open issue, and I'm planning on a clone or "relaunch" campaign.

Thanks for the suggestions!

**Closed** 2016-02-14 14:43 UTC
Labels: question
