### ISSUE TITLE
Ignore Certificates

### ISSUE THREAD

**Issue by brianhaugli** [gophish/gophish#132] opened 2016-02-05 15:58 UTC
Have gophish ignore certificates used internally.  I get the following errors:

! certificate signed by unknown authority

**Comment by jordan-wright** [comment] 2016-02-05 17:06
Hi Brian,

This is a known issue that will be fixed in 0.1.2. I'll close this as a duplicate of #77.

Thanks for the report!

**Closed** 2016-02-07 02:35 UTC

**Comment by jordan-wright** [comment] 2016-02-13 20:33
@brianhaugli Just a heads up, this has been fixed via 0a7bfcf664b7aa70015d44932c9b4806756b3d76

**Comment by brianhaugli** [comment] 2016-02-13 20:58
Very cool.  I'll give it shot on Monday.

Regards,

Brian Haugli

It begins with the most simple belief, the one you must have in yourself.
That must be translated into results by dedication. The knowledge that
dedication, which feeds on belief, can make it so.
