### ISSUE TITLE
Can i able to upgrade the gophish with vesion 0.6 to 0.7.1 without loosing the completed results?

### ISSUE THREAD

**Issue by KrishanKanagarajah** [gophish/gophish#1237] opened 2018-10-16 05:10 UTC
Hi Jordan, 

Trust you are good. I am currently running version 0.6 on AWS. On our recent test, we have noticed that gophish have sent emails twice to each user. Therefore the next simulation, I want to try with the latest version (0.7.1) without removing/ losing the old test results.

Thanks, heaps in advance for your help.

Krishan

**Comment by dsmurf** [comment] 2018-10-16 08:58
Hi #KrishanKanagarajah.
I have done numerous test with just that.
I even made a script that does all for me. you Take a backup of you running gophish then update and then copy gophish.db from backup to updated running.

**Comment by S0larflare** [comment] 2018-10-16 14:20
You will have to add the line in your config.json for your contact address at the bottom. Make sure you also put a comma at the end of the migrations_prefix line...I forgot to and was confused by the error message for a couple of minutes.

**Comment by jordan-wright** [comment] 2018-10-17 15:51
It's odd that the `contact_address` line is being reported as required, since that's definitely not the intention. You should get a warning if it's empty, but Gophish should still start up just fine 🤔 

But, since this issue concerns updating Gophish and great advice has been provided, I'm going to go ahead and close this out.

Thanks for the great responses, everyone!

**Closed by jordan-wright** 2018-10-17 15:51 UTC

**Comment by S0larflare** [comment] 2018-10-17 19:18
Jordan,I believe the problem is that if the config.json file doesn’t have the contact address line at all, the startup fails. So if you are upgrading from a previous version, you have to ensure that the line is added, even if the address itself is blank

Sent from my iPhone

On 17 Oct 2018, at 16:51, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1237<https://github.com/gophish/gophish/issues/1237>.
