### ISSUE TITLE
Attachment Tracking & Open Rate

### ISSUE THREAD

**Issue by mirkatson** [gophish/gophish#1176] opened 2018-08-23 02:25 UTC
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.6

Brief description of the issue: 
Tracking which user has downloaded the attachment (e.g word doc/pdf)

What are you expecting to see happen? :
Expecting to see which user has downloaded the attachment and opened it.

Or is it possible to include a individual tracking code (user's ID) in the document, so when the user opens it, it will generate a callback to the GoPhish server. From there, we are able to extract the callback URL in the log file and correlate it with the user's ID.
 
Thanks!

**Comment by jordan-wright** [comment] 2018-08-24 22:21
Hi @mirkatson,

Thanks for reaching out! As you've seen, we have issues #513 and #227 for tracking attachment support. We don't have an ETA at the moment, since we're actively working on other issues.

Since this appears to be a duplicate of those issues, I'm going to go ahead and close this one out so we can track everything through the existing issues.

Thanks again for getting in touch!

**Closed by jordan-wright** 2018-08-24 22:21 UTC

**Comment by blshkv** [comment] 2021-11-01 23:50
FYI, there is also https://github.com/onvio/gophish/commits/master. You might want to merge both if onvio fork has done something better
