### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by migmultisync** [gophish/gophish#786] opened 2017-10-05 14:39 UTC
Hello,

I have very little programming experience and I'm having difficulty getting Gophish installed. I've read through the user manual but I still can't get it working. Here's what I've completed:
Downloaded the 64x Windows version
Extracted to my Desktop

Can anyone help me out?

**Comment by CoreyMcCown13** [comment] 2017-10-05 16:00
There isn't really an installation process. Open the extracted folder on your desktop and run the gophish.exe file. You can edit the config.json file to meet your needs. There is no programming needed. You'll probably want to know some basic HTML for the landing pages and email templates.

**Comment by migmultisync** [comment] 2017-10-05 17:26
I thought that's how it would work but when I open the exe, a box flashes on the screen and closes itself. I assumed there was something I was missing.

**Comment by S0larflare** [comment] 2017-10-05 17:28
Try opening a cmd window and run it from there

Sent from my iPhone

On 5 Oct 2017, at 18:26, migmultisync <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought that's how it would work but when I open the exe, a box flashes on the screen and closes itself. I assumed there was something I was missing.

**Comment by CoreyMcCown13** [comment] 2017-10-05 17:29
Like @S0larflare said, try in command prompt.

1. Open a command prompt (cmd.exe)
2. Navigate to your gophish folder ( cd C:\Users\username\Desktop\gophish-v0.4-windows-64bit )
3. Type gophish.exe - this will execute the binary from within the command prompt and give you some output.

**Comment by migmultisync** [comment] 2017-10-05 17:55
Got a little further
![image](https://user-images.githubusercontent.com/32546633/31242358-cc63a356-a9d4-11e7-970d-a2613445909b.png)

**Comment by jordan-wright** [comment] 2017-10-06 01:08
@migmultisync At this point I recommend referring to these issues which are directly related to what you're encountering: https://github.com/gophish/gophish/search?q=an+attempt+was+made&type=Issues&utf8=%E2%9C%93

These issues should help answer your question. Hope this helps!

Since at this point this is now a duplicate of these other 10 or so issues, I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2017-10-06 01:08 UTC
