### ISSUE TITLE
NGINX Reverse Proxy Config

### ISSUE THREAD

**Issue by littlejob** [gophish/gophish#1885] opened 2020-07-02 12:31 UTC
What version of Gophish are you using?: Latest - running in docker 
Brief description of the issue: Gophish listener does not like https redirection  
What are you expecting to see happen? : https redirection to defined gophish listener 

Having some issues with NGINX routing traffic correctly, was curious if anyone can shed some light on a few pain points.

- I have NGINX running in a docker container
- Handling HTTPS redirection like a charm
- Config files stored : /etc/nginx/conf.d/
- I have websites config (which is a GoPhish instance) below

```
server{
listen 80;
server_name yourwebsitename.com www.yourwebsitename.com;    location / {
    proxy_pass http://172.17.0.2:80;}
}
```

Also have the default config present in the same directory

```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```
When I generate a campaign via GoPhish the URL's are generated, however the URL's do not route correctly. I am routed to the default nginx welcome page for each request, compared to the GoPhish listener on port 80.

Thinking the default config was the issue, I removed it. Then I would get a bad gateway error.. Has anyone been successful in implementing this with a reverse proxy?

**Comment by edermi** [comment] 2020-07-02 14:54
For me this minimal example works fine:

~~~
server {
  listen 80;
  listen 443 ssl;

  server_name <domain>;

  location / {
      proxy_pass http://localhost:8000/;
  }

  ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem; 
  ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
  
}
~~~

Make sure to adapt domain name, certificate locations and port. For the gophish admin interface, just use another subdomain and forward the requests to the backend on the appropriate port.

**Comment by littlejob** [comment] 2020-07-02 17:02
> For me this minimal example works fine:
> 
> ```
> server {
>   listen 80;
>   listen 443 ssl;
> 
>   server_name <domain>;
> 
>   location / {
>       proxy_pass http://localhost:8000/;
>   }
> 
>   ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem; 
>   ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
>   
> }
> ```
> 
> Make sure to adapt domain name, certificate locations and port. For the gophish admin interface, just use another subdomain and forward the requests to the backend on the appropriate port.

What does your config.json file look like for gophish. I assume based on your config, the listening port is 8000 compared to the default 80? 

`{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
`

**Comment by edermi** [comment] 2020-07-03 07:54
Can you show your default nginx config? Where are you accessing the site from?

You need to set the hostname of your site in the server_name parameter, otherwise the configuration block will not be used when you access the site. Also, you may need the `/` in the end of the URL of the proxy_pass directive.

I'm using a fairly standard config file, just the ports changed and all interfaces bound to localhost (127.0.0.1).

**Comment by littlejob** [comment] 2020-07-07 18:53
> Can you show your default nginx config? Where are you accessing the site from?
> 
> You need to set the hostname of your site in the server_name parameter, otherwise the configuration block will not be used when you access the site. Also, you may need the `/` at the end of the URL of the proxy_pass directive.
> 
> I'm using a fairly standard config file, just the ports changed and all interfaces bound to localhost (127.0.0.1).

sure - 
`server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
	
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}`

**Comment by edermi** [comment] 2020-07-07 19:03
Did you include your config?

**Comment by littlejob** [comment] 2020-07-07 20:05
> Did you include your config?

the default config and my sites config is in my very first post. Obviously the _yourwebsitename.com_ is a placeholder for the domains name.

**Comment by edermi** [comment] 2020-07-07 21:56
It's not about the placeholder. Did you include the configuration file describing your configuration in the nginx main configuration?
http://nginx.org/en/docs/ngx_core_module.html#include

It is really difficult to help you as you do not post *complete* configuration files. So, please post all of your nginx config (not just snippets). You may redact domain names, but if you're not familiar with nginx you should not omit config lines because you think they are not relevant. Also, please tell us which operating system and version you are running on and which errors are thrown by nginx (if any). Where are the configuration files placed? You can check your config with `nginx -t`and `journalctl -b -u nginx` brings up the nginx logs since your last boot if you are using the systemd service. 

I can tell you that running gophish behind nginx should not be too difficult (I'm running several instances this way) and your configuration is probably messed up at some other point.

**Comment by littlejob** [comment] 2020-07-08 11:57
My intent was not to leave key information excluded from my reply. Maybe I am misunderstanding what specifically you are requesting. I shall be more specific as I am not omitting anything. 

/etc/nginx/nginx.conf
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

I have two config files in the /etc/nginx/conf.d/ directory: 
default.conf
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
	
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

domain.conf
```
server{
    server_name domain.com;
    location / {
        proxy_pass http://172.17.0.2:80/;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server{
    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name domain.com;
    return 404; # managed by Certbot

}
```

Running Ubuntu 19.10. 

Self tests pass
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
I appreciate your help.

**Comment by edermi** [comment] 2020-07-09 11:24
Do you access the page via https or http?
To me your config looks quite weird, but I'm coming from Debian and I am used to their conventions, so this is probably personal preference.

At first glance, I don't see anything that looks wrong. I'd successively remove stuff that should not be needed (e.g. the default server for localhost) as well as the letsencrypt stuff (you have your certificate already?) because I made the experience that the certbot changes sometimes break the intended behavior. Once your setup works as intended, you can take care of fixing LE.

I'd suggest the following to start:

~~~
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
}
~~~

~~~
server {
    server_name domain.com;
    location / {
        proxy_pass http://172.17.0.2:80/;
    }
    listen 80;
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; 
    # include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot # not sure if we need them, I'd try the first run without them

}
~~~

default.conf should not be required, so you can delete the symlink or move the file somewhere else. If this works, you only need to take care of the automatic 301 redirect to https (I'd go without the if solution, just a vHost listening on 80 and doing the redirect) and letsencrypt. Here, I can recommend you to use the webroot authenticator instead of the nginx modules but this is also, again, my personal preference.

**Comment by littlejob** [comment] 2020-07-09 11:55
> Do you access the page via https or http?
> To me your config looks quite weird, but I'm coming from Debian and I am used to their conventions, so this is probably personal preference.
> 
> At first glance, I don't see anything that looks wrong. I'd successively remove stuff that should not be needed (e.g. the default server for localhost) as well as the letsencrypt stuff (you have your certificate already?) because I made the experience that the certbot changes sometimes break the intended behavior. Once your setup works as intended, you can take care of fixing LE.
> 

I do have the lets encrypt certs already - generated by certbot. I have followed your above recommendations, removed the default config file and modified my domains config. 

- admin portal is still accessible 
- https re-direct is still working - valid certs 
- when I create a new campaign, generated URL's result in a _500 Internal Server Error_
- I have tried with and without the _include /etc/letsencrypt/options-ssl-nginx.conf_

I attempted a few campaigns specifying slightly different URL's to see if that was the issue:
- http://domain.com
- https://domain.com 
- also the above with an appended "/"

all to no prevail.. suggestions?

**Comment by edermi** [comment] 2020-07-09 12:08
> I do have the lets encrypt certs already - generated by certbot. I have followed your above recommendations, removed the default config file and modified my domains config.
> 
> * admin portal is still accessible

This doesn't run over nginx, right? 

> * https re-direct is still working - valid certs

I guess this is cached by your browser, in private mode there should be no redirect anymore

> * when I create a new campaign, generated URL's result in a _500 Internal Server Error_

Is this server error thrown by nginx or gophish? Either way, there should be a log entry in the error log of nginx/gophish.

**Comment by littlejob** [comment] 2020-07-09 12:41
> > * when I create a new campaign, generated URL's result in a _500 Internal Server Error_
> 
> Is this server error thrown by nginx or gophish? Either way, there should be a log entry in the error log of nginx/gophish.

- I do not see any logs in the nginx side: /var/log/nginx/error.log or /var/log/nginx/access.log 
- when i change the gophish listener to listen on port 443, i see a gophish cookie is dropped when I browse the phish link, but i still receive the 500 http response code 
- if i change the listener back to 80,  cookie is no longer present/given (all tests performed in private windows - no cache)
- also enabled logging on the gophish instance.. probably should have done that from the beginning... but with the listener set to 80, request does not even get to the gophish instance, so there is no log. tested admin page to insure nginx logging was working.. it is..

**Comment by edermi** [comment] 2020-07-09 13:13
> > > * when I create a new campaign, generated URL's result in a _500 Internal Server Error_
> > 
> > 
> > Is this server error thrown by nginx or gophish? Either way, there should be a log entry in the error log of nginx/gophish.
> 
> * I do not see any logs in the nginx side: /var/log/nginx/error.log or /var/log/nginx/access.log - and i feel like i should see something..

Yes, I agree. This is weird.

> * when i change the gophish listener to listen on port 443, i see a gophish cookie is dropped when I browse the phish link, but i still receive the 500 http response code

This sounds like the requests go through

> * if i change the listener back to 80,  cookie is no longer present/given (all tests performed in private windows - no cache)

This is weird?

> * also enabled logging on the gophish instance.. probably should have done that from the beginning... but with the listener set to 80, request does not even get to the gophish instance, so there is no log. tested admin page to insure nginx logging was working.. it is..

OK this becomes really weird and I have honestly no idea what's going on. I run GoPhish along nginx on Debian 10 with nginx and certbot from the official repositories and this works really well, provided the configuration above. Usually you do not have to rewrite stuff or provide fancy options, just pass the HTTP requests through.

Maybe somebody else knows what's wrong, but I have no clue, sorry.

**Comment by littlejob** [comment] 2020-07-09 13:40
> OK this becomes really weird and I have honestly no idea what's going on. I run GoPhish along nginx on Debian 10 with nginx and certbot from the official repositories and this works really well, provided the configuration above. Usually you do not have to rewrite stuff or provide fancy options, just pass the HTTP requests through.
> 
> Maybe somebody else knows what's wrong, but I have no clue, sorry.

Have you tried running this configuration in docker? A separate container for both nginx and gophish?

**Comment by edermi** [comment] 2020-07-09 14:23
No, as Docker adds complexity I want to avoid. I don't see the point in using Docker for a web server that is packaged alongside the distribution and a single-binary application listening on a local port. I am sorry I can't help you with the Docker issue.

**Comment by jordan-wright** [comment] 2020-07-25 04:07
I'm going to go ahead and close this one out since there haven't been any updates in over 2 weeks and this isn't really an issue with Gophish itself. I hope you were able to find a resolution to this @littlejob! Everywhere that I've seen suggests a standard nginx reverse proxy config should be sufficient for passing traffic back to Gophish.

**Closed by jordan-wright** 2020-07-25 04:07 UTC
