### ISSUE TITLE
UI reporting wrong information - database inconsistency with UI

### ISSUE THREAD

**Issue by franckyz0r** [gophish/gophish#1552] opened 2019-08-22 06:25 UTC
What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
GUI information are not updating properly
What are you expecting to see happen?:
Number of emails sent and other information update near real-time
What are you seeing happen?
I've sent 3420 emails and in UI it sais only 321. 
In `mail_logs` DB there is no entry with my campaign id.
In `events` DB for campaign id 121 I have 3420 unique `email sent` entries and only 321 in UI.
In `events` DB for campaign id 121 I have 581 unique `clicked link` entries and only 180 in UI.
In `events` DB for campaign id 121 I have 99 unique `submitted data` entries and only 38 in UI.
In `events` DB for campaign id 121 I have 91 unique `reported` entries and only 58 in UI.
I've checked some of the trgets and in UI here is what I have - inconsistency:
![image](https://user-images.githubusercontent.com/8490591/63490324-17e11200-c4bd-11e9-90c2-f57fc6e3d96e.png)
or
![image](https://user-images.githubusercontent.com/8490591/63491752-b753d400-c4c0-11e9-91cf-256f23dc75f0.png)

I was watching the load of the server while emails were sent - nothing unusual, pretty low.
Also I was watching the logs after I started the campaign and emails were scheduled and sent without errors.

Could this be a database limitation? Too many queries?
Is there anything else I can check to see what happened?
Can I trust the values in DB to write some reports?
Is there anything I can do to refresh the UI to show up the information from DB?

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Start a campaign with 3k+ targets
 * Step 2 - Observe logs while emails are sent (no errors)
 * Step 3 - Observe results

**Comment by jordan-wright** [comment] 2019-08-24 01:46
HI there!

Thanks so much for reaching out and taking the time to give this detailed information. I'm sorry you're encountering these issues. This is definitely not expected behavior.

First and foremost - the database should be your source of truth. There's always a risk (though, I would hope a small one) that there is logic on the frontend causing incorrect values to be displayed, so I would always trust the DB more than the frontend.

If you're still seeing inconsistencies after doing a refresh on the page, then I would lean towards some kind of error in the frontend. If you open your browser's developer tools, do you see any errors in the console?

Additionally, if you look in the network inspector in the developer tools, you will see a request made to the `/summary` endpoint. If you view the response received, do those numbers look correct? My goal here is to verify that the API itself is giving you correct data, since that will confirm it's a frontend issue.

**Comment by franckyz0r** [comment] 2019-08-26 06:26
Hello,

So I checked the developer tools:

- when I load `Campaigns` tab there is no error in console
- when I load the detailed campaign page:
![image](https://user-images.githubusercontent.com/8490591/63669453-b5e91b00-c7e2-11e9-8b86-7742d1234500.png)
- when I load `Campaigns` tab and check the request made to the `/summary` endpoint the numbers of my campaign doesn't seem right:

> {
      "id": 121,
      "created_date": "2019-08-21T10:00:18.627077189Z",
      "launch_date": "2019-08-21T09:59:00Z",
      "send_by_date": "0001-01-01T00:00:00Z",
      "completed_date": "0001-01-01T00:00:00Z",
      "status": "In progress",
      "name": "Campaign name",
      "stats": {
        "total": 3420,
        "sent": 359,
        "opened": 224,
        "clicked": 224,
        "submitted_data": 49,
        "email_reported": 62,
        "error": 0
 }

If you need more information in debugging this, let me know.

**Comment by franckyz0r** [comment] 2019-08-26 06:35
Seems to be the same thing as #1065

**Comment by jordan-wright** [comment] 2019-12-06 02:44
Hey there!

I've merged 44f8840, which I anticipate fixes this issue. There are a couple of other PR's I hope to get merged in, then I'll cut a new release and you can take it for a spin 😄

Sorry again for all the hassle! Hopefully this makes things work like a charm.

**Closed by jordan-wright** 2019-12-06 02:44 UTC
Labels: support
