### ISSUE TITLE
Making a fake Google log-in page.

### ISSUE THREAD

**Issue by Guguano** [gophish/gophish#569] opened 2017-03-22 19:12 UTC
I'm trying to make a fake Google log-in page. When I import the URL of the page. When I go to the fake one and put in an email, it simply clears the text field and says to put in an email again. I noticed that on the real page, after you put in your email and it changes to the password box, the end of the URL changes from #identifier to #password. But importing either one doesn't change anything. How do I make it redirect to the password box after you input an email? Thanks!

**Comment by S0larflare** [comment] 2017-03-22 20:44
The #identifier and #password parts are still the same page, they are just variables which tell the page what to show at a certain point. To do this you'd have to alter the page and do a bit of custom scripting.

Personally, I altered a google login to just have a static email/password form rather than messing with anything fancy.

**Comment by Guguano** [comment] 2017-03-22 21:41
Ah, okay. I suck at HTML, I don't suppose you still have your custom page
you could share? Lol
-- 


Jesse Burdick-Pless

**Comment by S0larflare** [comment] 2017-03-22 21:53
I should be able to, won't have a chance until Friday though

Sent from my iPhone

On 22 Mar 2017, at 21:42, Guguano <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah, okay. I suck at HTML, I don't suppose you still have your custom page
you could share? Lol
--


Jesse Burdick-Pless

**Comment by jordan-wright** [comment] 2017-03-22 23:10
I'd ask that we please don't share brand-infringing landing pages through this forum.

Totally understand if you're doing this type of campaign for your own organization - I can't stop you. But, I don't want to see gophish taken down because we have potentially copyrighted html hosted in the repo in any form.

**Comment by jordan-wright** [comment] 2017-03-24 03:29
Going ahead and closing this one out for now since it looks like the root cause was identified.

@Guguano - as @S0larflare mentioned, you can just add the static `<input>` elements to have the data you need and you should be good to go. 😄

**Closed by jordan-wright** 2017-03-24 03:29 UTC
