### ISSUE TITLE
email reporting error:  "imap: unexpected completion status ... The specified charset is not supported"

### ISSUE THREAD

**Issue by ldunzweiler** [gophish/gophish#1748] opened 2020-02-07 13:41 UTC
What version of Gophish are you using?:
Gophish-v0.9 on linux
IMAP Email on Exchange 2016

Brief description of the issue:
In 'Reporting Settings' I put in all the details, left advanced settings alone. I click 'Test Settings' and get a nice big green checkmark. 

So what is the end user supposed to do to get a successful report? In my testing I have tried forwarding, replying (with the To address changed) and sending as attachment to the configured imap account. Gophish dashboard is not reporting a successful report.

**Comment by glennzw** [comment] 2020-02-07 16:52
Hi there! The reporting feature is new so it's great to hear you're using it, and your feedback will help us make it better.

The user should forward the email to the specified account. Gophish periodically checks in, and if the email is a campaign marks it as reported. If you keep an eye on the logs you should see information outlining this behaviour.

If you manually log into the email account can you see that the email has been marked as read? Also, make sure you forward inline, not as an attachment.

**Comment by ldunzweiler** [comment] 2020-02-07 17:09
Sry, I should know a little better to include logs. 

So on the email server all I see in the imap logs is a successful login every 30secs as expected. 

However in gophish.err log I see this every 30sec.

```
time="2020-02-07T12:06:09-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"BDLHV5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"
time="2020-02-07T12:06:39-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"OCLHG5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"
time="2020-02-07T12:07:10-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"FEUJT5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"
```

**Comment by S0larflare** [comment] 2020-02-07 17:43
From the looks of that error it seems like whatever the imap client using to parse the messages is failing to do so due to the charset used. It’s probably something that will need to be handled with an update. I’m not sure what is used to parse the emails off the top of my head though

Sent from my iPhone

On 7 Feb 2020, at 17:09, ldunzweiler <notifications@github.com> wrote:

﻿

Sry, I should know a little better to include logs.

So on the email server all I see in the imap logs is a successful login every 30secs as expected.

However in gophish.err log I see this every 30sec.

time="2020-02-07T12:06:09-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"BDLHV5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"
time="2020-02-07T12:06:39-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"OCLHG5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"
time="2020-02-07T12:07:10-05:00" level=error msg="uid search failed: imap: unexpected completion status (\"FEUJT5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"

**Comment by glennzw** [comment] 2020-02-07 21:01
Thanks for the logs. So it's failing in the findEmails() function here:

https://github.com/gophish/gophish/blob/master/imap/imap.go#L215

Doing some Googling it seems like it's a Microsoft Exchange issue. The BADCHARSET response-code provides a list of supported charsets, not the charset that is invalid. The charset that is invalid is the charset used in the UIDSearch() command (which I assume is UTF-8).

The server you're using doesn't support any charset other than US-ASCII, and presumably the search happening here for new messages is non-US-ASCII.

What is your environment? I'll try reproduce it on my side. Otherwise you could try reconfiguring your mail server to UTF-8.

**Comment by glennzw** [comment] 2020-02-07 21:05
Also, the library I'm using for IMAP is very old, and hasn't been updated in six years. I should maybe swap out to something newer, like https://github.com/emersion/go-imap

**Comment by ldunzweiler** [comment] 2020-02-10 19:02
Our environment is Exchange 2016.  The Exchange Admin and I have spent the morning searching for and  been unable to find anything on how and where to change to allow the server too accept UTF-8 beyond a domain name.

**Comment by ldunzweiler** [comment] 2020-02-10 20:12
What imap sever will work?  Will Yahoo or a linux host with Postfix work?

Expectedly I get the same error when I test an Outlook account as above.  I can login but when I run a test campaign I get the same charset is not supported. 
When I try Gmail after I enable IMAP and "allow sign-in from less secure apps" I get this when I test my IMAP configuration settings.

`imap: unexpected completion status ("STBGR2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)")`

**Comment by wshi4440** [comment] 2020-02-11 18:18
Do you need to import the Exchange IMAP Server's cert to your gophish server?  I have a similar gophish set up, but I was unable to get a successful connection from "Test Settings".  The error message in log says "tls: first record does not look like a TLS handshake".

I am using TLS for IMAP.

What version of Gophish are you using?:
Gophish-v0.9 on Windows 10
IMAP Email on Exchange 2016

**Comment by ldunzweiler** [comment] 2020-02-11 22:21
IMAP port is 143
IMAPS port is 993

If I have "Use TLS:" checked when using port 143 I get that exact error.  You using port 993?

**Comment by ldunzweiler** [comment] 2020-02-11 22:22
> Do you need to import the Exchange IMAP Server's cert to your gophish server? I have a similar gophish set up, but I was unable to get a successful connection from "Test Settings". The error message in log says "tls: first record does not look like a TLS handshake".
> 
> I am using TLS for IMAP.
> 
> What version of Gophish are you using?:
> Gophish-v0.9 on Windows 10
> IMAP Email on Exchange 2016

IMAP port is 143
IMAPS port is 993

If I have "Use TLS:" checked when using port 143 I get that exact error. You using port 993?

**Comment by ldunzweiler** [comment] 2020-02-11 22:26
Changed the title to better reflect the issue. 

Previously was "how is email reporting supposed to work?"

**Comment by wshi4440** [comment] 2020-02-11 22:33
My port is 687.

Did you have to import the Exchange IMAP Server's cert to your gophish server to get your TLS connection working?

**Comment by glennzw** [comment] 2020-02-11 22:35
Thanks for your patience with this @ldunzweiler. I've only tested the IMAP reporting on GMail and my own IMAP servers; so I'm not sure how Exchange handles things.

Are there exchange servers I could connect to, or just sign up for an Outlook.com email address to try replicate your environment? I'd be pressed for time to setup a whole Exchange server.

As for your error `imap: unexpected completion status ("STBGR2 NO [ALERT] Please log in via your web` - I got this too, and signed in via the web link and authorised the 'less secure' app. It seems you've done this, but GMail works fine for me.

I'm quite busy with my day job at the moment but will try figure this out ASAP.

**Comment by ldunzweiler** [comment] 2020-02-11 22:54
@wshi4440 if you aren't the email admin I'd verify that 687 is the IMAPS port. That is the same error I get using our non-IMAPS port. To me it would appear that the port is incorrect. 

@glennzw  Thanks for looking into it.  Wonder what is up with gmail in my test.  If it works for you, and it appears yahoo works, I will bang there and see what happens. 

The error I got on Exchange I got with my outlook account so maybe could test Outlook in lieu of Exchange? Maybe Azure would have a free trail that allows access to Exchange?

**Comment by jordan-wright** [comment] 2020-02-12 05:48
With Gmail, I use the following settings:

Host: imap.gmail.com
Port: 993
Use TLS: true

I also turned on "Less secure app access" to allow connections via IMAP.

**Comment by glennzw** [comment] 2020-02-13 10:28
I'm struggling to reproduce this. I signed up for an Outlook.com account and that works fine:

![Screenshot 2020-02-13 at 10 27 55](https://user-images.githubusercontent.com/3966613/74425424-935bc480-4e4b-11ea-93a8-876f23477207.png)

**Comment by glennzw** [comment] 2020-02-13 10:42
Actually you pointed out you get the Big Green Tick, but then get failure in the logs. I can confirm I'm seeing the same in my logs:

time="2020-02-13T10:40:19Z" level=error msg="uid search failed: imap: unexpected completion status (\"NHGVU5 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.\")"

It makes sense as the Green Tick only checks if we can login successfully, the error comes from searching for email.

Working on this now, will keep you posted.

**Comment by glennzw** [comment] 2020-02-13 11:37
Update;

To login to IMAP servers I borrowed code from https://github.com/jprobinson/eazye. In turn, `eazye` uses https://github.com/mxk/go-imap. I found the point of failure in `mxk/go-imap`:

```
// UIDSearch is identical to Search, but the numbers returned in the response
// are unique identifiers instead of message sequence numbers.
func (c *Client) UIDSearch(spec ...Field) (cmd *Command, err error) {
	return c.Send("UID SEARCH", append([]Field{"CHARSET", "UTF-8"}, spec...)...)
}
```
https://github.com/mxk/go-imap/blob/master/imap/imap.go#L377

Here the CHARSET is set to UTF-8. I changed this to `US-ASCII` et voila, gophish is able to check for new email on Outlook.com. Interestingly, I'm still able to check email on GMail too.

Doing some more digging it looks like the other popular IMAP library, `github.com/emersion/go-imap`, bumped into the same issue some years ago: https://github.com/emersion/go-imap/issues/48

Their [solution](https://github.com/emersion/go-imap/pull/50/files) was to fall back to US-ASCII if BADCHARSET is received.

For the short term I'll work on implementing the same solution into `github.com/mxk/go-imap`, and in the medium term update gophish to use the newer `emersion/go-imap`

If you want to get this working now, just update [the line](https://github.com/mxk/go-imap/blob/master/imap/imap.go#L377
) I mentioned above from "UTF-8" to "US-ASCII" and recompile your gophish.

**Comment by glennzw** [comment] 2020-02-13 17:27
I spent the better part of today learning more about IMAP than I've ever wanted to know.

I tried various elegant fallback solutions (automatically try UTF-8 and fallback to US-ASCII) but the easier solution in the end was to remove the hardcoded UTF-8 charset from the `mxk/go-imap` library. This allows users to manually specify the encoding, if they wish, by including it in part of the []imap.Field slice.

Anyway, If you update `gophish/imap/imap.go` to import `github.com/glennzw/go-imap/imap` rather than `github.com/mxk/go-imap/imap` you'll be good to go.

I submitted a pull request to `mxk/go-imap`, but I don't think the project is being maintained.

@jordan-wright I know you're not a fan of importing untrusted code. Would you like me to submit a pull request to point to my fork, or leave as is until I can get around to updating to a newer imap library?

**Comment by jordan-wright** [comment] 2020-02-15 19:43
Let's leave as-is until we can get around to updating the IMAP library, since that's the long-term solution. We can even fork `emersion/go-imap` if needed to give us added flexibility.

When I get a chance, I'll make a branch for this and see about giving you write access to it @glennzw.

Thanks for the great discussion!

**Comment by asriznet** [comment] 2020-03-11 05:32
Hi,

We are just setting up a phishing campaign and setting up email reporting however running into an issue with adding an O365 account for IMAP configuration.

Ran into this thread thought to check if there's any workaround to getting this fixed without rebuilding from source?

test using gmail seems fine but not using Office365 account.

**Comment by asriznet** [comment] 2020-03-12 04:40
We're just finishing the setup of our phishing campaign and had some issues getting user-report information. as checked on logs, it matches the bug reported here as we use O365 for the IMAP reporting account.

Is there a quick workaround to this?

`time="2020-03-12T04:06:38Z" level=error msg="uid search failed: imap: unexpected completion status (\"MSHLT5 NO [BADCHARSET (US-ASCII)] The specified charset$`

**Comment by glennzw** [comment] 2020-03-15 10:49
Hi @asriznet - for now you'll need to make a small code change and recompile:

### Option 1:
Pull down the Gophish source, and then edit the file `github.com/mxk/go-imap/imap/imap.go` as I've done here:

https://github.com/mxk/go-imap/pull/30/files#

### Option 2:
Update `gophish/imap/imap.go` to import `github.com/glennzw/go-imap/imap` rather than `github.com/mxk/go-imap/imap` you'll be good to go.

Unfortunately it seems the mxk/go-imap project is not being maintained so my pull request is unlikely to go through. When I find some time I'm going to migrate to a more modern IMAP library.

**Comment by asriznet** [comment] 2020-03-15 19:53
> Hi @asriznet - for now you'll need to make a small code change and recompile:
> 
> ### Option 1:
> Pull down the Gophish source, and then edit the file `github.com/mxk/go-imap/imap/imap.go` as I've done here:
> 
> https://github.com/mxk/go-imap/pull/30/files#
> 
> ### Option 2:
> Update `gophish/imap/imap.go` to import `github.com/glennzw/go-imap/imap` rather than `github.com/mxk/go-imap/imap` you'll be good to go.
> 
> Unfortunately it seems the mxk/go-imap project is not being maintained so my pull request is unlikely to go through. When I find some time I'm going to migrate to a more modern IMAP library.

Thanks @glennzw , Option 2 did not seem to work for me so went with Option 1.
I can see that it's able to read the emails in the IMAP account but it's still not showing as reported, wondering if i'm missing anything.

![Screenshot 2020-03-16 at 3 47 10 AM](https://user-images.githubusercontent.com/11292398/76709398-59772a00-6739-11ea-8f82-96b54563ca73.png)

I saw the emails changed from unread to read status automatically but not detected as a report in the campaign dashboard.

the only thing i see in logs are TLS handshake errors:

> time="2020-03-15T19:39:22Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:21 +0000] \"POST /api/campaigns/ HTTP/2.0\" 201 15112 \"https://10.1.10.61:3333/campaigns\" \"Mozilla/5.0 (Macintosh; Intel $
time="2020-03-15T19:39:22Z" level=info msg="Email sent" email="\"John Doe\" <john.doe@contoso.com>"
time="2020-03-15T19:39:23Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:23 +0000] \"GET /campaigns/33 HTTP/2.0\" 200 2111 \"https://10.1.10.61:3333/campaigns\" \"Mozilla/5.0 (Macintosh; Intel Mac $
time="2020-03-15T19:39:23Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:23 +0000] \"GET /js/dist/app/campaign_results.min.js HTTP/2.0\" 200 5063 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/$
time="2020-03-15T19:39:23Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:23 +0000] \"GET /css/dist/gophish.css HTTP/2.0\" 200 52473 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/5.0 (Macintosh$
time="2020-03-15T19:39:23Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:23 +0000] \"GET /api/campaigns/33/results?{} HTTP/2.0\" 200 823 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/5.0 (Maci$
time="2020-03-15T19:39:38Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:38 +0000] \"GET /track?rid=RHmZw2K HTTP/1.1\" 200 95 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.$
time="2020-03-15T19:39:45Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:45 +0000] \"GET /track?rid=RHmZw2K HTTP/1.1\" 200 95 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X) Outlook/0.0.0\""
time="2020-03-15T19:39:51Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:51 +0000] \"GET /track?rid=RHmZw2K HTTP/1.1\" 200 95 \"\" \"Mozilla/4.0 (compatible; ms-office; MSOffice 16)\""
2020/03/15 19:39:57 http: TLS handshake error from 172.16.20.3:59049: remote error: tls: unknown certificate
time="2020-03-15T19:39:57Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:57 +0000] \"GET /api/campaigns/33/results?{} HTTP/2.0\" 200 576 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/5.0 (Maci$
time="2020-03-15T19:39:59Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:39:59 +0000] \"GET /api/campaigns/33/results?{} HTTP/2.0\" 200 576 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/5.0 (Maci$
time="2020-03-15T19:40:02Z" level=info msg="172.16.20.3 - - [15/Mar/2020:19:40:02 +0000] \"GET /api/campaigns/33/results?{} HTTP/2.0\" 200 576 \"https://10.1.10.61:3333/campaigns/33\" \"Mozilla/5.0 (Maci$

**Comment by glennzw** [comment] 2020-03-16 13:29
Hmm if they're being marked as read then it would seem it's parsing them. Could you share the email source here? The IMAP monitor searches for the text `?rid=xxxxxxx` in the email text with the regex:

```
var goPhishRegex = regexp.MustCompile("(\\?rid=[A-Za-z0-9]{7})")
rid := goPhishRegex.FindString(body)
```

Also, I see you've ticked the 'Delete campaign emails' box, so if they're still in your inbox (marked as read) that would suggest to me it couldn't find the rid parameter, and doesn't think they're campaign emails.

**Comment by glennzw** [comment] 2020-03-16 13:35
Another thought; are you forwarding inline or as an attachment? We currently only support inline. See https://github.com/gophish/gophish/issues/1782

**Comment by asriznet** [comment] 2020-03-16 15:00
> Another thought; are you forwarding inline or as an attachment? We currently only support inline. See #1782

Hi @glennzw , tests was done inline forwarding as I saw your comment above that this feature does not support reporting via attachment.

Below is a portion of the email source that contain the hyperlink:

`<p align=3D"center" style=3D"text-align:center"><span style=3D"font-family:&quot;=
Arial&quot;,sans-serif;color:black"><a href=3D"http://10.1.10.61?rid=3DRHmZw2K">=
<span style=3D"color:white;text-transform:uppercase">Update Your Account Crede=
ntials&nbsp;</span></a></span><o:p></o:p></p>`

I'm not sure why outlook for mac is returning "=" then going to next line but this is exactly what I get when I view source from Outlook for mac, don't have other options to view source for now.

![Screenshot 2020-03-16 at 10 58 51 PM](https://user-images.githubusercontent.com/11292398/76771118-d063ff80-67d9-11ea-9c1a-510976b7aeb5.png)


Attached is the HTML source code for the email template used for the campaign
[gophish-emailtemplate.txt](https://github.com/gophish/gophish/files/4338746/gophish-emailtemplate.txt)

**Comment by glennzw** [comment] 2020-03-16 15:48
Hmm, I think we have a problem with encoding. I notice your rid values have '3D' at the front, relating to 'Quoted Printable', as do all values in your template. 

So you'll notice that your URL value is `http://10.1.10.61?rid=3DRHmZw2K` <-- note the '3D' at the start is not part of the actual rid parameter if you check it in your campaign, e.g mine below:

![Screenshot 2020-03-16 at 15 41 30](https://user-images.githubusercontent.com/3966613/76775106-c8399f00-679c-11ea-90a1-72dfbb75ba28.png)

Encoding '=' in QP is '=3D', which is why we're getting this. To be honest I'm not sure why though, and if it's a sending issue or an IMAP receiving issue. I'm doing some Googling now, but thought I'd update you in case you have any email-fu insight.

**Comment by asriznet** [comment] 2020-03-16 17:32
Ah, I didn't notice that at all.

So i checked the source of the campaign email on the target receiving end and noticed the same pattern. so i'm assuming that it started from the campaign email sent out from gophish to the target?

Do I need to edit the HTML template for my campaign email or is does that not help at all?
I used the {{.URL}} tag for the URL as per documentation.

`<a href="{{.URL}}" style="color:blue; text-decoration:underline"><span style="color:white"><span style="text-transform:uppercase">Update Your Account Credentials&nbsp;</span></span></a>`

for sending profile, we installed postfix on the gophish server and configured it with anonymous relay.
![Screenshot 2020-03-17 at 1 30 02 AM](https://user-images.githubusercontent.com/11292398/76784590-e03a0e80-67ee-11ea-97a0-2c4f4fef0fca.png)

**Comment by glennzw** [comment] 2020-03-16 17:33
I've added quoted-printable decoding support in this fork: 

https://github.com/glennzw/gophish/tree/fix-qp

I've tested it against your `gophish-emailtemplate.txt` and it works. Could you take it for spin please @asriznet and if all looks good I'll send in a pull request.

**Comment by asriznet** [comment] 2020-03-16 18:11
> I've added quoted-printable decoding support in this fork:
> 
> https://github.com/glennzw/gophish/tree/fix-qp
> 
> I've tested it against your `gophish-emailtemplate.txt` and it works. Could you take it for spin please @asriznet and if all looks good I'll send in a pull request.

Hi @glennzw , I've made the changes(https://github.com/asriznet/gophish/commit/0a149ba8fd951fdd3c818268aa00970cb5041406) and rebuilt from source however getting same results.

**Source of email received in IMAP account**
`<a href=3D"http://10.1.10.61?rid=3DpVKwkpL">=
<span style=3D"color:white;text-transform:uppercase">Update Your Account Crede=
ntials&nbsp;</span></a>`

**Result ID: pVKwkpL**

will it have any difference if we're using postfix installed on the gophish server as sending profile? We're not using O365 for SMTP as we would like separate gophish from operations and keep it within testing environment also it's easier to monitor emails coming in from a static address.

**Comment by glennzw** [comment] 2020-03-16 18:24
So in the email source you'll still see the quoted-printable 3D characters, just internally gophish will check the headers and decode if qp. If your gophish logs are set to info you should see output of either:

Good:
`time="2020-03-16T17:17:23Z" level=info msg="User 'Test <test@mail.com>' reported email with rid OeQlYf3"`

or

Bad:
```
time="2020-03-16T15:34:00Z" level=info msg="User 'Test <test@mail.com>' reported email with rid 3DOeQlY"
time="2020-03-16T15:34:00Z" level=error msg="Error reporting GoPhish email with rid 3DOeQlY: record not found"
```

**Comment by spadgezilla** [comment] 2020-07-08 14:48
> Hi @asriznet - for now you'll need to make a small code change and recompile:
> 
> ### Option 1:
> Pull down the Gophish source, and then edit the file `github.com/mxk/go-imap/imap/imap.go` as I've done here:
> 
> https://github.com/mxk/go-imap/pull/30/files#
> 
> ### Option 2:
> Update `gophish/imap/imap.go` to import `github.com/glennzw/go-imap/imap` rather than `github.com/mxk/go-imap/imap` you'll be good to go.
> 
> Unfortunately it seems the mxk/go-imap project is not being maintained so my pull request is unlikely to go through. When I find some time I'm going to migrate to a more modern IMAP library.

Hi, It looks as though v0.10.1 is using the emersion imap library now but I still get the 'BADCHARSET' error. I also see this in the console despite getting the green tick when testing the login:
![image](https://user-images.githubusercontent.com/7251456/86933370-61b50400-c132-11ea-9d2f-40e1755dc4ad.png)

My environment is linux with v0.10.1 and I'm using an Office365 mailbox.

**Comment by glennzw** [comment] 2020-07-08 18:28
Hi @spadgezilla - thanks for getting in touch.

What IMAP settings are you using? Is Office365 mailbox different to Outlook.com mail account? I'll try reproduce on my side.

**Comment by ldunzweiler** [comment] 2020-07-08 21:32
@glennzw I am still having the same issue.  Get the successful login but badcharset error. 
CentOS 8
gophish 0.10.1
local Exchange 2016 on IMAPS

**Comment by glennzw** [comment] 2020-07-09 06:55
@ldunzweiler Is there any chance you could set up a dummy account for me on your server and email / DM the details to me?

**Comment by spadgezilla** [comment] 2020-07-09 07:29
Hi @glennzw - my IMAP settings are below

Host: outlook.office365.com
Port: 993
TLS: yes

I've tried configuring this with an outlook.com and gmail.com account, outlook doesn't work and encounters the same error, gmail works absolutely fine.

**Comment by asriznet** [comment] 2020-07-09 07:32
> @ldunzweiler Is there any chance you could set up a dummy account for me on your server and email / DM the details to me?

Microsoft offers 1 month free trial if you wish to test it: https://www.microsoft.com/en-us/microsoft-365/microsoft-365-business-standard-one-month-trial

Just have to spend about 30mins to setup the new O365 tenant before you can start testing the Mail functions.

Unfortunately our organization have quite strict policy on account creations with MFA for all user accounts.

**Comment by glennzw** [comment] 2020-07-09 09:01
@spadgezilla 
@asriznet 

Aha, I think I've found the problem! I assume you're grabbing gophish from https://github.com/gophish/gophish/releases ? The releases here don't include the latest IMAP updates. You'll need to download and compile source from https://github.com/gophish/gophish

**Comment by spadgezilla** [comment] 2020-07-09 09:06
@glennzw - Thanks, I'll give that a go now and report back.

**Comment by glennzw** [comment] 2020-07-09 12:11
Great! I'm also quite happy I didn't have to deploy an Exchange server to reach this point 😄

**Closed** 2020-07-09 16:38 UTC

**Comment by asriznet** [comment] 2020-07-10 11:39
i've spin up a fresh ubuntu container and install gophish from source as recommended.
Configure IMAP reporting to an O365 account successfully
Created a new campaign and tested.
all tracking works except for User Reporting.
Gophish parsed the email successfully as I see it changed from unread to read status however still not recognize as part of campaign
logs are are recognising user reports but still not been tagged to the campaign.

`time="2020-07-10T11:29:26Z" level=info msg="User 'John Doe <hello@contoso.com>' reported email with subject 'FW: Password expired: Please update your account credentials.'. This is not a GoPhish campaign; you should investigate it."`

**Comment by spadgezilla** [comment] 2020-07-10 12:28
@asriznet 

I've seen this too but not done much in the way of testing yet. I think it has something to do with the formatting of the email that is forwarded to the monitored mailbox. Specifically, I have noticed this being an issue when the email is forwarded from the junk folder (i.e. stripped down). See screenshot below of logs from the same campaign, one forwarded from the inbox and one forwarded from the junk folder. In a real world test, we would configure our whitelisting so that the spam test would get through to the users inbox.

![image](https://user-images.githubusercontent.com/7251456/87154282-e037b000-c2b0-11ea-887d-881cb7538a93.png)

I also didn't think that forwarding as an attachment was supported, see https://github.com/gophish/gophish/issues/1782

**Comment by asriznet** [comment] 2020-07-10 12:39
> @asriznet
> 
> I've seen this too but not done much in the way of testing yet. I think it has something to do with the formatting of the email that is forwarded to the monitored mailbox. Specifically, I have noticed this being an issue when the email is forwarded from the junk folder (i.e. stripped down). See screenshot below of logs from the same campaign, one forwarded from the inbox and one forwarded from the junk folder. In a real world test, we would configure our whitelisting so that the spam test would get through to the users inbox.
> 
> ![image](https://user-images.githubusercontent.com/7251456/87154282-e037b000-c2b0-11ea-887d-881cb7538a93.png)
> 
> I also didn't think that forwarding as an attachment was supported, see #1782

Hi,
According to my latest testing on a fresh ubuntu install with gophish build from source, user report forwarded as attachment works fine now for Exchange Online.
Sorry as not able to update the status on the other discussion as was held up with other projects.

and no, none of the campaign emails are going to junk as we have set rules on the mailserver to bypass spam filtering.

**Comment by glennzw** [comment] 2020-07-10 15:22
Super. So, @asriznet and @spadgezilla, is everything working as expected now? I'm not sure about junk folder forwarding - but the latest IMAP will parse the email text, HTML, and attachments (of type eml) applying a regex searching for `?rid=XXXXXXX`

**Comment by asriznet** [comment] 2020-07-10 15:36
> Super. So, @asriznet and @spadgezilla, is everything working as expected now? I'm not sure about junk folder forwarding - but the latest IMAP will parse the email text, HTML, and attachments (of type eml) applying a regex searching for `?rid=XXXXXXX`

Hi @glennzw !
Thank you for your support and yes gophish works fully now with IMAP reporting too.

Although we have recently added ATP license to increase protection for our users which have made gophish reporting stopped working again due to [O365 ATP Safe Link](https://www.queensu.ca/its/microsoft-office-365/security-features/advanced-threat-protection/atp-safe-links), I have workaround this by excluding our campaign URL from ATP Safe Link Policy and reporting is working again.

Also i found out why logs are showing tracking for an unknown ID, it was because I had copied the email template from a previous campaign email which had the tracking image copied over. I have since edited the template to remove the old tracker, have yet to test it but i'm confident that was it.

**Comment by glennzw** [comment] 2020-07-13 10:27
Great, glad to hear it @asriznet, happy phishing!

**Comment by ldunzweiler** [comment] 2020-08-06 17:20
Just want to leave a note here about the _"This is not a GoPhish campaign; you should investigate it."_ On Outlook for macOS Catalina v16.40 I get this error when testing a phishing campaign from the root of my inbox.  I also get it in Outlook 2016 (16.0.5017.1000) on Windows 10 2004.  However, if I fwd as attachment GoPhish successfully sees it as reported in both cases.   GoPhish also sees it successfully reported if I send it via webmail or even the Windows 10 Mail app.
