### ISSUE TITLE
Allow for custom template variables

### ISSUE THREAD

**Issue by hevnsnt** [gophish/gophish#627] opened 2017-05-18 23:10 UTC
In the next version, can you please allow for custom template variables?

For example I would like to import custom user data:
FNAME
LNAME
EMAIL
COMPANY

And I would like to be able to use custom email template variables such as {{.FNAME}}, {{.LNAME}}, {{.EMAIL}}, {{.COMPANY}} etc

Thanks!

**Comment by jordan-wright** [comment] 2017-05-20 20:42
Thanks for sending this in! It looks like this is a duplicate of #27, which is yet to be implemented. There are some development barriers to overcome before this can happen, but it's on our radar.

We'll work from that issue, so I'll close this one out.

**Closed by jordan-wright** 2017-05-20 20:42 UTC
