### ISSUE TITLE
Not able to redirect the user to my landing page and not able to see the mail status

### ISSUE THREAD

**Issue by NavinGovind** [gophish/gophish#1996] opened 2020-10-05 09:10 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11.0

Brief description of the issue:  

Not able to redirect the user to my landing page even though I have imported the landing page sucessfully and I'm not able to see the status on the dashboard only mail sent is shown to me

What are you expecting to see happen? :

The user should be directed to proper landing page , I should be able to see the status in dashboard and should be able to capture the password

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Code of my landing page:

```
  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <title> nexuba </title>
  | <link rel='shortcut icon' type='image/x-icon' href='I/favicon.ico?v=1.01'>
  | <meta name="viewport" content="width=device-width">
  | </head>
  |  
  | <FRAMESET rows="100%">
  | <FRAMESET cols="100%">
  | <FRAME src="EmployeeExperts.php">
  | </FRAMESET>
  | </FRAMESET>
  |  
  | </html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by NavinGovind** [comment] 2020-10-05 09:11
Landing page code:

<!DOCTYPE html>
<html>
<head>
       <title> nexuba </title>
	   <link rel='shortcut icon' type='image/x-icon' href='I/favicon.ico?v=1.01'>
       <meta name="viewport" content="width=device-width">
</head>

       <FRAMESET rows="100%">
               <FRAMESET cols="100%">
                       <FRAME src="EmployeeExperts.php">
               </FRAMESET>
       </FRAMESET>

</html>

**Comment by glennzw** [comment] 2020-10-06 10:40
Hi there!

I updated your pasted code to have backticks at the start and end (three of these characters -->  `) so the code shows up.

Your code is importing a PHP file `<FRAME src="EmployeeExperts.php">`, which is probably what's going wrong. Here's an example of a working landing page for you:

```html
<html>
 <body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  </body>
</html>
```

Otherwise you should try import the rendered `EmployeeExperts.php` that's loaded in the frame. ie if you previously imported `http://foo.com` rather now import `http://foo.com/EmployeeExperts.php`

Good luck.

**Comment by NavinGovind** [comment] 2020-10-07 10:19
Hi Glen,

Thank you for the code. Now we are able to make the users divert to my
landing page . But I'm not able to capture the data entered please help me
to slove this error .

Regards,
Navin G

**Comment by glennzw** [comment] 2020-10-09 09:59
Have you ticked the box when configuring your campaign to capture data? The above posted landing page should capture username at the least.

**Comment by NavinGovind** [comment] 2020-10-09 10:01
Hi Glenn,

Yes I have clicked both the boxes

**Comment by glennzw** [comment] 2020-10-09 10:08
Is data not being captured with this landing page:

```
<html>
 <body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  </body>
</html>
```

or with your own landing page code?

**Comment by NavinGovind** [comment] 2020-10-09 10:12
Let me try for this and check whether it works. Meanwhile if I give the
code of my landing page can you modify and give me

**Comment by jordan-wright** [comment] 2020-10-11 18:54
Hi there,

It looks like this is a duplicate of #1997 at this point since you're asking about capturing submitted data. With this being the case, I'm going to close this one out. If you're still running into issues after looking through the documentation I mentioned in my comment, let us know in #1997 and we can reopen to continue troubleshooting.

**Closed by jordan-wright** 2020-10-11 18:54 UTC
