### ISSUE TITLE
Opened Email tracking problem

### ISSUE THREAD

**Issue by r38** [gophish/gophish#1092] opened 2018-06-01 13:20 UTC
What version of Gophish are you using?: Lastest

Brief description of the issue: My "email opened" campaign statistics only increment when I click on the links and not when opening the email

What are you expecting to see happen? : Increment when opened

What are you seeing happen? Only when clicked on link

The external image is load but the stats didn't back to me until i clicked on the link

Thanks!

**Comment by jordan-wright** [comment] 2018-06-02 05:30
Hi @r38 - thanks for reaching out!

> The external image is load but the stats didn't back to me until i clicked on the link

Can you give some more context to this? When you say the external image is loaded, do you see that connection in the Gophish terminal? Like, you saw a connection log for the `/track` endpoint?

And the stats coming back- is this in the dashboard? How long was the delay between the email open and click events? If you waited multiple minutes between opening the email and clicking the link, did the event times also show that same delay?

**Comment by r38** [comment] 2018-06-04 07:18
hi @jordan-wright - Thank you for taking my problem into account,

> The external image is load but the stats didn't back to me until i clicked on the link
I mean I read the tickets related to stats reporting problems, and I activated as said in the automatic loading of external images. It's like the {{.Tracker}} didn't work/load, there is no log return to gophish when i opened. 

Even if I waited long minutes between opening the mail and clicking on the link, either in the campaign results or in the dashboard, the statistics of opening email and clicking on links appear at the same time on the timeline (When I click on the link)

PS:  I work on Debian9 VM (Win10 host).
The client e-mailing is Gmail.
I follow step by step your documentation to configure gophish.

**Comment by mcvaa** [comment] 2018-06-06 20:40
Gophish-v0.5.-windows-64bit.zip. Once the campaign is sent, receive the email I'm able to click on the link and all email sent, email opened, clicked link, and submitted data reports properly showing the users that have taken the action the issue is the submitted data view details does not populate the users information as shown in the screen shot:
![image](https://user-images.githubusercontent.com/14318521/41063943-15436aa0-69a8-11e8-8542-5d5b53cd9f89.png)

The landing page is configured to capture submitted data and capture passwords 
![image](https://user-images.githubusercontent.com/14318521/41063993-3fb2608e-69a8-11e8-8007-5c224e7b260d.png)

Along with the email template does have the add tracking image checked
![image](https://user-images.githubusercontent.com/14318521/41064028-5cb5dbca-69a8-11e8-9886-9fa5ca282b67.png)

Please advise.

**Comment by r38** [comment] 2018-06-12 12:12
hi @jordan-wright, do you have any idea ? :/

**Comment by jordan-wright** [comment] 2018-06-12 13:50
Hey there @r38, sorry for the delay!

> the statistics of opening email and clicking on links appear at the same time on the timeline (When I click on the link)

Do you mean in the pie charts you see the email opened and clicked link stats update at the same time? If this is the case, that's on the frontend where I have some logic that says "if the link was clicked, but we haven't seen an email open event, go ahead and add to that stat since the email was obviously opened".

Do you see the actual email opened event when you expand the row of the result in the campaign results page?

If the clicked link events are working, it might also help us make sure the `{{.Tracker}}` is formatted correctly if you could show us the source of the email you receive. It's quite possible that the tracker is configured correctly and whatever email provider you are using is still just configured to block automatic image fetching. I'm afraid if that's the case there's nothing we can do in Gophish to get around this.

**Comment by jordan-wright** [comment] 2018-07-07 22:01
Going ahead and closing this since there hasn't been any updates in a while. @r38 if you're still running into problems, if you could take a look at the questions from my previous comment then I'd be happy to re-open this and we can continue troubleshooting.

Thanks again for reaching out!

**Closed by jordan-wright** 2018-07-07 22:01 UTC
Labels: support

**Comment by sialegi** [comment] 2020-12-22 06:56
hi, also face this problem, my template has {{.Tracker}} .but upon opening the email. it does not record to gophish.
also check the email received show the original. 

Client's email was google. already check "Always display external images"

<img alt=3D'' style=3D'display: none' src=3D'http://192.168.22.123/track?ri=
d=3DUtUlrmT'/></body>
</html>
