### ISSUE TITLE
Garbled accessories

### ISSUE THREAD

**Issue by Ymigmli** [gophish/gophish#2096] opened 2021-01-11 08:26 UTC
What version of Gophish are you using?: 
gophish_0.11.0

Brief description of the issue: 
Send 中文测试.docx Chinese attachment in the mailbox display garbled, using ie, firebox, Google to view the mailbox

What are you expecting to see happen? :
not garbled，中文测试.docx becomes a file 中文测试.docx

What are you seeing happen?
中文测试.docx becomes a file 涓枃娴嬭瘯.docx

The source code of abnormal page displayed in the inboxes
`<span player="/cgi-bin/download?mailid=ZL1011-IyqJzSPfD69UZkMcrz_LIb1&amp;filename=%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95.docx&amp;sid=HBXArUP5etohNRBP">涓枃娴嬭瘯.docx</span>`

eml:
`Content-Disposition: attachment; filename="中文测试.docx"
Content-ID: <中文测试.docx>
Content-Transfer-Encoding: base64
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document;
	name="中文测试.docx"`

Inboxes display normal page source code
`<span player="/cgi-bin/download?mailid=ZL1211-6uMwUrxWvBznLQhXcB0feb1&amp;filename=%D6%D0%CE%C4%B2%E2%CA%D4.docx&amp;sid=HBXArUP5etohNRBP">中文测试.docx</span>`

eml:
`------=_NextPart_5FFBEAAB_10302518_241C259A
Content-Type: application/octet-stream; charset="gb18030";
	name="=?gb18030?B?1tDOxLLiytQuZG9jeA==?="
Content-Disposition: attachment;
	filename="=?gb18030?B?1tDOxLLiytQuZG9jeA==?="
Content-Transfer-Encoding: base64`

**Comment by glennzw** [comment] 2021-01-22 10:49
You've probably already tested this, but if you send an email to that inbox from another email account, does the attachment filename come through OK? i.e I want to rule out that the problem is not with the email client or server along the way.

**Comment by Ymigmli** [comment] 2021-01-22 11:55
Thank you very much for your reply. I have been paying attention to this issue these days.

It's normal to use other mailbox to send mail to this in box, and use the same Google and Firefox browser to view attachments.

The SMTP server is Kali (postfix), and gophish is also installed in Kali. Windows uses gophish's own SMTP server, which has been side tested. If the attachment name of the email is Chinese, the open of the in box is garbled.

**Comment by Ymigmli** [comment] 2021-01-22 11:59
Thank you for your reply.
In addition, this login page cannot get the submitted data.

`<!DOCTYPE html><html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


<title>演练单位OA系统</title>
<link rel="stylesheet" type="text/css" href="https://192.168.20.222:50001/oa/css.css"/>
<link rel="shortcut icon" href="http://192.168.20.223:50003/favicon.ico"/>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/jquery.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/js.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/base64-min.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/loginscript.js"></script>
<style>
.lmaisft{width:450px;border-radius:10px;text-align:left;background:white;border:1px #dddddd solid;}
.box{box-shadow:0px 5px 15px 1px rgba(0,0,0,0.1);}
.btn-danger{background-color:#d9534f;}
</style>
</head>


<body style="background:#E5F3FC;">

<div align="center" style="position:absolute;width:100%">
	<div id="topheih" class="blank40" style="height: 224px;"></div>

	<div style="font-size:30px"><b>演练单位OA系统</b></div>
	<div class="blank30"></div>
	<div class="lmaisft box">
		<div class="blank20"></div>
		<div id="mainlogin">
		
		<div align="center"><img title="http://127.0.0.1" class="box" onclick="location.reload()" style="border-radius:50%;border:1px #ffffff solid; background:white" src="https://192.168.20.222:50001/oa/logo.png" id="imglogo" align="absmiddle" height="100" width="100"/><b style="font-size:22px"></b></div>
		<div class="blank10"></div>
		<form style="padding:20px;padding-left:80px" name="myform" action="">
			
						<div id="loginview0">
			
				<div>
					<div><input type="text" style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)getpassobj().focus()" value="" placeholder="请输入用户名/姓名/手机号/邮箱" name="adminuser"/></div>
				</div>

				<div class="blank30"></div>
				<div>
					<div><input style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)loginsubmit()" value="" type="password" placeholder="请输入密码" name="password"/></div>
				</div>

				<div class="blank10"></div>
				<div align="left">
					 <div class="checkbox"><label><input type="checkbox" name="rempass"/>记住密码</label>  <a onclick="erwmlogin()" href="javascript:;"><img src="https://192.168.20.222:50001/oa/ewml.png" title="二维码登录" align="absmiddle"/></a></div>
				</div>
			</div>
			<div id="loginview1" style="display:none">
				<input type="hidden" name="logintype" value="0"/>
							<div>
					<input type="text" style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)form(&#39;adminmobileyzm&#39;).focus()" maxlength="11" value="" placeholder="请输入手机号" name="adminmobile"/>
				</div>
				<div class="blank30"></div>
				<div>
					<table><tbody><tr>
					<td><input type="text" style="height:40px;width:200px;border-top-left-radius:5px;border-bottom-left-radius:5px" class="input" onkeyup="" maxlength="6" placeholder="请输入验证码" name="adminmobileyzm"/></td>
					<td><input type="button" onclick="getyzm(this)" style="height:42px;width:100px;border-top-right-radius:5px;border-bottom-right-radius:5px" value="获取验证码" class="webbtn"/></td>
					</tr></tbody></table>
				</div>
			</div>
			

			<div class="blank20"></div>

			<div align="left">
				<button type="button" onclick="loginsubmit()" style="padding:10px 30px;border-radius:5px" class="webbtn" name="button">登录</button> <span id="msgview"></span>
			</div>
			<div class="blank10"></div>
		</form>
		
		</div>
	</div>



	<div class="blank20"></div>
	<div align="center" style="height:30px;line-height:30px;color:#555555">
		Copyright ©2021 演练单位OA系统v2.2.0   -   
		版权所有：<a href="http://www.rockoa.com/" style="color:#1F83C1" target="_blank">信呼开发团队</a>
	</div>

</div>


</body></html>`

**Comment by Ymigmli** [comment] 2021-01-26 02:31
To solve the above problem, we can modify the form.

`<form style="padding:20px;padding-left:80px" name="myform" action="">`
changed:
`<form **method="post"** style="padding:20px;padding-left:80px" name="myform" action="">`

`<button type="button" onclick="loginsubmit()" style="padding:10px 30px;border-radius:5px" class="webbtn" name="button">登录</button> <span id="msgview"></span>`
changed:
`<**input type="submit"** style="padding:10px 30px;border-radius:5px" class="webbtn" **value="登陆"** /> <span id="msgview"></span>`

`<!DOCTYPE html><html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


<title>演练单位OA系统</title>
<link rel="stylesheet" type="text/css" href="https://192.168.20.222:50001/oa/css.css"/>
<link rel="shortcut icon" href="http://192.168.20.223:50003/favicon.ico"/>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/jquery.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/js.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/base64-min.js"></script>
<script type="text/javascript" src="https://192.168.20.222:50001/oa/loginscript.js"></script>
<style>
.lmaisft{width:450px;border-radius:10px;text-align:left;background:white;border:1px #dddddd solid;}
.box{box-shadow:0px 5px 15px 1px rgba(0,0,0,0.1);}
.btn-danger{background-color:#d9534f;}
</style>
</head>


<body style="background:#E5F3FC;">

<div align="center" style="position:absolute;width:100%">
	<div id="topheih" class="blank40" style="height: 224px;"></div>

	<div style="font-size:30px"><b>演练单位OA系统</b></div>
	<div class="blank30"></div>
	<div class="lmaisft box">
		<div class="blank20"></div>
		<div id="mainlogin">
		
		<div align="center"><img title="http://127.0.0.1" class="box" onclick="location.reload()" style="border-radius:50%;border:1px #ffffff solid; background:white" src="https://192.168.20.222:50001/oa/logo.png" id="imglogo" align="absmiddle" height="100" width="100"/><b style="font-size:22px"></b></div>
		<div class="blank10"></div>
		<form method="post" style="padding:20px;padding-left:80px" name="myform" action="">
			
						<div id="loginview0">

				<div>
					<div><input type="text" style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)getpassobj().focus()" value="" placeholder="请输入用户名/姓名/手机号/邮箱" name="adminuser"/></div>
				</div>

				<div class="blank30"></div>
				<div>
					<div><input style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)loginsubmit()" value="" type="password" placeholder="请输入密码" name="password"/></div>
				</div>

				<div class="blank10"></div>
				<div align="left">
					 <div class="checkbox"><label><input type="checkbox" name="rempass"/>记住密码</label>  <a onclick="erwmlogin()" href="javascript:;"><img src="https://192.168.20.222:50001/oa/ewml.png" title="二维码登录" align="absmiddle"/></a></div>
				</div>
			</div>
			<div id="loginview1" style="display:none">
				<input type="hidden" name="logintype" value="0"/>
							<div>
					<input type="text" style="height:40px;width:300px;border-radius:5px" class="input" onkeyup="if(event.keyCode==13)form(&#39;adminmobileyzm&#39;).focus()" maxlength="11" value="" placeholder="请输入手机号" name="adminmobile"/>
				</div>
				<div class="blank30"></div>
				<div>
					<table><tbody><tr>
					<td><input type="text" style="height:40px;width:200px;border-top-left-radius:5px;border-bottom-left-radius:5px" class="input" onkeyup="" maxlength="6" placeholder="请输入验证码" name="adminmobileyzm"/></td>
					<td><input type="button" onclick="getyzm(this)" style="height:42px;width:100px;border-top-right-radius:5px;border-bottom-right-radius:5px" value="获取验证码" class="webbtn"/></td>
					</tr></tbody></table>
				</div>
			</div>
			

			<div class="blank20"></div>

			<div align="left">
				<input type="submit" style="padding:10px 30px;border-radius:5px" class="webbtn" value="登陆" /> <span id="msgview"></span>
			</div>
			<div class="blank10"></div>
		</form>
		
		</div>
	</div>



	<div class="blank20"></div>
	<div align="center" style="height:30px;line-height:30px;color:#555555">
		Copyright ©2021 演练单位OA系统v2.2.0   -   
		版权所有：<a href="http://www.rockoa.com/" style="color:#1F83C1" target="_blank">信呼开发团队</a>
	</div>

</div>


</body></html>`

**Comment by glennzw** [comment] 2021-03-06 17:42
@Ymigmli looks like a reasonable solution, thank you for sharing it. I'll go ahead and close this out.

**Closed by glennzw** 2021-03-06 17:42 UTC
