### ISSUE TITLE
Cannot Delete Campaign If Template Deleted

### ISSUE THREAD

**Issue by recrudesce** [gophish/gophish#254] opened 2016-04-26 12:52 UTC
If you create a campaign, then delete a template, you are unable to subsequently delete the campaign.

:: Reproduce ::
 - Create user/group template
 - Create email template
 - Create landing page template
 - Create campaign
 - Delete any of the above templates (not the campaign)
 - Try and delete campaign

Error message that gets thrown is:

```
 2016/04/26 08:48:25 campaign.go:161: record not found: template not found for campaign
 2016/04/26 08:48:25 api.go:95: record not found

```

**Comment by jordan-wright** [comment] 2016-04-27 06:15
Thanks for the report @recrudesce! Let me take a look and see if I can get this fixed.

Just curious - what version of gophish are you running? Are you using one of the binaries, or are you building from source?

**Comment by recrudesce** [comment] 2016-04-27 07:41
Hey Jordan,
I am using 0.1.1, downloaded as a binary.

I can try with 0.1.2 if that helps ?

**Comment by jordan-wright** [comment] 2016-05-20 20:58
Hey @recrudesce - I see that this is very likely a dupe of #197. Building from source should fix this issue until we release the next binaries.

If you are still able to reproduce this issue after building from source, let me know and I'll re-open.

Thanks for the report!

**Closed by jordan-wright** 2016-05-20 20:58 UTC
Labels: bug, med-priority
