### ISSUE TITLE
Newbie here needs help launching campaign

### ISSUE THREAD

**Issue by JKasper777** [gophish/gophish#581] opened 2017-03-30 14:51 UTC
So I've followed a few tutorials and I've gotten test emails to send and imported a satisfactory template.  My issue is that I am not getting a change in status when the emails are opened.  Most likely has something to do with using an incorrect url or Ip address somewhere but I could definitely use some guidance.  I'll post my settings for you to review and hopefully point out my mistakes.

"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish.crt",
		"key_path" : "gophish.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

- I'm using a gmail address as the sending address and all of the emails will be going to gmail users on our internal network.  I'm using smtp.gmail.com:587 in my sending profile.

- I've imported the default gmail landing page as my landing page.

- I sent an email to myself in the format that I want and imported the source as the email template.

- When setting up the campaign, I've tried using the IP of my local computer as the url ( 172.xxx.xxx.xxx:80) and I've tried using 0.0.0.0:80 as well.

I'm sure my mistake is glaringly obvious but any help would be greatly appreciated.

**Comment by Vanhecke** [comment] 2017-03-31 11:15
Did you tick the box "Add tracking image" or did you add the tracking url manually?

**Comment by JKasper777** [comment] 2017-03-31 13:51
Yes sir I had the box ticked

**Comment by JKasper777** [comment] 2017-03-31 14:04
@Vanhecke

**Comment by Vanhecke** [comment] 2017-03-31 16:12
Well neither 172.xxx.xxx.xxx:80 or 0.0.0.0:80 will work over the internet.
Are you using 172.16.0.0/12 internally at the company? Or are you using 172.0.0.1?

Either way, using a local IP might not work with certain browsers for security reasons.
I recommend you setting up gophish on a small VPS with a public IP.

**Comment by JKasper777** [comment] 2017-03-31 16:18
@Vanhecke yes we use 172.16.x.x internally at our company.  I thought that might work since all of the employees are on the internal network but maybe it's not working due to using the gmail smtp server.

**Comment by S0larflare** [comment] 2017-04-03 10:48
If you are using this internally in a company, is there a mail server internally that you can use?

**Comment by JKasper777** [comment] 2017-04-03 19:38
@S0larflare would this even be an email server issue though?  The emails are coming through just fine.  I'm just not getting any update on the success if they are opened and links are clicked.

**Comment by jordan-wright** [comment] 2017-04-03 22:49
Are you including yourself on the campaigns? If so, what is the URL you see in the email you receive?

What do you see when you click the link in the email?

**Comment by JKasper777** [comment] 2017-04-04 12:19
Yes so far I've only been sending them to myself to test.  The link I've been getting is something along the lines of http://172.16.1.xxx/?rid=IEW8sPh, which is the address of my machine +whatever gophish is adding. @jordan-wright

**Comment by S0larflare** [comment] 2017-04-04 12:47
So if you set that up and click the link in the email, do you see the landing page that you have set up? Is it just that you never get the email opened event in the campaign? Do you still get 'clicked link' or 'submitted data' or anything?

**Comment by JKasper777** [comment] 2017-04-04 12:53
Actually upon clicking I get a 404 error.  I don't get clicked link/submitted data or even email opened. @S0larflare

**Comment by S0larflare** [comment] 2017-04-04 13:02
Sounds like you're not able to reach the server, hence the problem. The simplest problem that could be causing this is a block on port 80 inbound on your local machine, so you could try changing it to port 81 in your config just to check. If that does nothing, can you see anything in the console when you click the link?

**Comment by JKasper777** [comment] 2017-04-04 13:05
Would you recommend using 0.0.0.0:81 for the server or the address of my machine with :81? I appreciate all of the help from you guys.

**Comment by S0larflare** [comment] 2017-04-04 13:10
Yes, sorry, should have said. Put 0.0.0.0:81 in your config.json, then put your campaign address as http://172.16.1.xxx:81, see if you get anything coming through then.

**Comment by JKasper777** [comment] 2017-04-04 13:18
Ok this time upon clicking the link I got a connection refused error instead of a 404 error

**Comment by S0larflare** [comment] 2017-04-04 13:34
Just tested it on mine, Gophish doesn't appear to like port 81, try it with 8080 instead!

**Comment by JKasper777** [comment] 2017-04-04 13:50
Still getting the connection refused error even with 8080

**Comment by jordan-wright** [comment] 2017-04-04 13:58
If you don't see any connection logs in your gophish terminal and the IP address is correct, it's likely that there is a firewall preventing access.

**Comment by JKasper777** [comment] 2017-04-04 14:12
OK I'll look for possible firewall isssues.  Again I appreciate all of the help.

**Comment by JKasper777** [comment] 2017-04-04 15:23
OK so I now am having success with the link pointing to an actual page but still am not getting any confirmation of email opening or clicking of the link.  I've tried adding the tracking link via checking the box and also adding it manually.

**Comment by jordan-wright** [comment] 2017-04-06 02:56
The email opening may be due to your email client not loading remote images for privacy reasons.

What is the URL you see in the email you receive? You see the confirmed landing page when you click that link? Do you see the connection appear in the Gophish terminal?

If you see that connection but still don't see a "Clicked Link" event appear, we'll have to continue troubleshooting.

**Comment by jordan-wright** [comment] 2017-05-27 01:20
Closing this one out since there haven't been any updates in nearly 2 months.

@JKasper777 if you're still having issues getting up and running, let us know and we can re-open.

**Closed by jordan-wright** 2017-05-27 01:20 UTC
Labels: support

**Comment by BBsttx** [comment] 2017-08-17 19:40
JKasper777 - How did you resolve your issues...I seemed to have the exact same problem
