### ISSUE TITLE
How do we use user-reporting?

### ISSUE THREAD

**Issue by doubledrat** [gophish/gophish#1152] opened 2018-07-30 10:30 UTC
What version of Gophish are you using?: 
0.6

Brief description of the issue: 
so how are we supposed to use user-reporting? I can't see a code to insert into the email template to provide a reporting link. Also if I visit the link by hand it doesn't give any indication to the end user that it's worked (although it has)

What are you expecting to see happen? :
a code to be able to insert into the templates so that users can click on it to show they've spotted the phish.  Also the ability to define landing pages for the reporting (or failing that at least to have a default page saying "thanks for reporting")

What are you seeing happen?
can't give the user a link to click on, so can't use this feature?

**Comment by cyberbsw** [comment] 2018-08-07 17:29
Also interested.

**Comment by doubledrat** [comment] 2018-08-08 09:26
I'm pretty sure there is no way of using this feature yet!

I hacked the code to make it work, but it's not pretty ;-)

**Comment by petermat** [comment] 2018-08-18 12:26
Reporting link in email template? You mean like "This could be a Phishing email, please click here to report me" ?
Makes no sense to me, please elaborate.

You need a script looking into you reporting email address and sending requests to Gophish server when it finds a gophish campaign mail.

Request format:
http://phish_server/report?rid=1234567

**Comment by jordan-wright** [comment] 2018-08-18 16:10
Sorry for the late response everyone - these past couple of months have been really busy.

@petermat is correct that the reporting functionality is meant to let users report emails from their mail client. This is typically seen as a "Report Phishing" button or similar that you can install.

The problem is that we don't have an official email client integration at the moment. That's something we're working on. It's likely that we can use https://github.com/duo-labs/isthislegit to make this happen, but I haven't had the chance to make adjustments to it / get it working.

I'll keep everyone updated!

**Comment by mrbangus** [comment] 2018-12-19 16:35
@jordan-wright - So, I've been using GoPhish for a couple years now and recently installed Version 0.7.1 and I noticed the "Email Reported" graph.  But, the only way to report phishing emails would be to pass the link: http://phish/report?rid= with the "rid" after the =.  
I know there's several ways being tossed around, but I think the easiest way would be to pass the RID into a text field with a submit button to the Admin area Campaign results and if the email has been reported, the admin click the submit button and report it.  Something like the attached file.  
![capture](https://user-images.githubusercontent.com/10834544/50233561-b2fb7800-0381-11e9-9d8f-0517c796bfaf.PNG).  

I'm no engineer or coder, but I believe this shouldn't be too hard to code into GoPhish.

**Comment by mrbangus** [comment] 2018-12-19 21:54
I've figured out a solution to my previous comment.  I edited the **campaign_results.html** file.  arrowed down beneath the User Guide and API Documentation lines and added this code: 
`<li>
<br /><br /><ul><b>Email Reported</b>
<form action="http://phish (this will be whatever you name your server)/report?rid=" method="GET">
<input type="text" id="rid" name="rid" placeholder="XXX" />
<button type="submit" id="submit">Submit</button></ul></form><br />
<center>Please enter the RID Number for the user </center>
</li>`
This creates a text box with a submit button.  When someone reports an email (we've created the alias suspicious@ourcompanyname.com).  When someone is suspicious of an email, they send it there.  When we send out the phishing emails, and they forward it to this address, in the admin section of GoPhish, copy the RID and paste it in the txt field, hit submit and GoPhish counts it.  

I know this is a crude method, but hopefully will make it a tad bit easier until GoPhish community can create a better way.

**Comment by jordan-wright** [comment] 2018-12-22 02:11
Hey everyone!

Thank you for the great suggestions. My long term goal is to add user actions in each user’s results. So, these actions would include resending an email (or sending immediately if it hasn’t been sent yet), marking the email as reported, etc.

**Comment by jordan-wright** [comment] 2020-08-15 15:25
Hi everyone,

Just closing out older issues. In recent releases, you have the option to click the icon under the "Reported" column for each result. This will pop up a modal asking if you want to mark the result as reported. If you confirm, then the result will be correctly marked as reported, giving a manual way to process email reports.

**Closed by jordan-wright** 2020-08-15 15:25 UTC
Labels: support
