### ISSUE TITLE
Cannot import site due to proxy server in use

### ISSUE THREAD

**Issue by plex3r** [gophish/gophish#212] opened 2016-03-16 10:31 UTC
When I try to import a site it fails, I assume this is because I have to use a proxy to connect to the internet?

**Comment by jordan-wright** [comment] 2016-03-16 17:36
Do you see any specific error messages that could indicate the cause for the error?

**Comment by plex3r** [comment] 2016-03-17 09:08
I didn't see any errors when trying to do this it just times out, what I ill try is connecting to a direct internet connection and see if it then succeeds.

![landing_page_failure](https://cloud.githubusercontent.com/assets/4057454/13841260/b666cf84-ec1f-11e5-835b-2ea0c814199c.PNG)
![gophish_terminal](https://cloud.githubusercontent.com/assets/4057454/13841263/b9651772-ec1f-11e5-99f3-9b22318dfb3e.PNG)

**Comment by jordan-wright** [comment] 2016-03-19 01:22
Hey @plex3r - just checking in, any luck with this?

**Comment by jordan-wright** [comment] 2016-03-22 00:16
Hey @plex3r - just checking in one more time, any luck with this?

**Comment by plex3r** [comment] 2016-03-22 07:10
Hi Jordan,

Sorry haven't got chance to test yet.

I'll do it today.

**Comment by plex3r** [comment] 2016-03-22 08:59
@jordan-wright just tried it on an adsl connection and it works fine so it's got to be something to do with going through a proxy server at work to access the internet.

Hope this helps.

**Comment by jordan-wright** [comment] 2016-03-22 11:13
You bet! I might go ahead and close this for now. Proxy issues can be a huge pain to diagnose.

Since you were able to get it working, it at least looks like your gophish installation is good to go.

Thanks for the update!

**Comment by plex3r** [comment] 2016-03-22 11:17
@jordan-wright I've no idea what might be involved in support web proxies but I'd guess a lot of companies that are going to use this as an internal tool will have them and yes they may be able to use an alternative connection if it's a big issue to overcome.

**Comment by jordan-wright** [comment] 2016-03-22 11:44
I completely agree. In this case, it looks like something in the proxy was preventing outbound requests, which is odd, but will be difficult to track down from our end.

Did you see the same behavior trying to import HTTP sites, or only HTTPS sites?

Also, you might try setting the "HTTP_PROXY" environment variable to your companies proxy and see if that helps?

**Comment by rfdevere** [comment] 2016-03-22 12:00
This used to be an issue on every product/software I ran, issues getting it from my work machine to an external IP. If data policies permit it where you are just run things off a VPS and SSH onto it. You have 0 issues with getting access, although at the expensive of having your data 'out there'

**Comment by jordan-wright** [comment] 2016-03-22 15:43
Going to go ahead and close this for now. We will continue evaluating solutions if we encounter other issues.

**Closed by jordan-wright** 2016-03-22 15:43 UTC
Labels: support

**Comment by Oneiroi** [comment] 2024-01-19 14:03
@jordan-wright appreciate this is an old issue so apologies for "necro"'ing it somewhat; that being said the patch I'm proposing in #3077 fixes this issue @plex3r if you're seeing this issue at this time, please also t.a.l at the patch as this should fix the issues you reported.

Will happily amend any other areas which need such support, please lmk!
