### ISSUE TITLE
Landing page WYSIWYG view doesn't have scrollbars

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#773] opened 2017-09-29 15:04 UTC
Using v0.3, I created a new page, clicked on import site, the typed in 'https://login.microsoftonline.com/'.  When the page showed up in the WYSIWYG view (SOURCE not enabled), it only shows the MS blue.  There are no scrollbars to move around or any way to do a full page view/preview.

UPDATE:  After enabling 'capture submitted data' and 'capture password' (didn't try with just enabling one or the other), the WYSIWYG view now has scrollbars.  Didn't try to uncheck those two items as I don't want to break anything!

This would be resolved with implementation of issue #114.

**Comment by jordan-wright** [comment] 2017-09-30 03:52
This appears to be a duplicate of #753.

Here's my comment from that issue which pertains here, too:

Unfortunately, there are some pages that are so heavily tied into Javascript that when you preview them in CKEditor (our HTML editor) they won't show up right because it prevents the execution of scripts for security reasons.

With that being the case, it's possible that saving the page might make it look ok when it comes time to run a campaign, but I can't make that guarantee.

I wish there were more we could do about this, but you may just have to clone the website locally, make any changes and then manually add in the HTML to your landing page.

**Closed by jordan-wright** 2017-09-30 03:52 UTC
