### ISSUE TITLE
Debugging sending performance issue

### ISSUE THREAD

**Issue by edermi** [gophish/gophish#1726] opened 2020-01-21 15:44 UTC
What version of Gophish are you using?: 
c553d7d9255bd686f4e169f9471da5ece0aefcb7

Brief description of the issue: 
As several users have already reported, sending performance of Gophish degrades for a large number of targets.

What are you expecting to see happen? :
Fast mail sending even for a large number of targets.

What are you seeing happen?

I did some deep dive and identified the root cause of the issue. I took care to write down all steps in order to allow you to reproduce the issue with minimal manual work. Grab a drink and take a seat..

## Setup

- The test is conducted on a Debian Buster VM running on my local machine. All actions take place locally, therefore it is **not** required to have Internet connectivity (apart from installing required packages and getting sources), an external mail server, domain configured etc. The used Go version is `go1.11.6 linux/amd64`.
- `go get` Gophish from c553d7d9255bd686f4e169f9471da5ece0aefcb7
- `go build` Gophish
- Download latest MailHog release (https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64)
- Run mailhog with default options
- Verify web interface works (http://localhost:8025)
- To verify the mail server works and to get an idea for its performance, I use the following Python script that sends 5k Mails and measures times:

~~~python
import smtplib
from email.message import EmailMessage
from timeit import default_timer as timer

start = timer()

s = smtplib.SMTP('localhost:1025')

for number in range(0, 5000):
    msg = EmailMessage()
    msg.set_content("Mail from python")
    msg['Subject'] = f'Test {number}'
    msg['From'] = "sender@example.com"
    msg['To'] = "receiver@example.com"

    s.send_message(msg)

s.quit()
end = timer()
print(end - start) 
~~~

On my small test VM (2 notebook cores, <4GB RAM) this takes about 24 seconds:

~~~bash
$ python3 --version
Python 3.7.3
$ python3 python-gophishdbg-sendmail.py
23.703909114999988
~~~

- In mailhog, we can see that all mails have been received by mailhog and no mail was lost. 

![verify_mailhog_works](https://user-images.githubusercontent.com/7430871/72819016-c061f080-3c6c-11ea-8793-3a5fdb716400.png)
- Since this is a rather simple use case and a lab setup involving no authentication, only small message sizes, in memory storage and no network latency, I'd say that it would be OK for Gophish to send 5k mails in less than 5 minutes.

- Now fire up gophish. The following script is used to automatically provision the server with meaningful test data so we can compare the performance and probably spot the bug later on

- Use the following python script to fill the instance with meaningful data and start sending mails:

~~~python
from gophish import Gophish # pip3 install gophish
from gophish.models import *
from faker import Faker # pip3 install Faker
from faker.providers import internet

# You may need to adjust this
api_key = "e53caa153515308abf60dd2bddb05caed4be0d4f1806d88b04e244f29f7abcef"
api = Gophish(api_key, host='https://localhost:3333', verify=False)


def create_sending_profile():
    smtp = SMTP(name='Test SMTP')
    smtp.host = "localhost:025"
    smtp.from_address = "Example <example@example.com>"
    smtp.interface_type = "SMTP"
    smtp.ignore_cert_errors = True
    try:
        smtp = api.smtp.post(smtp)
        print("Created sending profile with ID {}".format(smtp.id))
    except Error:
        print("Sending profile already exists, skipping")
    

def create_targets(num: int=5000):
    fake = Faker()
    fake.add_provider(internet)
    targets = []
    for i in range(0, num):
        targets.append(User(first_name=f"User_{i}", last_name="", email=fake.email()))
    group = Group(name="Performance Debugging User Set", targets=targets)
    try:
        group = api.groups.post(group)
        print("Created group with ID {}".format(group.id))
    except Error:
        print("Group already exists, skipping")

def create_landing_page():
    page = Page(name='Test Page', html='<html><body>Click <a href="{{.URL}}">here</a></body></html>')
    try:
        page = api.pages.post(page)
        print("Created test page with ID {}".format(page.id))
    except Error:
        print("Landing page already exists, skipping")


def create_mail_template():
    template = Template(name='Test Template', html='<html><body>Click <a href="{{.URL}}">here</a></body></html>')
    try:
        template = api.templates.post(template)
        print("Created test template with ID {}".format(template.id))
    except Error:
        print("Template already exists, skipping")


def create_campaign():
    groups = [Group(name='Performance Debugging User Set')]
    page = Page(name='Test Page')
    template = Template(name='Test Template')
    smtp = SMTP(name='Test SMTP')
    url = 'http://phishing_server' # doesn't matter
    campaign = Campaign(name='Example Campaign', groups=groups, page=page, template=template, smtp=smtp)
    input("Everything is ready, hit <Enter> to start the campaign\n")
    try:
        campaign = api.campaigns.post(campaign)
        print("Created test campaign with ID {}".format(campaign.id))
    except Error:
        print("Campaign already exists, skipping")


if __name__ == '__main__':
    create_sending_profile()
    create_targets()
    create_landing_page()
    create_mail_template()
    create_campaign()
~~~

## Identifying the issue

As you can see in mailhog, E-Mails are sent comparably slow - according to the info log about 2-4 mails per second.

During the sending time frame, gophish also generates quite high load on the machine.

![gophish_high_load_during_send](https://user-images.githubusercontent.com/7430871/72819014-c061f080-3c6c-11ea-9558-84c98d921604.png)

Sending all 5000 Mails took (according to timestamps in log) 40 minutes and 22 seconds - also 13 messages have not been transmitted (this is something for another issue...):

![lost_mails](https://user-images.githubusercontent.com/7430871/72819015-c061f080-3c6c-11ea-8f3e-216076619176.png)

Interestingly, sending 100 instead of 5000 mails goes significantly faster, therefore I assume that Gophish becomes slower depending on the size of the set or target emails. This behaviour makes it also trickier to nail down the bug, since mail sending is fast for small recipient sets.

I modified the send loop in `mailer.go` to contain some simple time measurements:

~~~go
for i, m := range ms {
		start := time.Now()
		select {
		case <-ctx.Done():
			return
		default:
			break
		}
		selectTiming := time.Since(start)
		start = time.Now()
		message.Reset()
		resetTiming := time.Since(start)
		start = time.Now()
		err = m.Generate(message)
		if err != nil {
			log.Warn(err)
			m.Error(err)
			continue
		}
		generationTiming := time.Since(start)
		start = time.Now()
		err = gomail.Send(sender, message)
		errorTiming := time.Since(start)
		start = time.Now()
		if err != nil {
			if te, ok := err.(*textproto.Error); ok {
				switch {
				// If it's a temporary error, we should backoff and try again later.
				// We'll reset the connection so future messages don't incur a
				// different error (see https://github.com/gophish/gophish/issues/787).
				case te.Code >= 400 && te.Code <= 499:
					log.WithFields(logrus.Fields{
						"code":  te.Code,
						"email": message.GetHeader("To")[0],
					}).Warn(err)
					m.Backoff(err)
					sender.Reset()
					continue
				// Otherwise, if it's a permanent error, we shouldn't backoff this message,
				// since the RFC specifies that running the same commands won't work next time.
				// We should reset our sender and error this message out.
				case te.Code >= 500 && te.Code <= 599:
					log.WithFields(logrus.Fields{
						"code":  te.Code,
						"email": message.GetHeader("To")[0],
					}).Warn(err)
					m.Error(err)
					sender.Reset()
					continue
				// If something else happened, let's just error out and reset the
				// sender
				default:
					log.WithFields(logrus.Fields{
						"code":  "unknown",
						"email": message.GetHeader("To")[0],
					}).Warn(err)
					m.Error(err)
					sender.Reset()
					continue
				}
			} else {
				// This likely indicates that something happened to the underlying
				// connection. We'll try to reconnect and, if that fails, we'll
				// error out the remaining emails.
				log.WithFields(logrus.Fields{
					"email": message.GetHeader("To")[0],
				}).Warn(err)
				origErr := err
				sender, err = dialHost(ctx, dialer)
				if err != nil {
					errorMail(err, ms[i:])
					break
				}
				m.Backoff(origErr)
				continue
			}
		}
		errorHandlingTiming := time.Since(start)
		log.WithFields(logrus.Fields{
			"email":               message.GetHeader("To")[0],
			"selectTiming":        selectTiming,
			"resetTiming":         resetTiming,
			"generationTiming":    generationTiming,
			"errorTiming":         errorTiming,
			"errorHandlingTiming": errorHandlingTiming,
		}).Info("Email sent")
		m.Success()
    }
~~~

Here are some results for mails from the 100-targets-run:
~~~
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=michele70@griffin.info errorHandlingTiming=156ns errorTiming=3.994391ms generationTiming=14.584268ms resetTiming="1.094µs" selectTiming=454ns
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=iwright@hotmail.com errorHandlingTiming=144ns errorTiming=2.447298ms generationTiming=5.096648ms resetTiming="1.373µs" selectTiming=376ns
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=mwhite@yahoo.com errorHandlingTiming=132ns errorTiming=2.632184ms generationTiming=15.213952ms resetTiming="1.006µs" selectTiming=479ns
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=estesdavid@duncan.com errorHandlingTiming=143ns errorTiming=1.572142ms generationTiming=13.906821ms resetTiming="1.061µs" selectTiming=458ns
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=anthonyescobar@gmail.com errorHandlingTiming=860ns errorTiming=2.739628ms generationTiming=5.999564ms resetTiming="1.64µs" selectTiming=488ns
time="2020-01-21T14:41:49+01:00" level=info msg="Email sent" email=evansautumn@yahoo.com errorHandlingTiming=145ns errorTiming=4.33192ms generationTiming=6.889167ms resetTiming="1.357µs" selectTiming=393ns
~~~

These are from a run with 5k targets:

~~~
01-21T14:43:58+01:00" level=info msg="Email sent" email=sandrasmith@hess.com errorHandlingTiming=167ns errorTiming=1.843308ms generationTiming=146.712995ms resetTiming="1.286µs" selectTiming=602ns
time="2020-01-21T14:43:58+01:00" level=info msg="Email sent" email=emilysims@hotmail.com errorHandlingTiming=185ns errorTiming=1.393477ms generationTiming=159.945886ms resetTiming="1.193µs" selectTiming=549ns
time="2020-01-21T14:43:59+01:00" level=info msg="Email sent" email=stephenssean@hotmail.com errorHandlingTiming=187ns errorTiming=1.923179ms generationTiming=154.307453ms resetTiming="1.428µs" selectTiming=631ns
time="2020-01-21T14:43:59+01:00" level=info msg="Email sent" email=jacob32@davis.net errorHandlingTiming=153ns errorTiming=1.582331ms generationTiming=189.721859ms resetTiming="1.451µs" selectTiming=581ns
time="2020-01-21T14:43:59+01:00" level=info msg="Email sent" email=sabrinamorrow@yahoo.com errorHandlingTiming=162ns errorTiming=1.066675ms generationTiming=153.22342ms resetTiming="1.03µs" selectTiming=628ns
time="2020-01-21T14:44:00+01:00" level=info msg="Email sent" email=oliverchristine@day-cruz.com errorHandlingTiming=161ns errorTiming=1.432362ms generationTiming=147.885443ms resetTiming="1.355µs" selectTiming=430ns
~~~

As you can see, the fastest generation took about 5ms in the 100 targets run whereas the 5k run has elements with nearly 190ms.

So, let's take a closer look at `Generate()` in `models/maillog.go` by adding some timers:

~~~go
// Generate fills in the details of a gomail.Message instance with
// the correct headers and body from the campaign and recipient listed in
// the maillog. We accept the gomail.Message as an argument so that the caller
// can choose to re-use the message across recipients.
func (m *MailLog) Generate(msg *gomail.Message) error {
	start := time.Now()
	r, err := GetResult(m.RId)
	if err != nil {
		return err
	}
	c, err := GetCampaign(m.CampaignId, m.UserId)
	if err != nil {
		return err
	}

	f, err := mail.ParseAddress(c.SMTP.FromAddress)
	if err != nil {
		return err
	}
	msg.SetAddressHeader("From", f.Address, f.Name)
	elapsedQueryData := time.Since(start)

	start = time.Now()
	ptx, err := NewPhishingTemplateContext(&c, r.BaseRecipient, r.RId)
	if err != nil {
		return err
	}
	elapsedPTC := time.Since(start)

	start = time.Now()
	// Add the transparency headers
	msg.SetHeader("X-Mailer", config.ServerName)
	if conf.ContactAddress != "" {
		msg.SetHeader("X-Gophish-Contact", conf.ContactAddress)
	}

	// Add Message-Id header as described in RFC 2822.
	messageID, err := m.generateMessageID()
	if err != nil {
		return err
	}
	msg.SetHeader("Message-Id", messageID)

	// Parse the customHeader templates
	for _, header := range c.SMTP.Headers {
		key, err := ExecuteTemplate(header.Key, ptx)
		if err != nil {
			log.Warn(err)
		}

		value, err := ExecuteTemplate(header.Value, ptx)
		if err != nil {
			log.Warn(err)
		}

		// Add our header immediately
		msg.SetHeader(key, value)
	}

	elapsedHeaders := time.Since(start)
	start = time.Now()
	// Parse remaining templates
	subject, err := ExecuteTemplate(c.Template.Subject, ptx)
	if err != nil {
		log.Warn(err)
	}
	elapsedTemplate := time.Since(start)
	start = time.Now()
	// don't set Subject header if the subject is empty
	if len(subject) != 0 {
		msg.SetHeader("Subject", subject)
	}

	msg.SetHeader("To", r.FormatAddress())
	if c.Template.Text != "" {
		text, err := ExecuteTemplate(c.Template.Text, ptx)
		if err != nil {
			log.Warn(err)
		}
		msg.SetBody("text/plain", text)
	}
	elapsedRemainingHeaders := time.Since(start)
	start = time.Now()
	if c.Template.HTML != "" {
		html, err := ExecuteTemplate(c.Template.HTML, ptx)
		if err != nil {
			log.Warn(err)
		}
		if c.Template.Text == "" {
			msg.SetBody("text/html", html)
		} else {
			msg.AddAlternative("text/html", html)
		}
	}
	elapsedHTML := time.Since(start)
	start = time.Now()
	// Attach the files
	for _, a := range c.Template.Attachments {
		msg.Attach(func(a Attachment) (string, gomail.FileSetting, gomail.FileSetting) {
			h := map[string][]string{"Content-ID": {fmt.Sprintf("<%s>", a.Name)}}
			return a.Name, gomail.SetCopyFunc(func(w io.Writer) error {
				decoder := base64.NewDecoder(base64.StdEncoding, strings.NewReader(a.Content))
				_, err = io.Copy(w, decoder)
				return err
			}), gomail.SetHeader(h)
		}(a))
	}
	elapsedAttachments := time.Since(start)

	log.WithFields(logrus.Fields{
		"elapsedQueryData":        elapsedQueryData,
		"elapsedPTC":              elapsedPTC,
		"elapsedHeaders":          elapsedHeaders,
		"elapsedTemplate":         elapsedTemplate,
		"elapsedRemainingHeaders": elapsedRemainingHeaders,
		"elapsedHTML":             elapsedHTML,
		"elapsedAttachments":      elapsedAttachments,
	}).Info("Email sent")

	return nil
}
~~~

The results indicate that the most expensive operation is querying data (5k users).

~~~
time="2020-01-21T15:19:31+01:00" level=info msg="Email sent" elapsedAttachments=79ns elapsedHTML="16.385µs" elapsedHeaders="16.811µs" elapsedPTC="27.208µs" elapsedQueryData=147.391754ms elapsedRemainingHeaders=566ns elapsedTemplate="3.529µs"
time="2020-01-21T15:19:31+01:00" level=info msg="Email sent" email=annacoleman@hotmail.com generationTiming=147.529328ms
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" elapsedAttachments=117ns elapsedHTML="25.834µs" elapsedHeaders="29.639µs" elapsedPTC="579.586µs" elapsedQueryData=148.520964ms elapsedRemainingHeaders=833ns elapsedTemplate="14.256µs"
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" email=connie91@sullivan-stone.com generationTiming=149.388801ms
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" elapsedAttachments=76ns elapsedHTML="20.441µs" elapsedHeaders="17.493µs" elapsedPTC="113.009µs" elapsedQueryData=158.642195ms elapsedRemainingHeaders=527ns elapsedTemplate="8.678µs"
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" email=rdavis@gmail.com generationTiming=158.913708ms
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" elapsedAttachments=77ns elapsedHTML="31.888µs" elapsedHeaders="26.208µs" elapsedPTC="62.666µs" elapsedQueryData=147.374994ms elapsedRemainingHeaders=509ns elapsedTemplate="4.141µs"
time="2020-01-21T15:19:32+01:00" level=info msg="Email sent" email=jasonsmith@yahoo.com generationTiming=147.574892ms
time="2020-01-21T15:19:33+01:00" level=info msg="Email sent" elapsedAttachments=177ns elapsedHTML="60.164µs" elapsedHeaders="31.445µs" elapsedPTC=22.0101ms elapsedQueryData=159.384985ms elapsedRemainingHeaders=799ns elapsedTemplate="14.785µs"
~~~

Again, **what** exactly is slow?

~~~go
func (m *MailLog) Generate(msg *gomail.Message) error {
	start := time.Now()
	r, err := GetResult(m.RId)
	if err != nil {
		return err
	}
	elapsedGetResult := time.Since(start)
	start = time.Now()
	c, err := GetCampaign(m.CampaignId, m.UserId)
	if err != nil {
		return err
	}
	elapsedGetCampaign := time.Since(start)
	start = time.Now()
	f, err := mail.ParseAddress(c.SMTP.FromAddress)
	if err != nil {
		return err
	}
	msg.SetAddressHeader("From", f.Address, f.Name)
	elapsedParseAddress := time.Since(start)

	ptx, err := NewPhishingTemplateContext(&c, r.BaseRecipient, r.RId)
	if err != nil {
		return err
	}

	log.WithFields(logrus.Fields{
		"elapsedGetResult":    elapsedGetResult,
		"elapsedGetCampaign":  elapsedGetCampaign,
		"elapsedParseAddress": elapsedParseAddress,
	}).Info("Email sent")

	// Add the transparency headers
~~~

Result:

~~~
time="2020-01-21T15:28:15+01:00" level=info msg="Email sent" elapsedGetCampaign=144.87673ms elapsedGetResult="948.977µs" elapsedParseAddress="8.167µs"
time="2020-01-21T15:28:15+01:00" level=info msg="Email sent" email=jacksonthomas@yahoo.com generationTiming=146.047505ms
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" elapsedGetCampaign=150.072904ms elapsedGetResult=1.613692ms elapsedParseAddress="7.988µs"
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" email=jasonthompson@yahoo.com generationTiming=152.102629ms
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" elapsedGetCampaign=149.681185ms elapsedGetResult="865.732µs" elapsedParseAddress="8.829µs"
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" email=suecollins@hotmail.com generationTiming=150.753832ms
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" elapsedGetCampaign=164.984759ms elapsedGetResult="902.753µs" elapsedParseAddress="8.743µs"
time="2020-01-21T15:28:16+01:00" level=info msg="Email sent" email=annacoleman@hotmail.com generationTiming=166.232961ms
time="2020-01-21T15:28:17+01:00" level=info msg="Email sent" elapsedGetCampaign=144.901844ms elapsedGetResult="896.696µs" elapsedParseAddress="12.833µs"
time="2020-01-21T15:28:17+01:00" level=info msg="Email sent" email=connie91@sullivan-stone.com generationTiming=146.169969ms
time="2020-01-21T15:28:17+01:00" level=info msg="Email sent" elapsedGetCampaign=149.204837ms elapsedGetResult=1.422603ms elapsedParseAddress="8.264µs"
time="2020-01-21T15:28:17+01:00" level=info msg="Email sent" email=rdavis@gmail.com generationTiming=150.96901ms
time="2020-01-21T15:28:17+01:00" level=info msg="Email sent" elapsedGetCampaign=149.987239ms elapsedGetResult=1.021825ms elapsedParseAddress="8.303µs"
~~~

**Result: The call to `GetCampaign()` massively slows down E-Mail sending with many recipients.** Fetching complete campaign info for every mail from the database also may explain the high load and slow web interface during sending.

## Solution

In my opinion there isn't a single obvious solution to the problem. Probably it is a good idea to take load from the database. As far as I see the ms slice passed to `sendMail()` may contain mails from different campaigns - if I'm mistaken and this is not the case, I'd vouch for querying the campaign once before going to the send loop and passing the object to each `Generate()` call. Otherwise, I'd probably use a simple cache, e.g. a two-dimensional map that is queried in `GetCampaign()` before going the long way down to the database.

I'd love to hear your opinions and solutions to the problem; Once @jordan-wright has decided what's probably best I can also send in a PR in order to hopefully solve the problem finally.

If there are any further questions or remarks, please feel free to ask.

**Comment by jordan-wright** [comment] 2020-01-21 15:53
Hey @edermi,

I’ll have time to dig into this later this evening, but for now just wanted to drop a quick comment to say “wow.”

Thanks for the *amazing* write up! 💚

**Comment by jordan-wright** [comment] 2020-01-22 04:19
Hey @edermi!

Just wanted to follow-up. To start, thank you again for sending this in. Really great work!

I totally agree with your analysis. It seems perfectly reasonable that the extra database access is causing most if not all of the significant delay.

What I'll be doing as time allows this week is creating a [benchmark](https://golang.org/pkg/testing/#hdr-Benchmarks) that we can use to measure improvements over the lifetime of the code. We can test with 100, 1000, and 5000 emails to start to measure how long things take. This is something I introduced in the last release to assist with performance improvements when managing groups and campaigns (see #1686 for details). Since this is testing something outside the `models/` package, there's a little more plumbing I'll need to do to get everything working.

Once I have that in place, we can iterate on improvements to the design. You're correct that the easiest solution would be to ensure that emails are queued to the mailwork organized by campaign. I'm pretty sure [this happens now](https://github.com/gophish/gophish/blob/947bb4ccba242135696e246e2f0991dd929eff2b/worker/worker.go#L65), but I'll confirm. If that's the case, we could add a pointer to the already loaded campaign say, [here](https://github.com/gophish/gophish/blob/947bb4ccba242135696e246e2f0991dd929eff2b/worker/worker.go#L78) and [here](https://github.com/gophish/gophish/blob/947bb4ccba242135696e246e2f0991dd929eff2b/worker/worker.go#L113), using a new function like `CacheCampaign()` off the maillog object that would be something like this:

```go
type MailLog struct {
...
campaign *Campaign `json:"-"`
}

func (m *MailLog) CacheCampaign(c *Campaign) {
    m.campaign = c
}
```

It's not my preferred design, but I'm not sure of a cleaner solution at the moment without some significant thinking about how the flow works. For example, it'd be great if this cache happened automatically as maillogs are loaded, but as things are implemented we'd still have the same problem. And adding a caching layer is likely more complex than I'd like, since we'd have to consider the entire lifecycle of objects in it.

For now, I'll get this benchmark knocked out and pushed up to a branch so that you can replicate the results with me and we can think more about different approaches to solve the problem.

**Comment by edermi** [comment] 2020-01-22 10:35
Hi @jordan-wright,

first of all, thanks for the kind words. As you can see, I'm really interested in getting rid of this bug as soon as possible since it messes up the results of larger awareness campaigns.

I took another look at the issue today: Fetching the campaign details (`c.getDetails()` in `GetCampaign()`) takes a lot of time because it retrieves all of the related campaign data. I tried to tweak the performance by just fetching required values, but still, there are too many queries to have a reasonable speed. I'm not a database expert, but probably there are further options to improve query speed, e.g. by creating a view on the relevant fields in order to fetch them all with a single query. Probably it is worth to spend some time thinking about this if we cannot make sure all mails belong to the same campaign or the caching complexity becomes too large.

I'll wait until your benchmarking is in place. In case you need feedback or help, please don't hesitate to @ me and I will see what I can do.

**Comment by jordan-wright** [comment] 2020-01-26 01:44
Just wanted to provide an update here. I spent some time trying to write a benchmark specifically for `mailer.sendMail` but I don't think it will be possible. The reason is that I need to have some level of DB access to make it work but this causes a circular dependency (`models -> mailer -> models`).

Instead, since we know the likely culprit is `maillog.Generate()`, I'll write a benchmark specifically for that. The benchmark will emulate what `sendMail` is doing.

Next, I agree that `GetCampaign` is something we should benchmark and improve as well so I'll make benchmarks for that. My tentative thought is that leveraging a transaction should speed things up significantly, but we'll see!

**Comment by jordan-wright** [comment] 2020-01-26 04:18
I've added benchmarks for the `maillog.Generate` function in 0620671. This measures how long it takes to call `Generate` with varying campaign sizes. This appears to reproduce your results:

```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ github.com/gophish/gophish/models -bench ^(BenchmarkMailLogGenerate100|BenchmarkMailLogGenerate1000|BenchmarkMailLogGenerate5000|BenchmarkMailLogGenerate10000)$

goos: darwin
goarch: amd64
pkg: github.com/gophish/gophish/models
BenchmarkMailLogGenerate100-4     	     423	   2647228 ns/op	  808228 B/op	   14130 allocs/op
BenchmarkMailLogGenerate1000-4    	      56	  22007848 ns/op	 6913918 B/op	  121755 allocs/op
BenchmarkMailLogGenerate5000-4    	       9	 112447866 ns/op	37676290 B/op	  600021 allocs/op
BenchmarkMailLogGenerate10000-4   	       5	 230155880 ns/op	75568974 B/op	 1197922 allocs/op
PASS
ok  	github.com/gophish/gophish/models	35.651s
Success: Benchmarks passed.
```

Using the examples you gave, we see that the average time to call `Generate` for a campaign of 100 recipients is roughly 2 milliseconds and for a campaign of 5000 recipients it's 112 milliseconds.

This clearly isn't ideal.

I'll also add benchmarks for `GetCampaign()` but I imagine that we'll see similar results suggesting that- as you identified- it's almost certainly the root cause. My initial thoughts on how to fix this will be to cache the relevant campaign details (only the fields we need. Basically everything but the results and events) into the maillog, then use that for generation. This means that we'll just need to do a lightweight lookup once per campaign which _should_ reduce this time dramatically.

When I have a preferred approach, I'll detail it here in case you'd like to take a stab at it. Happy to help shepherd the PR and help along the way! I'm always down to see code being merged into Gophish from folks in the community.

**Comment by jordan-wright** [comment] 2020-01-27 04:33
Ok, I think we're in good shape. Here's what I'm thinking.

### Fixing the first problem

I've confirmed that the call to `GetCampaign` is, as expected, what's taking so long here. Here's what I've done to try and reduce this.

First, I added a `cachedCampaign` field to the `MailLog` struct:

```go
type MailLog struct {
	Id          int64     `json:"-"`
	UserId      int64     `json:"-"`
	CampaignId  int64     `json:"campaign_id"`
	RId         string    `json:"id"`
	SendDate    time.Time `json:"send_date"`
	SendAttempt int       `json:"send_attempt"`
	Processing  bool      `json:"-"`

	cachedCampaign *Campaign
}
```

Then, I created a function called `CacheCampaign` which sets the provided campaign pointer to the `cachedCampaign` field after making sure the campaign has the expected ID:

```go
// CacheCampaign allows bulk-mail workers to cache the otherwise expensive
// campaign lookup operation by providing a pointer to the campaign here.
func (m *MailLog) CacheCampaign(campaign *Campaign) error {
	if campaign.Id != m.CampaignId {
		return fmt.Errorf("incorrect campaign provided for caching. expected %d got %d", m.CampaignId, campaign.Id)
	}
	m.cachedCampaign = campaign
	return nil
}
```

Then, both in calls to `GetDialer` and `Generate`, I check to see if the `cacheCampaign` is present. If it is, I use it. If it's not, I default back to `GetCampaign` (though, in reality this likely won't happen):

```go
func (m *MailLog) Generate(msg *gomail.Message) error {
	....
	c := m.cachedCampaign
	if c == nil {
		campaign, err := GetCampaign(m.CampaignId, m.UserId)
		if err != nil {
			return err
		}
		c = &campaign
	}
```

I then add the call to `CacheCampaign` in the benchmarks. This makes a *huge* difference, basically dropping them to the floor:

```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ github.com/gophish/gophish/models -bench ^(BenchmarkMailLogGenerate100|BenchmarkMailLogGenerate1000|BenchmarkMailLogGenerate5000|BenchmarkMailLogGenerate10000)$

goos: darwin
goarch: amd64
pkg: github.com/gophish/gophish/models
BenchmarkMailLogGenerate100-4     	    9429	    124463 ns/op	   27170 B/op	     504 allocs/op
BenchmarkMailLogGenerate1000-4    	    9986	    119438 ns/op	   27171 B/op	     504 allocs/op
BenchmarkMailLogGenerate5000-4    	    9646	    123551 ns/op	   27167 B/op	     504 allocs/op
BenchmarkMailLogGenerate10000-4   	   10000	    123759 ns/op	   27161 B/op	     504 allocs/op
PASS
ok  	github.com/gophish/gophish/models	37.109s
Success: Benchmarks passed.
```

This shows that even for a campaign of 10,000 recipients, the call to `Generate` will only take **.12 milliseconds**. Much better 😄 

### Oh no!

When testing this with a large campaign I noticed that, while I saw a speed up, it just wasn't as fast as I wanted it to be. I went back to the timing additions to gave, but everything was seemingly fine.

Then I noticed that we weren't checking the timing of the final call to `m.Success()`. Adding this showed that, while the `Generate` function was fixed, the `Success()` function was causing a 125ms delay! Oh no!

Sure enough, looking through the call tree we see that `Success()` calls `r.HandleEmailSent()` which calls `r.createEvent` which calls - you guessed it - `GetCampaign`. Oh no!

I blame past me.

Now let's fix that.

### Fixing the second problem

`GetCampaign` is called so that we can run `campaign.AddEvent`. But if we look at the [source](https://github.com/gophish/gophish/blob/0620671de60271265cf6e6131c47e8114aff8660/models/campaign.go#L157) of that function, we see that we only have it being a method on a campaign since we need the campaign ID.

Instead, we _could_ just move `AddEvent` into it's own function and accept the campaign ID as an argument:

```go
func AddEvent(e *Event, campaignID int64) error { .... }
```

Then, we can pass in the ID of the campaign that was already loaded.

Doing this removes that latency, making calls to `m.Success()` blazing fast. After all of this, I was able to send all 5,000 (not missing any) emails in roughly 3-5 minutes-ish.

Here's a sample of the logs:

```log
time="2020-01-26T22:32:19-06:00" level=info msg="Email sent" email="\"Bradley Potter\" <Bradley.Potter.54@example.com>" errorHandlingTiming=138ns errorTiming=13.74062ms generationTiming="332.557µs" resetTiming=934ns selectTiming=411ns successTiming=2.989589ms
time="2020-01-26T22:32:19-06:00" level=info msg="Email sent" email="\"David Fleming\" <David.Fleming.55@example.com>" errorHandlingTiming=149ns errorTiming=29.039962ms generationTiming="341.787µs" resetTiming=546ns selectTiming=198ns successTiming=3.31386ms
```

### Moving Forward

At this point, I think we have a good approach to move forward. I'd still like to do a bit more testing to make sure that we don't inadvertently break something, but I think we're in good shape.

I'm always open to helping you put up a PR with these changes so that you can show up as the committer if you'd like. Otherwise, I can post a PR, have you review it, then merge it in ASAP and make sure to credit you on the release notes. Whatever works for you works for me!

Thanks for all your patience on this one!

**Comment by edermi** [comment] 2020-01-27 20:41
Wow, that was really fast. **Thanks a lot** for getting this fixed within a few days.

Unfortunately I don't have the time for allocating a sufficient time slot to implement this and submit a PR within the next days. As you seem to have the code ready, I don't want to waste your time. I don't really insist on having my name attached to the git commit, so please go ahead :)

I will test and review the code once you made the pull request - maybe I have a few larger campaigns that are sufficient for testing within the next few weeks (no promises though!)

**Comment by jordan-wright** [comment] 2020-01-28 04:23
> Wow, that was really fast. Thanks a lot for getting this fixed within a few days.

It's easy when I only have to try and fix the problem since the root cause has already been tracked down and a detailed troubleshooting report is filed 😄 

I've pushed up some initial work in the `1726-sending-improvements` branch. If you'd like, you can check out this branch and re-run your experiments to see if performance is starting to meet your expectations.

While this is a great start and aims to take care of the processing side of things, I'd like to also do a bit of work reducing the memory usage since right now we temporarily cache the entire campaign into memory. This should still be better than it was since we were previously getting the entire campaign into memory for each email... twice... but I bet I can figure out a reasonably clean approach to only get the fields we need.

**Comment by jordan-wright** [comment] 2020-03-28 02:38
Hey @edermi!

Sorry for the late follow up! I think the issue is that in your demo code `fake.email()` won't give you 5,000 unique emails:

```
>>> from faker import Faker
>>> emails = []
>>> fake = Faker()
>>> for i in range(0, 5000):
...     emails.append(fake.email())
>>> len(emails)
5000
>>> len(set(emails))
4990
```

You can see here that just generating 5,000 emails resulted in 10 duplicates. Gophish will avoid sending emails to the same recipient twice to catch users that have the same email in multiple groups. One thing you can do to avoid this in your test code is to generate the index programmatically (e.g. `user-{i}@example.com`) and see if you still see the issue occur.

Give this a shot and let me know if you still see the issue happening. But the good news is that it appears Gophish is working as expected 🎊 With this being the case, I'm going to go ahead and close this one out, but *please* don't hesitate to let me know if you still see the issue occurring.

Thank you again for all your time and patience getting this resolved! I'm really excited about these improvements.

**Closed by jordan-wright** 2020-03-28 02:38 UTC
Labels: bug
