### ISSUE TITLE
"mail: unencoded non-ASCII text in address" Error

### ISSUE THREAD

**Issue by hakawati** [gophish/gophish#666] opened 2017-06-24 12:25 UTC
Good morning.
I do not doubt that this open source project will play a huge role in the future.

This time I am building open source to conduct phishing email diagnosis.
However, in order to deceive the user, it does not support Unicode when the name is set as follows.
How can I solve this problem?

![image](https://user-images.githubusercontent.com/8299191/27508584-59753320-5923-11e7-96df-bb7f7461cd9d.png)

Thanks for reading.

**Comment by jordan-wright** [comment] 2017-06-24 15:05
This appears to be a duplicate of #135. We'll continue to work through that issue on a resolution.

Thanks for the report!

**Closed by jordan-wright** 2017-06-24 15:05 UTC
