### ISSUE TITLE
Cannot send email 

### ISSUE THREAD

**Issue by orangemacaroon** [gophish/gophish#1338] opened 2019-01-07 20:58 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue: I created a new profile - SMTP microsoft. but when i tried to perform a test email it stuck on error message " Max connection attempts exceeded - dial tcp x.x.x.x:25: i/o timeout"

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```time="2019-01-07T13:57:06-07:00" level=error msg="Max connection attempts exceeded - dial tcp 52.96.26.162:25: i/o timeout"
time="2019-01-07T13:57:06-07:00" level=info msg="x.x.x.x - - [07/Jan/2019:13:55:50 -0700] \"POST /api/util/send_test_email?api_key=d820d9a2ad1228ec452e9236cae8af1b59d6833d386ecc541bb937abc2fe3437705 HTTP/2.0\" 500 127 \"https://x.x.x.x:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\""

Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2019-01-09 03:06
Hi @orangemacaroon,

It looks as though GoDaddy is blocking outbound SMTP connections [unless they go through their relay servers](https://www.godaddy.com/help/find-your-email-relay-server-122). This is a common practice to avoid abuse. I'd recommend working with GoDaddy support if you need to use their servers for phishing simulations with Gophish.

**Comment by orangemacaroon** [comment] 2019-01-09 13:41
@jordan-wright , will check the article. kindly let this issue be on open as i will update the community once i make progress :)

**Comment by jordan-wright** [comment] 2019-01-17 02:56
Hi @orangemacaroon,

I wanted to check-in on this- did you make any progress? I'd like to avoid keeping issues that we've found the root cause for open too long, if possible.

Thanks!

**Comment by orangemacaroon** [comment] 2019-01-18 12:15
@jordan-wright issue is still not resolved, but it is on GoDaddy VPS servers not any more on GoPhish

**Comment by jordan-wright** [comment] 2019-02-17 19:21
Hi @orangemacaroon,

Since there hasn't been any updates to this issue in more than a month, I'm going to go ahead and close it out.

**Closed by jordan-wright** 2019-02-17 19:21 UTC
Labels: support

**Comment by orangemacaroon** [comment] 2019-02-21 20:47
just to update here to fix the issue you just need to modify the relay server on gophish meeting the sending profile use the relay server of godaddy.
