### ISSUE TITLE
Starting gophish on boot

### ISSUE THREAD

**Issue by packetsmacker** [gophish/gophish#646] opened 2017-06-07 15:47 UTC
I don't know if this is the place to post this question. I don't use github a lot. A co-worker set up a gophish server  and we need to get this to start when the machine boots up. Its running Centos 7. How do I do this?

**Comment by S0larflare** [comment] 2017-06-07 16:37
You're best looking into init.d. There's plenty of stuff on the web that would explain it better than I would. If you're struggling though let me know and I'll see if I can help (mine is on RHEL 7, so it's essentially the same)

Sent from my iPhone

On 7 Jun 2017, at 16:47, packetsmacker <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know if this is the place to post this question. I don't use github a lot. A co-worker set up a gophish server and we need to get this to start when the machine boots up. Its running Centos 7. How do I do this?

**Comment by S0larflare** [comment] 2017-06-07 16:39
Actually, the moment I sent that I remembered someone had put together a little script to do it for you in #586 . Worth taking a look

**Comment by jordan-wright** [comment] 2017-06-07 17:01
Good call @S0larflare! You're right that this appears to be a duplicate of other issues, which is solved by #586. @packetsmacker I recommend reviewing and adapting that solution as needed to your use case.

For now, I'll close this one out since it appears to have a valid answer. Thanks everyone!

**Closed** 2017-06-07 17:01 UTC
Labels: duplicate, support
