### ISSUE TITLE
gophish internet facing issues in azure

### ISSUE THREAD

**Issue by rfalk347** [gophish/gophish#1470] opened 2019-05-30 17:32 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by rfalk347** [comment] 2019-05-30 17:39
using latest windows ver of gophish - have a windows server in azure internet facing - bought a domain close to companies - got certificates - isuue is when sending mail / campaign via smtp it makes it to my work or internal domains etc but will not say go out to a yahoo email account or a gmail account ect the test mail sends successful but only shows up in my company mailbox not my personal yahoo or gmail account - we want to send the campaigns out to employees not part of the regular domain as they may not be in that said domain does that make any sense - is it how we have it internet facing - our smtp - or in the config.json file????

**Comment by jordan-wright** [comment] 2019-05-30 19:31
This sounds like an issue with the SMTP server you're using to send the emails. All Gophish can do is send the emails to your SMTP relay who is responsible for making sure emails get where they should go.

If you don't see the emails showing up in the inbox outside the internal domain, you'll want to go check the logs of whatever SMTP server you're using, since that's likely where the issue is occurring.

I hope this helps! Since there isn't anything we can do in Gophish to help resolve this, I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2019-05-30 19:31 UTC

**Comment by rfalk347** [comment] 2019-05-31 11:18
Thank you Sir..
