### ISSUE TITLE
Inconsistent / Misleading Summary of Campaign

### ISSUE THREAD

**Issue by daver208** [gophish/gophish#2018] opened 2020-10-23 17:16 UTC
What version of Gophish are you using?: v0.9.0

Brief description of the issue:  Opening a phishing email again, after clicking, generates a status of 'Email Opened' after the user clicked on the link.  This causes the campaign overview to show less 'Clicked' users than I would expect.

What are you expecting to see happen? :  I would expect the Campaign summary to show the most serious Status for the campaign, not necessarily the most recent.   I would expect that 'Email Sent' < 'Email Opened' < 'Clicked Link' < 'Submitted Data'

What are you seeing happen?  The results in the Campaign dashboard are in our case showing one less person clicked the link than actually did.

Please provide as many steps as you can to reproduce the problem:
 * As stated it appears the user opened the email in their mail client again after clicking the link, which changed the status back to 'Email Opened' from 'Clicked Link'

This was a campaign of ~1400 Users.  The campaign summary is reporting one less clicker than the raw data export shows.  We are planning on updating our version of GoPhish to the most recent version but none of the issues / release notes seem to address this.

UPDATE: 2020.10.29

Cloned and diffed the repo. Links below show the function that is supposed to handle this didn't change between 0.9.0 and 0.11.0.  I did look throughout some other results and there were many other cases where users opened the email again after clicking but, gophish correctly categorized them as having clicked the link.  I'm leaning toward this is a race condition or a problem with the database transaction.

The comments in the code (links below) indicate that you are trying to handle this correct, but if you can look at my [next comment](https://github.com/gophish/gophish/issues/2018#issuecomment-715481791), I posted some timing information on the email opened vs email clicked events.

https://github.com/gophish/gophish/blob/v0.9.0/models/result.go#L98
https://github.com/gophish/gophish/blob/v0.11.0/models/result.go#L92

<img width="1366" alt="gophish_0 9 0_status_bug" src="https://user-images.githubusercontent.com/3308163/97033550-82fafe00-1531-11eb-88cd-fbb6efb4a542.png">

**Comment by daver208** [comment] 2020-10-23 17:43
Additional Context:

If you will note, it appears that a `Clicked Link` AND an `Email Opened` are being recorded at exactly the same time.
`10:51:21 am`

Depending on implementation this could cause a race condition that would cause this issue.  It would also be pretty difficult to replicate.

**Comment by namanagrawal94** [comment] 2020-10-29 15:26
Did you add Tracking image in youremail template?

**Comment by daver208** [comment] 2020-10-29 20:38
Yes we had a tracking image in the campaign.

**Comment by namanagrawal94** [comment] 2020-10-30 02:41
Which email client are you using?

Did all the images from the email load after you open the email?

**Comment by daver208** [comment] 2020-10-30 10:49
@namanagrawal94 This was a phishing campaign, the user who clicked this phish was using:
Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)

We've run several other phishing campaigns that have not had a result like this.  Since the 'Email Opened' status is happening so many times, it seems very likely that the images did indeed load in their mail client or we would never have seen any / that many 'Email Opened' status updates.

**Comment by glennzw** [comment] 2021-03-06 22:20
Hi @daver208, I've tried reproducing this but your desired behaviour is what I'm getting. i.e. if a user opens an email, then clicks a link then opens the email again the 'Clicked Link' remains the status in the summary bar:

![Screenshot 2021-03-06 at 22 10 54](https://user-images.githubusercontent.com/3966613/110222283-f8f07800-7ec8-11eb-8dcc-949ca23d02ed.png)


This was generated via:

```
curl http://localhost/track?rid=yNb6lg8 # Simulate opening email
curl http://localhost/?rid=yNb6lg8 # Simulating clicking the link in the email
curl http://localhost/track?rid=yNb6lg8 # Simulate opening the email for a second time
curl http://localhost/track?rid=yNb6lg8 # Simulate opening the email for a third time
```

This is using version 0.11, perhaps you're not on the latest version?

Also FYI regarding this comment:

> The comments in the code (links below) indicate that you are trying to handle this correct, but if you can look at my next comment, I posted some timing information on the email opened vs email clicked events.
> https://github.com/gophish/gophish/blob/v0.9.0/models/result.go#L98
> https://github.com/gophish/gophish/blob/v0.11.0/models/result.go#L92

It's a little tricky, but the labels/etc are generated client side in Javascript in the [campaign_results.js](https://github.com/gophish/gophish/blob/master/static/js/src/app/campaign_results.js)

Specifically, there is a '[priority queue](https://github.com/gophish/gophish/blob/master/static/js/src/app/campaign_results.js#L110
)' of sorts that determines the 'severity' levels of different events:


```
var progressListing = [
    "Email Sent",
    "Email Opened",
    "Clicked Link",
    "Submitted Data"
]
```

What this means is that what's seen in the web UI can often differ from what you see in the database, or see in an exported .csv file.

If you're still getting this issue on the latest gophish version could you help me reproduce it?

**Comment by daver208** [comment] 2021-03-08 21:43
@glennzw As I mentioned this is the first time I've seen this behavior in the approximately 6 campaigns I've been involved with.  I currently don't have a lot of free cycles to help replicate this but, I did query the gophish API with the following query and response.....  I don't think this is an issue with the visualization, It appears to just be mirroring the `results` array field from the GoPhish API in 0.10.1.


```
# NOTE the ALL CAPS env variables
curl -s -H "Authorization: $AUTH_KEY" https://$GOPHISH_URL:3333/api/campaigns/ | jq -S 'map(del(.template,.page)) | .[] | select(.id as $i | [$CAMPAIGN_ID] | index($i) ) | .results[] | select (.email == "someone@example.com")'
{
  "email": "someone@example.com",
  "first_name": "redacted",
  "id": "V0vsBvb",
  "ip": "redacted",
  "last_name": "redacted",
  "latitude": 0.0,
  "longitude": 0.0,
  "modified_date": "2020-10-19T14:53:17.906934147Z",
  "position": "",
  "reported": false,
  "send_date": "2020-10-19T12:01:31.50776439Z",
  "status": "Email Opened"
}
```

**Comment by glennzw** [comment] 2021-03-10 10:34
Hi @daver208, thanks so much for the detailed reply. It's a real tricky one; perhaps your idea with the race condition is the reason. I'll try replicate on my side with your handy curls and dig our the root cause.

**Comment by daver208** [comment] 2021-03-10 13:06
@glennzw I have a feeling that replicating this will be difficult with a script simply because of nature of race conditions...  Also this is a simpler script for a single campaign, the above was something I saved so I could parse multiple campaigns.  This will select all records from both `results` and `timeline` with the given `email`. 

NOTE: the /10 is campaign 10

```
export AUTH_KEY=AUTH_KEY
export GOPHISH_URL=localhost
curl -sk -H "Authorization: $AUTH_KEY" "https://$GOPHISH_URL:3333/api/campaigns/10" | jq '{results, timeline} | .results[], .timeline[] | select ( .email == "someone@example.com")'
{
  "email": "someone@example.com",
  "first_name": "redacted",
  "id": "V0vsBvb",
  "ip": "redacted",
  "last_name": "redacted",
  "latitude": 0.0,
  "longitude": 0.0,
  "modified_date": "2020-10-19T14:53:17.906934147Z",
  "position": "",
  "reported": false,
  "send_date": "2020-10-19T12:01:31.50776439Z",
  "status": "Email Opened"
}
{
  "details": "",
  "email": "someone@example.com",
  "message": "Email Sent",
  "time": "2020-10-19T12:01:31.50776439Z"
}
{
  "details": "{\"payload\":{\"rid\":[\"V0vsBvb\"]},\"browser\":{\"address\":\"redacted\",\"user-agent\":\"Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)\"}}",
  "email": "someone@example.com",
  "message": "Email Opened",
  "time": "2020-10-19T14:51:21.87321343Z"
}
{
  "details": "{\"payload\":{\"rid\":[\"V0vsBvb\"]},\"browser\":{\"address\":\"redacted\",\"user-agent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363\"}}",
  "email": "someone@example.com",
  "message": "Clicked Link",
  "time": "2020-10-19T14:51:21.883216467Z"
}
{
  "details": "{\"payload\":{\"rid\":[\"V0vsBvb\"]},\"browser\":{\"address\":\"redacted\",\"user-agent\":\"Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)\"}}",
  "email": "someone@example.com",
  "message": "Email Opened",
  "time": "2020-10-19T14:51:21.873774267Z"
}
{
  "details": "{\"payload\":{\"rid\":[\"V0vsBvb\"]},\"browser\":{\"address\":\"redacted\",\"user-agent\":\"Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)\"}}",
  "email": "someone@example.com",
  "message": "Email Opened",
  "time": "2020-10-19T14:52:35.096536447Z"
}
{
  "details": "{\"payload\":{\"rid\":[\"V0vsBvb\"]},\"browser\":{\"address\":\"redacted\",\"user-agent\":\"Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)\"}}",
  "email": "someone@example.com",
  "message": "Email Opened",
  "time": "2020-10-19T14:53:17.906934147Z"
}
```

**Comment by glennzw** [comment] 2021-12-15 16:39
@daver208 I'm just going through old issues, and wondering if you had any further luck fixing or debugging this?

**Comment by daver208** [comment] 2021-12-15 18:51
> @daver208 I'm just going through old issues, and wondering if you had any further luck fixing or debugging this?

@glennzw We haven't had it happen again, which makes me think we did indeed hit some sort of strange race condition.  If you want to close the issue, I understand.  I did want to document it in case someone else saw it in the future....

Thanks!

Dave

**Comment by glennzw** [comment] 2021-12-17 13:32
OK thanks for the update @daver208. I'll close this for now, but feel free to reopen if you run into it again or want to add more info. The issue will remain searchable in case someone else bumps into the same problem in the future.

**Closed by glennzw** 2021-12-17 13:32 UTC
