### ISSUE TITLE
Send email error

### ISSUE THREAD

**Issue by anhtvd** [gophish/gophish#253] opened 2016-04-25 08:36 UTC
Hi!
Thanks for your tool!
When I send test emai I got an 'EOF' error.
Could you please tell me Why i get this error and how to fix it?
Thanks!
I use smtp.gmai.com:465.

**Comment by jordan-wright** [comment] 2016-04-30 01:58
We'll need to know more about your configuration.. Can you give us an example of the template you are using?

Do you see any error messages in the console when sending the emails?

**Comment by MichaelWolljung** [comment] 2016-05-19 19:55
Hello Jordan.
First of all, thanks for your initiative. I'm trying to use your tool but I encounter the same problem mentioned above. See the error in the console: 

2016/05/19 21:30:03 worker.go:186: Creating email using template
2016/05/19 21:30:03 worker.go:227: Sending Email to ***.***@***.fr
2016/05/19 21:35:03 worker.go:230: EOF
127.0.0.1 - - [19/May/2016:21:30:03 +0200] "POST /api/util/send_test_email?api_key=*** HTTP/1.1" 500 58 "http://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"

The sending profile I was trying to use was on ssl0.ovh.net:465.
If you need more info to troubleshoot, I can reproduce the error, please tell me.

**Comment by b3nny0** [comment] 2016-05-20 14:35
Hi Michael...I might have figured this out.  I was using gmail as my relay on port 465 and was getting the same error.  I changed the port to 587 and it worked.  Here is the article i referenced.

http://stackoverflow.com/questions/11662017/smtp-sendmail-fails-after-10-minutes-with-eof

Let me know if that works for you

**Comment by MichaelWolljung** [comment] 2016-05-21 11:23
Hey b3nny0. That was exactly the problem. When I use the port 587, it works just fine. Thank you very much for your help!

**Comment by jordan-wright** [comment] 2016-05-25 23:11
It looks like this is fixed by changing the port to 587. I'm going to go ahead and close this out for now.

Thanks for the community support! Great stuff!

**Closed by jordan-wright** 2016-05-25 23:11 UTC
Labels: support
