### ISSUE TITLE
Statistics on dashboard are wrong.

### ISSUE THREAD

**Issue by suffestuffie** [gophish/gophish#589] opened 2017-04-10 08:30 UTC
Hi,

Last week, we successfully completed a phishing campaign to 4500 employees. The program works great and we found only one issue: 

According to our calculations, the donut on the dashboard shows "clicked links" and not "successful phishes". The donuts on the campaign pages are correct.

Thanks for providing this excellent program!

**Comment by S0larflare** [comment] 2017-04-10 08:40
Anybody who clicks the link is counted as a successful phish. To a degree this is a symptom of an earlier build where it was simple success/email sent within a campaign, but where you could get a breakdown if you downloaded the csv or used the api. This was changed a few months ago so that the campaign side shows a better breakdown of what has happened.

That said, I personally would regard a click as a successful phish. If i'm trying to phish someone, I am not necessarily trying to get their details. By clicking you may have just infected your computer with something, I can do recon then and find more about your pc or your organization, it might get me a foothold. To be honest, if nothing else, you've just confirmed that your email address if valid...

**Comment by suffestuffie** [comment] 2017-04-10 08:51
OK, then it is just a matter of opinion. Maybe it is better to show both "clicked links" and "submitted data" on dashboard.

**Comment by jordan-wright** [comment] 2017-04-10 12:20
What version of Gophish are you running? The latest binary release fixed that issue and now shows clicked links and submitted data.

**Comment by suffestuffie** [comment] 2017-04-10 12:32
I was using 0.3 binaries. The dashboard does not show clicked links, the campaign statistic pages does.

![img-20170406-wa0005](https://cloud.githubusercontent.com/assets/26000951/24861833/6d03a426-1dfa-11e7-8118-f711e360eafc.jpg)

**Comment by jordan-wright** [comment] 2017-04-10 14:17
Ohhhh, I see what you mean. I can fix that. Thanks for the heads up!

**Comment by jordan-wright** [comment] 2017-06-18 22:34
Good news! This has been fixed in https://github.com/gophish/gophish/commit/80c68194a63ac1535479b3cfc67e1df4bca4594c.

The new dashboard chart looks like this:

![image](https://user-images.githubusercontent.com/1317288/27264791-52cda006-544c-11e7-9831-f127b9fffe6f.png)

Let me know if you run into any issues!

**Closed by jordan-wright** 2017-06-18 22:34 UTC
