### ISSUE TITLE
Admin server and phish server in different location

### ISSUE THREAD

**Issue by ferreirasc** [gophish/gophish#599] opened 2017-04-21 13:36 UTC
Ok, the title says everything.

Is it possible to keep the admin server and phish server in different locations?

Example:

"phish_server" -> "192.168.3.94:80"
"admin_server" -> "192.168.3.15:3333"

Thx! :-)

**Comment by jordan-wright** [comment] 2017-04-21 14:31
This appears to be a duplicate of https://github.com/gophish/gophish/issues/558. Let us know if that issue answers your question.

Thanks!

**Comment by ferreirasc** [comment] 2017-04-21 14:49
Ah... ok! That's what i thought (both hosts share the same database). 

I will try to figure out how to expose database for both servers. Any suggestion?

Thanks

**Comment by jordan-wright** [comment] 2017-04-21 15:03
If you use mysql you can just set it up on one of the hosts listening on all interfaces (0.0.0.0:3306) and then point the hosts to it.

**Comment by ferreirasc** [comment] 2017-04-21 15:21
Ya, it worked for me.

You can close it. :D

**Closed** 2017-04-25 01:34 UTC
