### ISSUE TITLE
No valid version found

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#1046] opened 2018-04-18 19:14 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
latest version just downloaded it 

Brief description of the issue: 
Im running gophish and getting the following error "models.go:98 no valid version found models.go:77 no valid version found

What are you expecting to see happen? :
gophish to run
What are you seeing happen?
error message 
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```


Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Paddyk3ll3h3r** [comment] 2018-04-18 19:15
![capture](https://user-images.githubusercontent.com/32489324/38952957-186cfb28-4302-11e8-86de-3cf171f1fb3c.PNG)

the following is a screenshot of the config.json file and the error message im getting

**Comment by jordan-wright** [comment] 2018-04-19 01:45
What are the contents of the `gophish-v0.5.0-windows-64bit` folder? It's looking like it's missing the `db` folder.

**Comment by Paddyk3ll3h3r** [comment] 2018-04-19 10:17
![capture](https://user-images.githubusercontent.com/32489324/38986070-29b7ffbc-4380-11e8-939d-9764bdb106a5.PNG)
db folder is present

**Comment by jordan-wright** [comment] 2018-04-19 14:02
It’s looking like it’s having trouble connecting to the database. I see the port in the MySQL connection string is 3333. I believe the default port for MySQL is 3306. Gophish is the service listening on 3333 so I don’t think the url you have in there now will work.

You need to change that connection string to point to your instance of MySQL.

**Comment by Paddyk3ll3h3r** [comment] 2018-04-20 11:50
I changed the port number to 3306 but it made no difference

**Comment by thryb** [comment] 2018-04-20 12:51
Could you please run the following command and post the result
netstat -a -b | findstr 3306
You will need an elevated prompt.

**Comment by Paddyk3ll3h3r** [comment] 2018-04-20 13:10
![capture1](https://user-images.githubusercontent.com/32489324/39052608-77dc35f0-4461-11e8-80b5-33c62d351453.PNG)
doesnt seem to give anything back

**Comment by thryb** [comment] 2018-04-20 13:10
Then your instance of MySQL isn't running. This would be your problem.

Cheers :)

**Comment by Paddyk3ll3h3r** [comment] 2018-04-20 13:27
this freaking error message has delayed me a week now, im doing this project for college

**Comment by thryb** [comment] 2018-04-20 13:31
You are also missing a coma after your db_path in your config.

**Comment by thryb** [comment] 2018-04-20 14:00
You're welcome? ...

**Comment by Paddyk3ll3h3r** [comment] 2018-04-20 14:06
Nicely spotted! i had it working, closed the command line and tried again and i got this error? im guessing its something small as it was just working? 
![capture1](https://user-images.githubusercontent.com/32489324/39055521-50ac9e22-4469-11e8-8d58-0e974717756b.PNG)

**Comment by Paddyk3ll3h3r** [comment] 2018-04-20 14:06
sorry wrong screenshot 
![capture](https://user-images.githubusercontent.com/32489324/39055563-691622f8-4469-11e8-9660-197539a44788.PNG)

**Comment by thryb** [comment] 2018-04-20 14:10
#948 talk about this issue.

**Comment by S0larflare** [comment] 2018-04-20 14:11
This is referenced in [Issue 948](https://github.com/gophish/gophish/issues/948). Can you build from the latest source? I'm not sure if that fix has been incorporated in to a release yet

**Comment by jordan-wright** [comment] 2018-04-21 02:04
To be honest, unless you have a clear reason to use MySQL, it might be easier to just stick with SQLite. Don't be fooled - SQLite is actually a really solid database for many needs, Gophish included.

Since you mention this is for a college course, I think the real value here won't be getting Gophish up and running, but rather seeing how we can use information available to troubleshoot issues. This is something that you'll run into _all the time_ in infosec during your career.

In this case, let's see how we could troubleshoot this so that next time it doesn't take up a week of your time. To start, we have a goal: we want to use MySQL instead of SQLite. The first step should always be the docs and any other supporting information (such as Github Issues!) that could give us a direction.

Once we know what we think we should do (e.g. change the config values to the MySQL url and change the engine to "mysql"), we can give it a shot. In this case, it didn't work.

But, we're given more information to go off of:

```
models.go:98 no valid version found
gophish.go:77 no valid version found
```

So we have the error message that _might_ be useful, and we have the place in the code where it happens. The error message doesn't seem to help us too much off the bat, so let's [jump into the code](https://github.com/gophish/gophish/blob/master/models/models.go#L98). We can see that it's right in the middle of database migrations and establishing a database connection.

We can use this to narrow down the problem: something's wrong with setting up our database.

At this point, let's take Gophish out of the picture. Is our database working correctly? We can do this using the `mysql` client to check our connection. If our database is up, do we have the correct URL? Can we use that same URL to establish the connection using something other than Gophish?

This would have shown you that the port is incorrect and, when that was fixed, would have shown you that the database wasn't created.

Then, once the database is back up and running and we've confirmed things look good outside of Gophish, we can give Gophish a shot again. At this point, you'll see the `Duplicate admin` error. This isn't immediately obvious, so we can search the issues again where we'll find #948.

The information in the issue is correct - this has been fixed but a new release hasn't been pushed. I'll get that done next week. But the point of this is simply that there's a bunch of information we can use to troubleshoot problems and work our way towards a solution. This is far more handy of a skill to have than being able to get software up and running. In fact, this is exactly what everyone in the community does to help troubleshoot new issues. It's all about asking the right questions and using all the information available to find a solution.

Hope this helps! Let me know if you have any questions.

**Comment by Paddyk3ll3h3r** [comment] 2018-04-21 02:25
Cool thanks, originally I was planning to stick to Sqlite but i'm designing this for a company as a part of my college degree and they use all mysql databases. I downloaded the master version on the github page and dragged the .exe and db files into it and it ran perfectly except i got a bunch of warnings about the database. Ill prob stick to version 3 as that seems to be the best option my mysql

**Comment by jordan-wright** [comment] 2018-04-21 16:09
Since we've determined the cause (misconfigured MySQL connection) and you've decided to move forward with 0.3 for now, I'm going to go ahead and close this out. 

Thanks for reaching out!

**Closed by jordan-wright** 2018-04-21 16:09 UTC
Labels: support
