### ISSUE TITLE
Sending Email issue

### ISSUE THREAD

**Issue by mkannan22** [gophish/gophish#109] opened 2016-02-01 16:28 UTC
When I attempt to send an email I am getting a "certificate signed by unknown authority" message. Any advice on how to resolve?

running windows 10

**Comment by jordan-wright** [comment] 2016-02-01 16:42
Ah, yes, that's a known issue. I have an open issue on my email library to allow you to override this.

Basically, the underlying SMTP connection is trying to negotiate TLS with the server, and the cert CA is not trusted by your machine.

The next release will allow you to override this to ignore cert errors.

**Comment by mkannan22** [comment] 2016-02-01 16:44
Thanks. Any timeline (days, months)?

**Comment by jordan-wright** [comment] 2016-02-01 17:50
A temporary workaround would be to install the CA certificate that signed your mail server cert as a trusted CA.

The other option is to disable TLS on your mail server, but if this is a non local mail server that is actually used to deliver mail, I wouldn't recommend it.

**Comment by jordan-wright** [comment] 2016-02-02 01:52
For now, I'm going to go ahead and close this as a duplicate of #77 - we'll track the status of the fix through that issue.

Thanks for the report!

**Closed by jordan-wright** 2016-02-02 01:52 UTC
Labels: duplicate
