### ISSUE TITLE
Can't access html file in endpoint folder

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#1219] opened 2018-10-01 15:52 UTC
What version of Gophish are you using?: 0.6.0

Brief description of the issue: I'm trying to host an html file on the endpoint folder in gophish. Nevertheless, I can't access this html file. I tried to acess an img in this same folder and it's working.

What are you expecting to see happen? : Display the html file.

What are you seeing happen? 404 page not found

**Comment by jordan-wright** [comment] 2018-10-01 22:09
Hi @Cycl0pe,

Thanks for reaching out! To verify, the HTML file will need to be in your `endpoint` directory, e.g. `static/endpoint/your_file.html`. Then, you can reference it with:

```
<a href="http://your_phish_server/static/your_file.html">Link</a>
```

It's important to note that you must be hitting the phishing server port, not the admin server. I've confirmed this works with the latest version (v0.7.1) so you may try upgrading if you continue to run into issues.

For now, I'll go ahead and close this out since hopefully this will help resolve the problem. If you continue to run into issues, if you could provide more information about your directory structure, how you're referencing the HTML file, etc., then that will help us continue troubleshooting and I can re-open the issue.

**Closed by jordan-wright** 2018-10-01 22:09 UTC

**Comment by Cycl0pe** [comment] 2018-10-08 08:59
Hi @jordan-wright ,

My file was named "index.html" and when I changed it to another name, it worked. I don't know why!
