### ISSUE TITLE
Send test email failed on first try.

### ISSUE THREAD

**Issue by jepunband** [gophish/gophish#1368] opened 2019-02-20 03:33 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  
0.7.1

Brief description of the issue: 
Send test email failed on first try.

What are you expecting to see happen? :
send test email successful.  (my username and password are correct)

What are you seeing happen?
Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials s1sm14066057pgv.30 - gsmtp

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  Sending Profiles tab, New Profile , Send Test Email.
 * Step 2 - host is smtp.gmail.com:587
 
also did some research on gmail, please confirm:
https://docs.mailpoet.com/article/61-sending-with-gmail-doesnt-work

**Comment by jordan-wright** [comment] 2019-02-20 03:39
Hi @jepunband,

Thanks for reaching out! Did you try all the troubleshooting steps listed in Step 2 of that article linked in the error message? This is Google saying that it's not accepting the provided username and password. It may be required to use an app password, or to set up your settings to allow "less-secure applications".

I'm afraid that either way, this doesn't appear to be an issue with Gophish itself, since it's just sending up whichever username and password you're providing.

**Comment by jepunband** [comment] 2019-02-20 04:20
@jordan-wright , i tried the solutions presented here :
https://support.google.com/mail/?p=BadCredentials

It didn't work.

**Comment by jepunband** [comment] 2019-02-20 06:45
so i have registered for smtp email at Easy-SMTP from ReachMail!, they have given Port: 25, 2525, 587, or 465 to be used. Email still not sending out. it is stuck at sending at "Send Test Email" .. no error messages ..just waiting at "sending"..

**Comment by jordan-wright** [comment] 2019-03-03 21:45
Hi @jepunband,

Sorry for the delay getting back to you.

As mentioned in the earlier comment, this is still an error being presented from Gmail. There isn't anything we can do in Gophish to prevent Gmail from denying the credentials you're providing.

Since there really isn't anything we can do in Gophish to fix this, I'm going to go ahead and close this one out. I recommend reviewing the recommendations Google provides again just to make sure all their suggestions are in place.

**Closed by jordan-wright** 2019-03-03 21:45 UTC
Labels: support

**Comment by BitByte0** [comment] 2020-05-28 16:08
The problem is not Gophish but Gmail account configuration.

The solution is:

1. Send a email to your own gmail account from gophish
2. You will see a new email in gmail, review it.  It says the reason why it is blocked the access to your account from different gmail account.
3. Inside your google account, deactivate the options "less secure app access"
4. Probe Gophish again!
