### ISSUE TITLE
Dashboard update Errors

### ISSUE THREAD

**Issue by GBvenkatesh** [gophish/gophish#1066] opened 2018-05-16 10:45 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**
![inkedscreenshot from 2018-05-15 01-27-59_li](https://user-images.githubusercontent.com/31404259/40112606-2ce54a4a-5939-11e8-884b-9139fbc5dccb.jpg)

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0 Linux 64 Bit 

Brief description of the issue: Results and Event status is not in synch

What are you expecting to see happen? : Dashboard update to date 

What are you seeing happen? Dashboard show some incorrect data

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2018-05-16 13:41
Thanks for reaching out! It looks like this is a duplicate of #1065 filed yesterday so we'll close this one out to help consolidate the issues.

Thanks again!

**Closed by jordan-wright** 2018-05-16 13:41 UTC

**Comment by GBvenkatesh** [comment] 2018-05-18 05:35
Hi Jordan,

Also in the same campaign, multiple instances of emails have been triggered by the same email address.
