### ISSUE TITLE
Bloodhound for auto suggestions is not working

### ISSUE THREAD

**Issue by anoopabbu** [gophish/gophish#653] opened 2017-06-12 11:59 UTC
Auto suggestion is not working. I am using it with Gophish framework written in go language. Here is my code.
    
    // template searchin
           template_bh = new Bloodhound({
                datumTokenizer: function(e) {
                    return Bloodhound.tokenizers.whitespace(e.template_details.name)
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: []
            }), template_bh.initialize(), $("#template.typeahead.form-control").typeahead({
                hint: !0,
                highlight: !0,
                minLength: 1
            }, {
                name: "templates",
                source: template_bh,
                templates: {
                    empty: function(e) {
                        return '<div class="tt-suggestion">No templates matched that query</div>'
                    },
                    suggestion: function(e) {
                        return "<div>" + escapeHtml(e.template_details.name) + "</div>"}}
}).bind("typeahead:select", function(e, a) {
     $("#template").typeahead("val", a.name)
}).bind("typeahead:autocomplete", function(e, a) {
      $("#template").typeahead("val", a.name)
}),

**Comment by jordan-wright** [comment] 2017-06-12 12:48
What browser are you using? What do you see in the browser developer tools console when you try to use it?

**Comment by anoopabbu** [comment] 2017-06-12 13:30
I am using it on Chrome and Firefox. It give me empty msg "no match at this query".

**Comment by jordan-wright** [comment] 2017-06-12 22:49
I don't think Gophish is using Bloodhound anymore for typeahead autosuggestions. I'm pretty sure it was all moved to Select2 drop downs in the latest release.

Regardless, there isn't enough information here to help troubleshoot. Where are you typing? What do you expect to happen? What templates are loaded? What do you see in the developer tools console? What version of Gophish are you using?

The more information you can provide, the easier it is for us to troubleshoot the issue. Also, if you aren't already, make sure you're upgraded to the latest version since I'm almost positive the typeahead integrations are gone.

**Comment by jordan-wright** [comment] 2017-06-15 01:09
I've confirmed that I can't find any other instances of bloodhound in Gophish on the source branch, so this doesn't appear to affect the latest release.

@anoopabbu - if you are confirmed to be using the latest version, if you could provide a screenshot it'll help us narrow down the cause. Until then, I'm going to go ahead and close this one out.

**Closed by jordan-wright** 2017-06-15 01:09 UTC

**Comment by anoopabbu** [comment] 2017-06-15 04:25
Hi Jordan,

I have fixed this issue by my end. Thanks for your valuable time.
