### ISSUE TITLE
Need Help in configuring my campaign 

### ISSUE THREAD

**Issue by GBvenkatesh** [gophish/gophish#1004] opened 2018-03-11 08:58 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.5.0 

Brief description of the issue: **Its not an issue, Need assistance on the configuring campaign.**

What are you expecting to see happen? **Dashboard results getting updated with results** 

What are you seeing happen? Not able to get the status of the email opened and link clicked

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
**My email template**
Hi,

Click on the below link to activate the reset password link 

http://10.10.14.5/
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I am trying this on a Virtual box environment. configured a internal network with 3 machines running as mentioned below 
a. 10.10.14.4 - Gophish Server 
b. 10.10.14.5 - web server 
c. 10.10.14.6 - Machine to access email

Landing Page = http://10.10.14.5/ - i am able to reach the server from 10.10.14.6
URL = http://10.10.14.4 - Gophish is running - do i need to config this as listening sever ?

I am launching the campaign with above config. Email is sent and the dashboard is updated, however the link opened status is not updated. I could see email is sent the dashboard is responding the same 

1. what should be my listening server and URl ?
 * Step 2 -

**Comment by S0larflare** [comment] 2018-03-12 08:01
I suggest that you read the [User Guide](https://gophish.gitbooks.io/user-guide/content/) as this is explained really well in there. You want to be using {{.URL}} rather than the IP address itself, put the IP address/hostname/url of your gophish server to the campaign url when setting it up:

![image](https://user-images.githubusercontent.com/8939757/37271622-81d53bba-25cb-11e8-9295-3cbc91323da9.png)


This should mean that when the link is clicked in your phishing email, they will be served the landing page you have created and defined and the dashboard will be updated accordingly.

**Comment by GBvenkatesh** [comment] 2018-03-12 09:44
Thank you so much for your responses. I just figured it out and its reporting me the status.
Got confused with the examples in the user guide.

User Guide!
**Most of the settings should be self-explanatory. The only thing to look out for is the URL field. Since the IP address of our Gophish server is 192.168.1.1, that's what we'll use:**

However on the image reference provided below it says 

![image](https://user-images.githubusercontent.com/31404259/37276466-b845fd6e-261c-11e8-9d7a-758557f07004.png)

**http://192.168.56.1**

this is where i got confused! my bad! 
But thanks for all the support and its an awesome tool.
Is there any option to evade the outlook from alerting this as a phishing email ?

**Comment by jordan-wright** [comment] 2018-03-12 23:10
Hi @GBvenkatesh - glad to hear you were able to get it worked out!

There aren't any options within Gophish to prevent outlook from flagging phishing emails. This is a defense in outlook that's working as intended. The only things you could try would be to whitelist the Gophish IP address in the Exchange settings, or modify the content of your emails. Neither of these are things we can provide under the scope of our support.

Since the original issue has been resolved, I'm going to go ahead and close this one out. Thanks again for getting in touch!

**Closed by jordan-wright** 2018-03-12 23:10 UTC
