### ISSUE TITLE
The Hyperlink doesn't work on mobile

### ISSUE THREAD

**Issue by kartikrajus** [gophish/gophish#449] opened 2016-11-24 09:19 UTC
The hyperlink created in gophish is wroking fine when recepients are opening the test phish through laptop but the same link doesn't work on mobile (Android). All it opens is a blank page.

What can we do to make this link clickable on mobile mail client?

Thanks,
Raj

**Comment by jordan-wright** [comment] 2016-11-24 17:42
Not sure what you mean by this.. is this for all landing pages or only a specific one? What do you see in the terminal output when you click the link from a mobile device?

Gophish just returns whatever HTML you set in the Landing Page, so if it has mobile compatibility issues, there isn't really anything gophish can do about it.

**Comment by Grapkano** [comment] 2016-11-24 17:52
Hi Jordan, I ran into this problem together with kartikrajus. The phishing link works fine with Outlook clients on a laptop but when you click the link on a mobile device it directs to a blanc page. Landing page is accessible by mobile in browser, just that clicking the link doesnt work for some reason.

**Comment by jordan-wright** [comment] 2016-11-24 18:04
What if you use a barebones template- something with nothing but a link. Does this still reproduce the issue? Im just struggling to see a reason why this would happen that isn't dependent on the template content.

What does the terminal output say when the mobile device clicks the link?

**Comment by Grapkano** [comment] 2016-11-24 18:11
Tried the link in outlook web access and it works..outlook client on phone=no dice. We're also struggling to understand why this happens.

**Comment by jordan-wright** [comment] 2016-11-24 18:16
The logs would tell us what's going on. If you could copy/paste the terminal output after you click the link with both clients, I bet we can get to the bottom of it.

**Comment by kartikrajus** [comment] 2016-11-25 08:17
Hi Jordan,

As this link doesn't open in the browser, there are no terminal output. Can this be related to the html code? The current HTML code is below for your quick review;

<p>All <strong>MUST </strong>acknowledge receiving notification of the new policy&nbsp;framework: <a href="{{.URL}}">CLICK HERE&nbsp;</a>to confirm the receipt of this email.</p>

Also, just fyi when I transfer this link to Whatsapp messenger, its works absolutely fine.

Thanks for your kind support.

**Comment by jordan-wright** [comment] 2016-11-26 23:20
When you say the link doesn't open in mobile, what do you mean it doesn't open? The link exists, and you can click on it, right?

What is the URL you see when you hover over the link? What is the URL in the browser when the link is clicked?

**Comment by Grapkano** [comment] 2016-11-27 08:43
Browser opens a blank page (about:blank) when the link is clicked in the Outlook client. Clicking it in Gmail client, Outlook web client etc does work.

**Comment by kartikrajus** [comment] 2016-11-28 13:05
Hi Jordan,

I tested this link on multiple client and browsers. It works absolutely fine everywhere but doesn't work on the MDM outlook client possibly because of the security settings where unsafe links, which are with some special character viz. ":" may have some restrictions and drops.

I'm sure, reducing the security settings of MDM client would never be an option and others would also be facing this issue would they be using secured MDM solution with such default policy enabled.

Is there a way we can avoid this special character in gophish?

Thanks !

**Comment by jordan-wright** [comment] 2016-11-28 14:09
Whoa - that's odd. Do you have a link to some documentation? I'd like to read more about that.

Why does your URL have a colon in it? If you are using the default port 80 for your gophish server, you don't need to specify a port in your URL.

**Comment by kartikrajus** [comment] 2016-11-28 16:19
The current configuration is running on 8083. I shall try to change this to port 80 and try.

Few links related to URL coding;

http://www.w3schools.com/tags/ref_urlencode.asp
http://www.werockyourweb.com/url-escape-characters/
http://www.blooberry.com/indexdot/html/topics/urlencoding.htm
https://github.com/deanoemcke/thegreatsuspender/issues/46

**Comment by kartikrajus** [comment] 2016-11-29 10:40
Hi Jordan, thanks for all the support. Hope, the links have some good reference.

The link is working absolutely fine and I can confirm that this issue was because of ":" into the URL which was considered unsafe link to be opened and same is restricted in MDM solution that we are using.

Meaning, those experiencing this problem must use default port:80 to avoid this issue.

**Comment by S0larflare** [comment] 2016-12-01 14:06
That's interesting, can I ask what MDM you're using?

**Comment by jordan-wright** [comment] 2016-12-06 02:45
Going ahead and closing this for now since the root cause was not directly in gophish's control.

Thanks for the excellent analysis and discussion! Feel free to keep chatting about the issue here- I'm just closing it so that we know there isn't outstanding work to be done to resolve it.

**Closed by jordan-wright** 2016-12-06 02:45 UTC

**Comment by Joan1989** [comment] 2018-04-19 05:44
i also have this problem on my web: [https://top10listguide.com/](https://top10listguide.com/), you can add this(article { z-index:1; } ) in the css.
