### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by fresh07** [gophish/gophish#947] opened 2018-01-29 06:32 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  20171208201932

Brief description of the issue: 

What are you expecting to see happen? : when I type in 127.0.0.1:3333 the application should load in the browser

What are you seeing happen? 2018/01/29 01:22:50 http: TLS handshake error from 127.0.0.1:51129: tls: first record does not look like a handshake
ecord does not look like a TLS handshake

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: no, i dont reach this stage

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment] 2018-01-29 09:18
Try https://127.0.0.1:3333

Sent from my iPhone

On 29 Jan 2018, at 06:32, fresh07 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: 20171208201932

Brief description of the issue:

What are you expecting to see happen? : when I type in 127.0.0.1:3333 the application should load in the browser

What are you seeing happen? 2018/01/29 01:22:50 http: TLS handshake error from 127.0.0.1:51129: tls: first record does not look like a handshake
ecord does not look like a TLS handshake

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: no, i dont reach this stage

Insert code here

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by davidfornesm** [comment] 2018-01-29 23:22
This issue was opened by me, and was then solved. As stated in the docs use https! S0larflare's solution should perfectly work...

**Comment by jordan-wright** [comment] 2018-01-30 03:30
As @davidfornesm and @S0larflare mentioned, this is almost certainly due to connecting via HTTP, not HTTPS.

Since this is a common problem with this as the solution, I'm going to go ahead and close this out. @fresh07 let us know if this doesn't fix the issue and we can always re-open.

Thanks for getting in touch!

**Closed by jordan-wright** 2018-01-30 03:30 UTC
