### ISSUE TITLE
[Feature Request] URL profiles

### ISSUE THREAD

**Issue by ponchohoncho** [gophish/gophish#877] opened 2017-12-08 21:57 UTC
The same way we have premade profiles for smtp servers, landing pages, and email templates, it would be nice to be able to preconfigure a few URLs.

In my case, I used a number of custom domains in front of gophish. One is a fake microsoft domain, a fake gmail domain, a fake linkedin domain, etc. being able to store these domains in a list would be helpful to be able to match the linkedin email template with the linkedin landing page with the linkedin SMTP profile and the linkedin URL.

In order to increase believably it would also be helpful to be able to use this same list to predefine the URL cruft i want to add to the domain, like: (maybe the template tokens in the URLs is a bit much, but it'd be cool!)

`https://www.fakelinkedin.com/e/rpp/77453361/{{.Email}}/54189456516987651494686/?hs=true&tok=30dasd834jk4o01`

`https://login.fakemicrosoft.com/common/oauth2/authorize?client_id=00000006-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dYpgBhtkjKGo42tXcOvJoCW0YCSK7wy1FKkMYW0NDw2p2j2gHTpfKIAsSJfG6aOmgtyk6jlMgxqrlvuP6jc-QMEPTbo9zQbVEXCL8jFNsGTyVOERA7JTSOw834TZZzt50ww5PszvzTxnBJssSUa28dkGKnyIF28NAaoeYQYL3nbUv4WwfP5HDFn9MkSN81xoL&nonce=636483668448602487.NzRmZmQzZDUtY2I1ZC00ZmZkLTkwOTQtOWY5Mjg2MTRjMDI0NjE4NjQyNjMtOWNiOC00NTkxLTgwMjQtMDI1ZTMyNWU4NTQ2&redirect_uri=https%3a%2f%2fportal.office.com%2flanding&ui_locales=en-US&mkt=en-US&client-request-id=8d9a82f5-7cd1-4642-9292-2d539188cf04&msafed=0`

`https://accounts.fakegoogle.com/signin/v2/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin`

the ?rid=ID would be appended to the end of all of these, of course

**Comment by ponchohoncho** [comment] 2017-12-08 22:06
A follow up feature could be Bundles, where we could define a set of landing page, email template, smtp, and url to apply them all in one click.

**Comment by jordan-wright** [comment] 2017-12-09 02:00
Hey there!

Thanks for reaching out. This appears to be a duplicate of #854, so I'll close this out in favor of tracking the implementation of this in that issue.

The good news is _yes_, this is a thing that we'll do. That is, we'll support multiple URLs saved similar to profiles. I can't see us doing the bundle situation yet, since that's essentially what a campaign is 😄 You can always copy a campaign and it'll open with the same url, landing page, template, smtp, etc.

Thanks again for getting in touch!

**Closed by jordan-wright** 2017-12-09 02:00 UTC
