### ISSUE TITLE
I can't use Chinese filling the <from> field in the New Sending Profile

### ISSUE THREAD

**Issue by edwardyeung** [gophish/gophish#404] opened 2016-10-20 09:34 UTC
The hint is `mail: missing word in phrase: mail: invalid string`

**Comment by jordan-wright** [comment] 2016-10-21 02:49
Hey @edwardyeung - thanks for letting us know about this. Unfortunately, I think this is an issue with Golang, no gophish. I don't believe Golang supports non-ascii characters in email addresses.

**Comment by jordan-wright** [comment] 2017-06-16 01:47
Closing this one out since it appears to be a duplicate of #135. We'll work from that issue to eventually track down the non-ascii characters in SMTP issue.

Thanks for this report!

**Closed by jordan-wright** 2017-06-16 01:47 UTC
Labels: duplicate
