### ISSUE TITLE
The connection was reset error

### ISSUE THREAD

**Issue by yogesh-imorsetech** [gophish/gophish#366] opened 2016-09-07 11:33 UTC
I could get gophish installed from source. Now my next problem is when I ran gophish binary and browse http://127.0.01:3333/login, it throws error - " The connection was reset".
Please check the attached console log screenshot.

![log](https://cloud.githubusercontent.com/assets/20571503/18310577/d14ca482-751c-11e6-80a0-e8d41b6713ea.png)

**Comment by jordan-wright** [comment] 2016-09-07 22:44
I believe this is a duplicate of #354 - can you confirm you are using Go v.1.7?

**Comment by yogesh-imorsetech** [comment] 2016-09-08 04:45
Yes its 1.7. Can you please help to get it working asap?

**Comment by jordan-wright** [comment] 2016-09-08 13:18
I will get it working when I have time. Gophish is a 100% volunteer effort.

In the meantime, I recommend using a version of Go < 1.7.

**Closed** 2016-09-08 13:18 UTC
Labels: support

**Comment by yogesh-imorsetech** [comment] 2016-09-08 13:21
How can I configure older version from source? I want to use campaign scheduling feature.

**Comment by yogesh-imorsetech** [comment] 2016-09-09 08:35
I tried with version 1.1 too but it gives same problem. Any help would be appreciated.
