### ISSUE TITLE
max connection attempts reached

### ISSUE THREAD

**Issue by velu120029** [gophish/gophish#959] opened 2018-02-07 07:25 UTC
I have downloaded from https://github.com/gophish/gophish/releases/download/v0.5.0/gophish-v0.5.0-linux-64bit.zip.

I am not able to send test mail as I am getting an error max connection attempts reached.

Kindly help

**Comment by jordan-wright** [comment] 2018-02-07 23:38
Hi @velu120029, thanks for reaching out. In the future, please use our issue template as it helps guide you towards providing the information needed to troubleshoot.

In the meantime, if you could please provide all the logs associated with what you're encountering, that'll help us get started.

**Comment by jordan-wright** [comment] 2018-02-08 22:17
Also, you might be interested to follow-along with #963, since it seems they may be having similar issues.

**Comment by mantis-le-sin** [comment] 2018-02-13 15:26
any news about that guys?

**Comment by jordan-wright** [comment] 2018-02-14 01:00
I'm going to go ahead and close this one out in favor of #963 where there's some more information and progress towards a fix.

Thanks for reaching out about this! Keep an eye out there for updates.

**Closed by jordan-wright** 2018-02-14 01:00 UTC
Labels: support

**Comment by Evekilel** [comment] 2018-02-20 06:12
Hi jordan, 

I have a custom cpanel login but I cannot send emails as it says max connection limit reached.

However I have tried with my gmail and it is working well. 

I don't quite get where the problem is with my cpanel

**Comment by Denzel-Washington** [comment] 2019-02-19 17:54
I got this error on first try after installing it , and send test email
 
Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials u127sm22353817pfu.165 - gsmtp
