### ISSUE TITLE
Data is not recording correctly 

### ISSUE THREAD

**Issue by mcvaa** [gophish/gophish#1207] opened 2018-09-21 18:09 UTC
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.7.1

Brief description of the issue:   Email reports correctly sent on dashboard and raw events. Once the user clicks the link and submits data it record under my email account information. This issue appears to occur on version 0.7.0 I then upgraded to the latest version same issue. I started from scratch did not copy over the db and same issue. 

What are you expecting to see happen? :  Each user that clicks the link in the email to record under their information for accurate information. 

What are you seeing happen? As listed above the information records under my email information see screen shot. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

Insert output here
![image](https://user-images.githubusercontent.com/14318521/45898855-3ae4dc80-bda9-11e8-96a1-d6d5a451a01d.png)

![image](https://user-images.githubusercontent.com/14318521/45898862-420bea80-bda9-11e8-982f-75f1fb6e4e92.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment] 2018-09-22 16:12
Hi @mcvaa,

Thanks for reaching out! Can you share a copy of what your email template looks like? Specifically, I'm interested in the way your structuring your links.

Gophish should associate captured events with the recipients ID (the `rid` parameter). So in this case it _appears_ that the link in the email is hardcoded to somehow point to your ID. You'll want to make sure you're structuring the link in your email to look something like this:

```html
<a href="{{.URL}}">Link</a>
```

**Comment by mcvaa** [comment] 2018-09-24 12:52
Hi Jordan,

Here is my email template:

{{.FirstName}}

Someone might have accessd your {{.Email}} account. You should consider verifying your identity by logging onto the site clicking on the _HQ Link_　and entering your credentials to authnticate.

If anyoe else has your account information they may attempt to access your personal or profesional work info.

If you require an account recovery, please consider clicking the _HQ Link_ again and attmpt to log into your account.　

Thank you for your cooperation with this seurity concern,

The IT Dept.

{{.Tracker}}

The HQ Link is the link for the authenticating webpage, I have added the screenshot below:
![emailtemplate](https://user-images.githubusercontent.com/14318521/45953124-24bc6380-bfd7-11e8-888d-719a06e377f9.PNG)

**Comment by rubberducky69** [comment] 2018-09-25 06:59
Is this is an actual phishing test? It could be because people are forwarding the mail to let fellow employees know, thus resulting in more clicks on the same ID from several users.

**Comment by mcvaa** [comment] 2018-09-26 13:08
Ok so I removed all campaigns and started fresh here is the test result of the newest campaign: 
![image](https://user-images.githubusercontent.com/14318521/46081624-fa9baa80-c16a-11e8-98d3-9daacc92d115.png)

As you can see there are two users myself and Mike. We both have different numbers. I have not clicked on the link in the email or submitted any data, but it clearly states that I have submitted data and Mike just had the email sent. 

Here is from the db event information:
![image](https://user-images.githubusercontent.com/14318521/46081826-78f84c80-c16b-11e8-89a4-db87db7c4051.png)

It is quite odd although Mike receives his own r_id when he clicks on the link in the email it redirects him and uses my r_id. I am creating a new landing page along with a new email template and will try again to see if we receive the same results. I will reply with the information.

Colleen

**Comment by mcvaa** [comment] 2018-09-26 13:21
Ok New campaign with the same exact results built a new landing page and a new email template are events: 
![image](https://user-images.githubusercontent.com/14318521/46082613-7ac30f80-c16d-11e8-95a6-f12bc42183df.png)

And Now the results:
![image](https://user-images.githubusercontent.com/14318521/46082660-99c1a180-c16d-11e8-81d5-47268f5cddb2.png)

**Comment by jordan-wright** [comment] 2018-09-27 00:39
Hi @mcvaa,

Thanks for the detailed response and follow-up! These are (on the surface, at least) good results, since we can see that Gophish is correctly creating separate `rid`'s for each user. This is the part that's odd to me:

> It is quite odd although Mike receives his own r_id when he clicks on the link in the email it redirects him and uses my r_id.

Just to confirm, you're saying that Mike receives a link with the correct `rid` but, when it's clicked, it is redirected to a link with your `rid`? If so, that's very, very odd indeed. 🤔 

Let's turn our attention to the templates and landing pages themselves. If it's ok with you, I'd like to run a test with the most simple templates and landing pages possible to see if that's what causing the problem.

If you have time, could you please make a template with this HTML:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p>This email was sent to {{.FirstName}}.</p>

<p>Please click <a href="{{.URL}}">this link.</a></p>
</body>
</html>
```

Then, please make a landing page with this HTML:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p>Hi {{.FirstName}}, you clicked the link, and an event should have been added in Gophish</p>
<p>Please submit this form</p>
<form action="" method="POST">
<input type="text" name="username" placeholder="any fake username"/>
<input type="password" name="password" placeholder="any fake password"/>
<input type="submit"/>
</body>
</html>
```

This is about as basic as a campaign can be, so if you see the same results, that would be even more peculiar. When running this campaign, please also confirm that the links received have the `rid` expected (by cross referencing what's in the database), as-in you have your `rid` and the other user has their correct `rid`.

If this yields the same results, we'll need to start looking at the network traffic itself.

Thanks again for your continued patience!

**Comment by mcvaa** [comment] 2018-09-27 13:55
Ok same results attached are screenshots of the process:

![2icands9272018](https://user-images.githubusercontent.com/14318521/46150560-d4454000-c23a-11e8-9383-373bc7b2c662.PNG)
![icands9272018](https://user-images.githubusercontent.com/14318521/46150561-d4454000-c23a-11e8-960e-30a50a223eba.PNG)
![mikeresultsdb9272018](https://user-images.githubusercontent.com/14318521/46150562-d4454000-c23a-11e8-9550-7f5599c4be7a.PNG)
![mikesubmitdb9272018](https://user-images.githubusercontent.com/14318521/46150563-d4454000-c23a-11e8-818c-97075b40762a.PNG)
![clicksubmitmike9272018](https://user-images.githubusercontent.com/14318521/46150564-d4454000-c23a-11e8-8f3c-74d85f454843.PNG)
![sentemail9272018](https://user-images.githubusercontent.com/14318521/46150565-d4454000-c23a-11e8-927d-5ceda5e2ecfc.PNG)
![aftersubmitipchange](https://user-images.githubusercontent.com/14318521/46150567-d4ddd680-c23a-11e8-9798-7f5d3ba0f9e6.PNG)
![differentipdb9272018](https://user-images.githubusercontent.com/14318521/46150568-d4ddd680-c23a-11e8-8909-aff84448c917.PNG)

I did create the above email template and Landing page 
![site](https://user-images.githubusercontent.com/14318521/46150807-69e0cf80-c23b-11e8-92c2-c18c01b4d795.PNG)
![emailfromcampaign](https://user-images.githubusercontent.com/14318521/46150808-69e0cf80-c23b-11e8-8472-25bc8cb1e34b.PNG)


I hope that helps

**Comment by jordan-wright** [comment] 2018-10-02 17:15
Hi @mcvaa,

Thanks for the update! It's odd - I don't immediately see anything wrong here. Both you and Mike have different `rid`'s assigned, the events are tracked with the correct ID (in that they see your `rid` and associate your recipient information).

In the final Outlook screenshot, is that your email account or Mike's? From what I gathered, this bug is that Mike was receiving emails that, when clicked, showed up under your results.

If you look at Mike's email, does it also claim to be sent to Colleen? Also, can you remind me the exact flow here? As in, Mike opens his email, sees that it was sent to him, clicks the link, confirms it shows his name, submits data, data shows up under Colleens records in Gophish, etc. etc.

**Comment by mcvaa** [comment] 2018-10-02 17:33
Hi,

That is correct Mike receives an email that was sent to both myself
(Colleen) and Mike. The email Mike receives clearly states Mike in the
email but when he clicks on the link it confirms that Colleen clicked on
the link even thought the email specified it was to him.

So for further troubleshooting I have a test server with Gophish set up
used the same landing page and the same email template and was unable to
repeat the result the difference with this test is that the GoPhish server
was version 5.0. So I copied the 5.0 version and moved it to my production
server ran the test again and wam same exact issue as the above problem.

Next test I am rebuilding a Windows 2012 R2 server and will install the
latest Windows 7.1.0 Gophish version create new templates and distribute a
new campaign. I will let you know how it goes.

If you have any ideas please let me know.

Colleen Vaa
Colleen Vaa

**Comment by jordan-wright** [comment] 2018-10-03 00:14
Please do let me know how it goes!

I'm sorry for the lack of quick answers but this is very.... unexpected behavior. I'm looking forward to hearing how the upgrade to 0.7.1 goes.

In the meantime, the only follow-up question I would have would be around the email itself. It appears that it would indicate that it was sent to Mike, but where does the link point to? Does the link contain Mike's `rid` or your `rid`? My guess is that it points to your `rid`, though that wouldn't explain why the email content would confirm it went to Mike.

**Comment by mcvaa** [comment] 2018-10-04 13:09
Ok that does explain it actually, because we are using a redirect. So how
can we change the URL without using an IIS redirect we don't want the IP
address to show when hovering over the link, we want it to be a specific
URL. This must have changed since the earlier version as my first campaign
using 5.0 I was able to copy the Link sent in the email an add it to our
HTTP redirect and it recorded all information.

Any suggestions?
Colleen Vaa

**Comment by mcvaa** [comment] 2018-10-04 18:55
UGH - Ok so I have built a new server I am fighting with creating a URL that is not an IP address so I don't need to use IIS redirect. Do you have any suggestions? 

Thank you,
Colleen

**Comment by mcvaa** [comment] 2018-10-11 17:20
Thank you Roberto-Carlo yes the A record is there was looking for an SSL
Cert that was truly secure but I have it taken care of now :)

Thank you again,
Colleen Vaa

**Comment by jordan-wright** [comment] 2018-10-28 16:40
Just checking in on this, it seems the issue was resolved so I'll go ahead and close this one out for now.

@mcvaa, if you're still encountering this issue, let us know and we'll be happy to re-open to continue troubleshooting. Thanks again for reaching out and your patience during troubleshooting!

**Closed by jordan-wright** 2018-10-28 16:40 UTC
Labels: support

**Comment by aukhan288** [comment] 2021-12-16 12:52
I want to get user id (user_id) from campaign table.
I edited for this achievement query in campaign.go file but it still return the old result
