### ISSUE TITLE
Multiple Landing Pages?

### ISSUE THREAD

**Issue by p4nic** [gophish/gophish#694] opened 2017-07-18 01:12 UTC
I attempted to create a gmail, using the new and old login forms. On the old one the next button would redirect, and on the new one, the next button straight up didn't work. Is there any way to make things like this work?

**Comment by jordan-wright** [comment] 2017-07-18 02:24
Currently, there isn't a clear native way to handle multiple redirect pages. You can host static content and try to redirect to it, but multiple redirects aren't supported and would have to be implemented using Javascript.

This should be handled by #223 when it gets implemented (coming soon) so I'm going to close this out as a duplicate of that issue.

**Closed by jordan-wright** 2017-07-18 02:24 UTC
