### ISSUE TITLE
Insert Date/Time

### ISSUE THREAD

**Issue by dragontologist** [gophish/gophish#512] opened 2017-01-11 19:36 UTC
It would be great to add some additional template options, such as a custom field beyond Position for every user. I would also love to see 
{{.Date}} and {{.Time}} (so that I don't have to update a template on shipping notifications every time I need to send it out)
{{.FullName}} (for us lazy people who don't want to have both first and last)
{{.RandomNumberX}} (where X represents the number of digits in the number you want to generate. This would be used to bypass many spam blockers that block based on a commonly seen subject line.)

**Comment by S0larflare** [comment] 2017-01-12 09:52
Im not sure of the value of the {{.FullName}} variable would be, couldn't you just put it all in FirstName or user {{.FirstName}} {{.LastName}}?

The others wouldn't necessarily be that difficult (although I can't find all the logic in the code which establishes the templates themselves). That said, I'm not sure whether just adding in a few variables would be the best way to go about it. Although it would be more work, I could see enabling people to create their own variables would be a better way to go (I think).

**Comment by jordan-wright** [comment] 2017-02-20 00:49
I just realized that this is a duplicate of #194. I am looking into different ways to support custom variables, but they're a ways off since it's a bit of a tricky thing to implement.

Closing this one, since it can be handled through other issues such as #194 and #27.

**Closed by jordan-wright** 2017-02-20 00:49 UTC
