### ISSUE TITLE
Cannot find mime/quotedprintable

### ISSUE THREAD

**Issue by cyopk** [gophish/gophish#121] opened 2016-02-03 02:37 UTC
hey there, thanks for sharing this app!

When I run "go get github.com/gophish/gophish" it seems to import everything except something called "mime/quotedprintable".
I saw that issue 80 touched on this but I have never installed GO before and so that case didn't help my problem unfortunately. 

I've then tried to build by running "go build" but this returns "cannot find package mime/quotedprintable" and stops me from building.

Lots of thanks in advance to anyone who can help :)

**Comment by jordan-wright** [comment] 2016-02-03 03:23
Make sure you have go version 1.5 installed. You can check this via go -version (or something like that :))

**Comment by jordan-wright** [comment] 2016-02-03 04:09
Ok, I verified it's "go version". Make sure you have >= 1.5 to have the mime/quotedprintable package.

For now, I'll go ahead and close this as a duplicate of #80.

**Comment by cyopk** [comment] 2016-02-03 04:10
Ah wow I'm sorry I never realised I had go already installed, thanks so much for your quick reply and it's working now, thanks again!

**Closed** 2016-02-03 04:09 UTC
Labels: duplicate, question
